// Static country data for attractions, phrases, prices, bestTimeToVisit, and funFacts.
// This data replaces the unreliable Gemini AI enrichment with deterministic, curated content.

import { extraAttractionsData, extraPhrasesData, extraPricesData, extraBestTimeToVisitData, extraFunFactsData } from './countryDataExtra.mjs';

export const knownAttractionsData = {
  nepal: [
    { name: "Boudhanath Stupa", city: "Kathmandu", famousFor: "One of the largest spherical stupas in Nepal and a UNESCO World Heritage Site", interestingFact: "The stupa's mandala design symbolizes the Buddhist cosmos", imageSearchQuery: "Boudhanath Stupa" },
    { name: "Pashupatinath Temple", city: "Kathmandu", famousFor: "Sacred Hindu temple dedicated to Lord Shiva on the bank of the Bagmati River", interestingFact: "One of the holiest Shiva temples in the world and a UNESCO site", imageSearchQuery: "Pashupatinath Temple", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Pashupatinath_Temple%2C_Kathmandu%2C_Nepal_%2839076%29.jpg/960px-Pashupatinath_Temple%2C_Kathmandu%2C_Nepal_%2839076%29.jpg" },
    { name: "Chitwan National Park", city: "Chitwan", famousFor: "UNESCO-listed park home to one-horned rhinos, Bengal tigers, and elephants", interestingFact: "Nepal's first national park, established in 1973", imageSearchQuery: "Chitwan National Park Nepal", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Chitwan_national_park_Rhinos.jpg/960px-Chitwan_national_park_Rhinos.jpg" },
    { name: "Phewa Lake", city: "Pokhara", famousFor: "Stunning freshwater lake reflecting the Annapurna mountain range", interestingFact: "The Tal Barahi Temple sits on an island in the middle of the lake", imageSearchQuery: "Phewa Lake Pokhara Nepal" },
    { name: "Swayambhunath (Monkey Temple)", city: "Kathmandu", famousFor: "Ancient religious complex atop a hill overlooking the Kathmandu Valley", interestingFact: "The site is over 2,500 years old and sacred to both Buddhists and Hindus", imageSearchQuery: "Swayambhunath Monkey Temple Kathmandu" },
  ],
  japan: [
    { name: "Fushimi Inari Shrine", city: "Kyoto", famousFor: "Thousands of iconic orange torii gates forming tunnels up a mountain", interestingFact: "The shrine has over 10,000 torii gates donated by businesses", imageSearchQuery: "Fushimi Inari Shrine Kyoto torii gates" },
    { name: "Senso-ji Temple", city: "Tokyo", famousFor: "Tokyo's oldest and most significant Buddhist temple", interestingFact: "Originally built in 645 AD, making it almost 1,400 years old", imageSearchQuery: "Senso-ji Temple Asakusa Tokyo" },
    { name: "Hiroshima Peace Memorial", city: "Hiroshima", famousFor: "UNESCO World Heritage Site commemorating the atomic bombing of 1945", interestingFact: "The Genbaku Dome is the only structure left standing near the bomb's hypocenter", imageSearchQuery: "Hiroshima Peace Memorial Genbaku Dome" },
    { name: "Arashiyama Bamboo Grove", city: "Kyoto", famousFor: "Towering bamboo stalks creating an otherworldly tunnel pathway", interestingFact: "The sound of wind through the bamboo was voted one of Japan's top 100 sounds", imageSearchQuery: "Arashiyama Bamboo Grove Kyoto" },
    { name: "Mount Fuji", city: "Shizuoka", famousFor: "Japan's tallest peak and an iconic cultural symbol", interestingFact: "The climbing season is only July-September; about 300,000 people climb it each year", imageSearchQuery: "Mount Fuji volcano" },
  ],
  france: [
    { name: "Eiffel Tower", city: "Paris", famousFor: "Iconic iron lattice tower and symbol of France", interestingFact: "It was originally intended to be dismantled after 20 years", imageSearchQuery: "Eiffel Tower Paris France" },
    { name: "Louvre Museum", city: "Paris", famousFor: "World's largest art museum, home to the Mona Lisa", interestingFact: "It would take 100 days to see every piece if you spent 30 seconds on each", imageSearchQuery: "Louvre Museum Paris glass pyramid" },
    { name: "Mont Saint-Michel", city: "Normandy", famousFor: "Medieval abbey perched on a tidal island", interestingFact: "The tides can rise up to 14 meters, the highest in continental Europe", imageSearchQuery: "Mont Saint-Michel Normandy France" },
    { name: "Palace of Versailles", city: "Versailles", famousFor: "Opulent royal palace with stunning gardens and Hall of Mirrors", interestingFact: "The palace has 2,300 rooms and 67 staircases", imageSearchQuery: "Palace of Versailles Hall of Mirrors" },
    { name: "Côte d'Azur", city: "Nice", famousFor: "The glamorous French Riviera coastline along the Mediterranean", interestingFact: "The term 'Côte d'Azur' was coined in 1887 by a poet", imageSearchQuery: "French Riviera Cote d'Azur Nice coastline" },
  ],
  'united states': [
    { name: "Statue of Liberty", city: "New York", famousFor: "Iconic symbol of freedom gifted by France in 1886", interestingFact: "The statue was originally copper-colored before oxidizing to its green patina", imageSearchQuery: "Statue of Liberty New York" },
    { name: "Grand Canyon", city: "Arizona", famousFor: "Massive gorge carved by the Colorado River over millions of years", interestingFact: "The canyon is 277 miles long, up to 18 miles wide, and over a mile deep", imageSearchQuery: "Grand Canyon Arizona panoramic view" },
    { name: "Golden Gate Bridge", city: "San Francisco", famousFor: "Iconic suspension bridge spanning the Golden Gate strait", interestingFact: "The bridge's color is called International Orange, chosen for visibility in fog", imageSearchQuery: "Golden Gate Bridge San Francisco" },
    { name: "Times Square", city: "New York", famousFor: "Bright, bustling commercial hub known as the Crossroads of the World", interestingFact: "Over 50 million people visit Times Square annually", imageSearchQuery: "Times Square New York City night" },
    { name: "Yellowstone National Park", city: "Wyoming", famousFor: "World's first national park with geysers, hot springs, and wildlife", interestingFact: "Old Faithful erupts approximately every 90 minutes", imageSearchQuery: "Yellowstone National Park Old Faithful geyser" },
  ],
  brazil: [
    { name: "Christ the Redeemer", city: "Rio de Janeiro", famousFor: "Iconic Art Deco statue of Jesus Christ atop Corcovado mountain", interestingFact: "The statue is 30 meters tall with arms stretching 28 meters wide", imageSearchQuery: "Christ the Redeemer Rio de Janeiro" },
    { name: "Iguazu Falls", city: "Foz do Iguaçu", famousFor: "Massive waterfall system on the border of Brazil and Argentina", interestingFact: "The falls are taller than Niagara Falls and twice as wide", imageSearchQuery: "Iguazu Falls Brazil panoramic" },
    { name: "Sugarloaf Mountain", city: "Rio de Janeiro", famousFor: "Iconic peak accessible by cable car with panoramic city views", interestingFact: "The cable car system has been running since 1912", imageSearchQuery: "Sugarloaf Mountain Rio de Janeiro cable car" },
    { name: "Amazon Rainforest", city: "Manaus", famousFor: "World's largest tropical rainforest and biodiversity hotspot", interestingFact: "The Amazon produces about 20% of the world's oxygen", imageSearchQuery: "Amazon River rainforest Manaus meeting of waters" },
    { name: "Pelourinho Historic Center", city: "Salvador", famousFor: "Colorful colonial architecture and Afro-Brazilian cultural hub", interestingFact: "Salvador was Brazil's first capital and a major hub of the African diaspora", imageSearchQuery: "Pelourinho Salvador Bahia colorful buildings" },
  ],
  mexico: [
    { name: "Chichen Itza", city: "Yucatan", famousFor: "Ancient Mayan pyramid and one of the New Seven Wonders of the World", interestingFact: "During equinoxes, shadows create a serpent illusion on the pyramid steps", imageSearchQuery: "Chichen Itza pyramid El Castillo" },
    { name: "Teotihuacan", city: "Mexico City", famousFor: "Ancient Mesoamerican city with the Pyramid of the Sun and Moon", interestingFact: "At its peak, Teotihuacan was one of the largest cities in the world with 200,000 people", imageSearchQuery: "Teotihuacan Pyramid of the Sun Mexico" },
    { name: "Cenotes of Yucatan", city: "Yucatan Peninsula", famousFor: "Natural sinkholes filled with crystal-clear water, sacred to the Maya", interestingFact: "There are over 6,000 cenotes in the Yucatan Peninsula", imageSearchQuery: "Yucatan cenote crystal clear water swimming" },
    { name: "Guanajuato", city: "Guanajuato", famousFor: "Colorful colonial city built in a ravine with underground tunnels", interestingFact: "The city's streets were once rivers, now converted to underground roads", imageSearchQuery: "Guanajuato Mexico colorful houses" },
    { name: "Tulum Ruins", city: "Tulum", famousFor: "Cliffside Mayan ruins overlooking turquoise Caribbean waters", interestingFact: "Tulum was one of the last cities built by the Maya, around 1200 AD", imageSearchQuery: "Tulum Ruins Mexico Caribbean coastline" },
  ],
  india: [
    { name: "Taj Mahal", city: "Agra", famousFor: "Ivory-white marble mausoleum and one of the New Seven Wonders", interestingFact: "It took 22 years and 20,000 workers to complete", imageSearchQuery: "Taj Mahal Agra India sunrise" },
    { name: "Jaipur City Palace", city: "Jaipur", famousFor: "Royal palace complex blending Rajasthani and Mughal architecture", interestingFact: "The royal family still lives in a portion of the palace", imageSearchQuery: "Jaipur City Palace Pink City India" },
    { name: "Kerala Backwaters", city: "Alleppey", famousFor: "Network of lagoons, lakes, and canals with traditional houseboat cruises", interestingFact: "The backwaters stretch over 900 km across Kerala", imageSearchQuery: "Kerala Backwaters houseboat Alleppey" },
    { name: "Varanasi Ghats", city: "Varanasi", famousFor: "Sacred riverfront steps along the Ganges River for Hindu rituals", interestingFact: "Varanasi is one of the oldest continuously inhabited cities in the world", imageSearchQuery: "Varanasi Ghats Ganges River ceremony" },
    { name: "Golden Temple", city: "Amritsar", famousFor: "Holiest Sikh gurdwara with stunning gold and marble architecture", interestingFact: "The temple's kitchen serves free meals to over 100,000 people daily", imageSearchQuery: "Golden Temple Amritsar India" },
  ],
  thailand: [
    { name: "Grand Palace", city: "Bangkok", famousFor: "Elaborate royal complex with the sacred Emerald Buddha temple", interestingFact: "Construction began in 1782 and was the official royal residence for 150 years", imageSearchQuery: "Grand Palace Bangkok Thailand" },
    { name: "Phi Phi Islands", city: "Krabi", famousFor: "Stunning tropical islands with turquoise waters and limestone cliffs", interestingFact: "Maya Bay was made famous by the movie 'The Beach' starring Leonardo DiCaprio", imageSearchQuery: "Phi Phi Islands Thailand turquoise water" },
    { name: "Wat Pho", city: "Bangkok", famousFor: "Temple of the Reclining Buddha, 46 meters long and covered in gold leaf", interestingFact: "Wat Pho is considered the birthplace of traditional Thai massage", imageSearchQuery: "Wat Pho Reclining Buddha Bangkok" },
    { name: "Chiang Mai Old City", city: "Chiang Mai", famousFor: "Walled historic center with hundreds of ancient Buddhist temples", interestingFact: "The city was founded in 1296 as the capital of the Lanna Kingdom", imageSearchQuery: "Chiang Mai temples old city Thailand" },
    { name: "Railay Beach", city: "Krabi", famousFor: "Paradise beach surrounded by dramatic limestone karst cliffs", interestingFact: "Railay is only accessible by boat despite being on the mainland", imageSearchQuery: "Railay Beach Krabi Thailand limestone cliffs" },
  ],
  'south korea': [
    { name: "Gyeongbokgung Palace", city: "Seoul", famousFor: "Grand Joseon dynasty palace with traditional changing of the guard ceremony", interestingFact: "The palace was originally built in 1395 and has been destroyed and rebuilt multiple times", imageSearchQuery: "Gyeongbokgung Palace Seoul Korea" },
    { name: "Bukchon Hanok Village", city: "Seoul", famousFor: "Traditional Korean village with hundreds of hanok houses between two palaces", interestingFact: "Some of the hanok houses are over 600 years old and still inhabited", imageSearchQuery: "Bukchon Hanok Village Seoul traditional houses" },
    { name: "Jeju Island", city: "Jeju", famousFor: "Volcanic island with stunning landscapes, waterfalls, and lava tubes", interestingFact: "Jeju has its own unique language and culture distinct from mainland Korea", imageSearchQuery: "Jeju Island volcanic landscape South Korea" },
    { name: "Lotte World Tower", city: "Seoul", famousFor: "555-meter supertall skyscraper with observation deck and stunning city views", interestingFact: "It is the tallest building in South Korea and the 6th tallest in the world", imageSearchQuery: "Lotte World Tower Seoul" },
    { name: "N Seoul Tower", city: "Seoul", famousFor: "Iconic observation tower on Namsan Mountain with panoramic city views", interestingFact: "The tower's love locks area has over 100,000 padlocks from couples", imageSearchQuery: "N Seoul Tower Namsan night view" },
  ],
  'korea (republic of)': [
    { name: "Gyeongbokgung Palace", city: "Seoul", famousFor: "Grand Joseon dynasty palace with traditional changing of the guard ceremony", interestingFact: "The palace was originally built in 1395 and has been destroyed and rebuilt multiple times", imageSearchQuery: "Gyeongbokgung Palace Seoul Korea" },
    { name: "Bukchon Hanok Village", city: "Seoul", famousFor: "Traditional Korean village with hundreds of hanok houses between two palaces", interestingFact: "Some of the hanok houses are over 600 years old and still inhabited", imageSearchQuery: "Bukchon Hanok Village Seoul traditional houses" },
    { name: "Jeju Island", city: "Jeju", famousFor: "Volcanic island with stunning landscapes, waterfalls, and lava tubes", interestingFact: "Jeju has its own unique language and culture distinct from mainland Korea", imageSearchQuery: "Jeju Island volcanic landscape South Korea" },
    { name: "Lotte World Tower", city: "Seoul", famousFor: "555-meter supertall skyscraper with observation deck and stunning city views", interestingFact: "It is the tallest building in South Korea and the 6th tallest in the world", imageSearchQuery: "Lotte World Tower Seoul" },
    { name: "N Seoul Tower", city: "Seoul", famousFor: "Iconic observation tower on Namsan Mountain with panoramic city views", interestingFact: "The tower's love locks area has over 100,000 padlocks from couples", imageSearchQuery: "N Seoul Tower Namsan night view" },
  ],
  china: [
    { name: "Great Wall of China", city: "Beijing", famousFor: "Ancient fortification stretching over 13,000 miles across northern China", interestingFact: "It took over 2,000 years to build, with construction starting in the 7th century BC", imageSearchQuery: "Great Wall of China Beijing Badaling" },
    { name: "Forbidden City", city: "Beijing", famousFor: "Imperial palace complex with nearly 1,000 buildings from the Ming and Qing dynasties", interestingFact: "It has 9,999 rooms — one less than the mythical 10,000 rooms in heaven", imageSearchQuery: "Forbidden City Beijing aerial view" },
    { name: "Terracotta Warriors", city: "Xi'an", famousFor: "Thousands of life-sized clay soldiers buried to protect Emperor Qin Shi Huang", interestingFact: "Every single warrior has a unique face; no two are identical", imageSearchQuery: "Terracotta Warriors Xi'an China army" },
    { name: "Li River Cruise", city: "Guilin", famousFor: "Scenic river journey through dramatic karst mountain landscapes", interestingFact: "The landscape appears on the 20 yuan banknote", imageSearchQuery: "Li River Guilin karst mountains cruise" },
    { name: "The Bund", city: "Shanghai", famousFor: "Waterfront promenade showcasing colonial-era architecture against the modern skyline", interestingFact: "The Bund contains 52 buildings in various architectural styles from around the world", imageSearchQuery: "The Bund Shanghai waterfront skyline night" },
  ],
  germany: [
    { name: "Brandenburg Gate", city: "Berlin", famousFor: "Iconic neoclassical monument symbolizing German unity", interestingFact: "During the Cold War, the gate stood in no-man's land between East and West Berlin", imageSearchQuery: "Brandenburg Gate Berlin Germany" },
    { name: "Neuschwanstein Castle", city: "Schwangau", famousFor: "Fairy-tale castle that inspired Disney's Sleeping Beauty Castle", interestingFact: "King Ludwig II only lived in the castle for 172 days before his death", imageSearchQuery: "Neuschwanstein Castle Bavaria fairy tale" },
    { name: "Cologne Cathedral", city: "Cologne", famousFor: "Gothic masterpiece and UNESCO World Heritage Site with twin spires", interestingFact: "Construction took over 600 years to complete, from 1248 to 1880", imageSearchQuery: "Cologne Cathedral Gothic spires Germany" },
    { name: "Pergamon Museum", city: "Berlin", famousFor: "World-class museum with monumental archaeological reconstructions", interestingFact: "The museum houses the Ishtar Gate of Babylon, built around 575 BC", imageSearchQuery: "Ishtar Gate Pergamon Museum Berlin" },
    { name: "Black Forest", city: "Baden-Württemberg", famousFor: "Dense forested mountain range famous for cuckoo clocks and Black Forest cake", interestingFact: "The Brothers Grimm set many of their fairy tales in the Black Forest", imageSearchQuery: "Schwarzwald Black Forest village Germany" },
  ],
  italy: [
    { name: "Colosseum", city: "Rome", famousFor: "Ancient Roman amphitheater that could seat 50,000 spectators", interestingFact: "The Colosseum had a retractable awning called the velarium to shade spectators", imageSearchQuery: "Colosseum Rome Italy ancient amphitheater" },
    { name: "Venice Canals", city: "Venice", famousFor: "Romantic city built on 118 islands connected by bridges and canals", interestingFact: "Venice has no roads — transportation is entirely by water or on foot", imageSearchQuery: "Venice canals gondola Italy" },
    { name: "Leaning Tower of Pisa", city: "Pisa", famousFor: "Famous bell tower tilting at nearly 4 degrees", interestingFact: "The lean began during construction in 1173 due to soft ground on one side", imageSearchQuery: "Leaning Tower of Pisa Italy" },
    { name: "Amalfi Coast", city: "Amalfi", famousFor: "Dramatic coastline with cliffside villages and Mediterranean vistas", interestingFact: "The road along the coast was built in the 19th century and clings to 600-meter cliffs", imageSearchQuery: "Amalfi Coast Italy colorful cliffside" },
    { name: "Pompeii", city: "Naples", famousFor: "Ancient Roman city preserved under volcanic ash from Mount Vesuvius eruption in 79 AD", interestingFact: "About a third of the city still remains unexcavated", imageSearchQuery: "Pompeii ruins Italy Mount Vesuvius" },
  ],
  'united kingdom': [
    { name: "Tower of London", city: "London", famousFor: "Historic castle housing the Crown Jewels and centuries of royal history", interestingFact: "Six ravens are kept at the Tower; legend says if they leave, the kingdom will fall", imageSearchQuery: "Tower of London Crown Jewels" },
    { name: "Stonehenge", city: "Wiltshire", famousFor: "Prehistoric stone circle dating back 5,000 years", interestingFact: "Some stones were transported over 150 miles from Wales — the method remains debated", imageSearchQuery: "Stonehenge Wiltshire England" },
    { name: "Buckingham Palace", city: "London", famousFor: "Official residence of the British monarch with the famous Changing of the Guard", interestingFact: "The palace has 775 rooms, including 78 bathrooms", imageSearchQuery: "Buckingham Palace London guards" },
    { name: "Edinburgh Castle", city: "Edinburgh", famousFor: "Dramatic hilltop fortress dominating the Scottish capital's skyline", interestingFact: "The castle sits on an extinct volcanic rock and has been a royal residence since the 12th century", imageSearchQuery: "Edinburgh Castle Scotland hilltop" },
    { name: "Big Ben & Houses of Parliament", city: "London", famousFor: "Iconic Gothic Revival buildings on the banks of the Thames", interestingFact: "Big Ben technically refers only to the bell, not the tower, which is the Elizabeth Tower", imageSearchQuery: "Big Ben Houses of Parliament London" },
  ],
  australia: [
    { name: "Sydney Opera House", city: "Sydney", famousFor: "Architectural masterpiece and UNESCO World Heritage Site on the harbor", interestingFact: "The roof is covered with over 1 million tiles, all made in Sweden", imageSearchQuery: "Sydney Opera House harbour bridge" },
    { name: "Great Barrier Reef", city: "Queensland", famousFor: "World's largest coral reef system visible from space", interestingFact: "The reef is home to over 1,500 species of fish and 400 types of coral", imageSearchQuery: "Great Barrier Reef Australia aerial coral" },
    { name: "Uluru (Ayers Rock)", city: "Northern Territory", famousFor: "Sacred Aboriginal monolith that changes color at sunrise and sunset", interestingFact: "Uluru stands 348 meters high but extends another 2.5 km underground", imageSearchQuery: "Uluru Ayers Rock sunset Australia" },
    { name: "Great Ocean Road", city: "Victoria", famousFor: "Scenic coastal drive featuring the Twelve Apostles rock formations", interestingFact: "The road was built by returned soldiers after World War I as a war memorial", imageSearchQuery: "Great Ocean Road Twelve Apostles Victoria" },
    { name: "Bondi Beach", city: "Sydney", famousFor: "Iconic Australian beach and surf culture destination", interestingFact: "The Bondi to Coogee coastal walk is one of the most photographed walks in Australia", imageSearchQuery: "Bondi Beach Sydney Australia surfing" },
  ],
  spain: [
    { name: "La Sagrada Familia", city: "Barcelona", famousFor: "Gaudí's unfinished masterpiece basilica, under construction since 1882", interestingFact: "Expected completion is 2026, over 140 years after construction began", imageSearchQuery: "Sagrada Familia Barcelona Gaudi" },
    { name: "Alhambra", city: "Granada", famousFor: "Stunning Moorish palace and fortress complex with intricate Islamic architecture", interestingFact: "The Alhambra's name means 'The Red One' in Arabic, referring to its reddish walls", imageSearchQuery: "Alhambra Granada Spain Moorish palace" },
    { name: "Park Güell", city: "Barcelona", famousFor: "Colorful mosaic-covered park designed by Antoni Gaudí", interestingFact: "Originally intended as a housing development, only two houses were built before becoming a park", imageSearchQuery: "Park Guell Barcelona mosaic Gaudi" },
    { name: "Plaza de España", city: "Seville", famousFor: "Grand semicircular plaza with tiled alcoves representing Spain's provinces", interestingFact: "The plaza was featured as Naboo in Star Wars Episode II", imageSearchQuery: "Plaza de España Seville Spain" },
    { name: "Prado Museum", city: "Madrid", famousFor: "One of the world's greatest art museums with works by Velázquez, Goya, and El Greco", interestingFact: "The museum has over 8,000 paintings but only about 1,300 are on display", imageSearchQuery: "Museo del Prado Madrid building facade" },
  ],
  egypt: [
    { name: "Pyramids of Giza", city: "Giza", famousFor: "Last remaining Wonder of the Ancient World, built over 4,500 years ago", interestingFact: "The Great Pyramid was the tallest man-made structure for over 3,800 years", imageSearchQuery: "Pyramids of Giza Egypt Great Pyramid Sphinx" },
    { name: "Valley of the Kings", city: "Luxor", famousFor: "Ancient burial ground with tombs of pharaohs including Tutankhamun", interestingFact: "Over 60 tombs have been discovered, but many more may remain hidden", imageSearchQuery: "Valley of the Kings Luxor Egypt tombs" },
    { name: "Karnak Temple", city: "Luxor", famousFor: "Vast temple complex dedicated to the god Amun with massive columns", interestingFact: "Karnak was built over a period of 2,000 years by successive pharaohs", imageSearchQuery: "Karnak Temple Luxor Egypt columns" },
    { name: "Abu Simbel", city: "Aswan", famousFor: "Colossal rock-cut temples built by Ramses II with four massive statues", interestingFact: "The entire temple was relocated in 1968 to save it from rising Nile waters", imageSearchQuery: "Abu Simbel temple Ramses statues Egypt" },
    { name: "Egyptian Museum", city: "Cairo", famousFor: "Home to King Tutankhamun's golden mask and thousands of ancient artifacts", interestingFact: "The museum holds over 120,000 items, many still uncatalogued", imageSearchQuery: "Museum of Egyptian Antiquities Cairo building" },
  ],
  turkey: [
    { name: "Hagia Sophia", city: "Istanbul", famousFor: "Architectural marvel that served as church, mosque, museum, and mosque again", interestingFact: "Its dome was the world's largest for nearly a thousand years", imageSearchQuery: "Hagia Sophia Istanbul Turkey dome interior" },
    { name: "Cappadocia", city: "Nevşehir", famousFor: "Surreal landscape of fairy chimneys and hot air balloon rides at sunrise", interestingFact: "Early Christians carved underground cities up to 18 stories deep to hide from persecution", imageSearchQuery: "Cappadocia hot air balloons fairy chimneys Turkey" },
    { name: "Pamukkale", city: "Denizli", famousFor: "White travertine terraces of mineral-rich thermal waters", interestingFact: "The name means 'Cotton Castle' in Turkish due to its white appearance", imageSearchQuery: "Pamukkale white terraces thermal pools Turkey" },
    { name: "Ephesus", city: "Selçuk", famousFor: "Well-preserved ancient Greek-Roman city with the Library of Celsus", interestingFact: "Ancient Ephesus was one of the largest cities in the Roman Empire with 250,000 people", imageSearchQuery: "Ephesus Library of Celsus ruins Turkey" },
    { name: "Blue Mosque", city: "Istanbul", famousFor: "Stunning Ottoman-era mosque with six minarets and blue-tiled interior", interestingFact: "It is the only mosque in Turkey with six minarets", imageSearchQuery: "Blue Mosque Sultan Ahmed Istanbul" },
  ],
  vietnam: [
    { name: "Ha Long Bay", city: "Quang Ninh", famousFor: "UNESCO World Heritage Site with thousands of limestone karst islands", interestingFact: "Ha Long means 'Descending Dragon' in Vietnamese legend", imageSearchQuery: "Ha Long Bay Vietnam limestone islands junk boat" },
    { name: "Hoi An Ancient Town", city: "Hoi An", famousFor: "Beautifully preserved historic trading port with lantern-lit streets", interestingFact: "Hoi An was a major Southeast Asian trading port from the 15th to 19th century", imageSearchQuery: "Hoi An Ancient Town lanterns Vietnam" },
    { name: "Cu Chi Tunnels", city: "Ho Chi Minh City", famousFor: "Vast underground tunnel network used during the Vietnam War", interestingFact: "The tunnel system stretches over 250 km and had hospitals, kitchens, and living quarters", imageSearchQuery: "Cu Chi tunnels entrance Vietnam" },
    { name: "Phong Nha Caves", city: "Quang Binh", famousFor: "World's largest caves with underground rivers and ancient formations", interestingFact: "Son Doong Cave here is the world's largest, with its own weather system inside", imageSearchQuery: "Phong Nha Cave Son Doong Vietnam" },
    { name: "Imperial City of Hue", city: "Hue", famousFor: "Walled fortress and palace complex of the Nguyen dynasty emperors", interestingFact: "The citadel was modeled after the Forbidden City in Beijing", imageSearchQuery: "Imperial City Hue Vietnam Forbidden Purple City" },
  ],
  greece: [
    { name: "Acropolis", city: "Athens", famousFor: "Ancient citadel with the iconic Parthenon temple", interestingFact: "The Parthenon was built in just 9 years (447-438 BC)", imageSearchQuery: "Acropolis Athens Parthenon Greece" },
    { name: "Santorini", city: "Santorini", famousFor: "Stunning volcanic island with white-washed buildings and blue domed churches", interestingFact: "The island was formed by one of the largest volcanic eruptions in recorded history", imageSearchQuery: "Santorini blue domes white buildings sunset" },
    { name: "Meteora", city: "Thessaly", famousFor: "Monasteries perched atop towering natural rock pillars", interestingFact: "Monks originally climbed these rocks using nets and ladders to find spiritual isolation", imageSearchQuery: "Meteora monasteries Greece rock pillars" },
    { name: "Delphi", city: "Phocis", famousFor: "Ancient sanctuary considered the center of the world in Greek mythology", interestingFact: "The Oracle of Delphi was the most important oracle in the ancient Greek world", imageSearchQuery: "Delphi ruins Temple of Apollo Greece" },
    { name: "Mykonos", city: "Mykonos", famousFor: "Cosmopolitan island famous for windmills, beaches, and vibrant nightlife", interestingFact: "The island's narrow winding streets were designed to confuse pirate invaders", imageSearchQuery: "Mykonos windmills Greece Little Venice" },
  ],
  canada: [
    { name: "Niagara Falls", city: "Ontario", famousFor: "Massive waterfall straddling the US-Canada border", interestingFact: "About 750,000 gallons of water flow over the falls every second", imageSearchQuery: "Niagara Falls Canada Horseshoe Falls" },
    { name: "Banff National Park", city: "Alberta", famousFor: "Stunning Rocky Mountain scenery with turquoise lakes and glaciers", interestingFact: "Banff was Canada's first national park, established in 1885", imageSearchQuery: "Banff National Park Lake Louise turquoise" },
    { name: "CN Tower", city: "Toronto", famousFor: "Iconic communications tower with glass floor and revolving restaurant", interestingFact: "It was the world's tallest free-standing structure for 34 years", imageSearchQuery: "CN Tower Toronto skyline Canada" },
    { name: "Old Quebec", city: "Quebec City", famousFor: "Historic district with cobblestone streets and French colonial architecture", interestingFact: "Quebec City is the only walled city north of Mexico in North America", imageSearchQuery: "Old Quebec City Chateau Frontenac winter" },
    { name: "Stanley Park", city: "Vancouver", famousFor: "1,000-acre urban park with beaches, trails, and totem poles", interestingFact: "The park's seawall is the world's longest uninterrupted waterfront path at 22 km", imageSearchQuery: "Stanley Park Vancouver seawall totems" },
  ],
  argentina: [
    { name: "Iguazu Falls", city: "Misiones", famousFor: "One of the world's largest waterfall systems with 275 individual cascades", interestingFact: "The 'Devil's Throat' section is a U-shaped chasm 80 meters high", imageSearchQuery: "Iguazu Falls Argentina Devil's Throat" },
    { name: "Perito Moreno Glacier", city: "El Calafate", famousFor: "Spectacular advancing glacier in Los Glaciares National Park", interestingFact: "It is one of the few glaciers in the world that is still growing", imageSearchQuery: "Perito Moreno Glacier El Calafate Argentina" },
    { name: "Buenos Aires La Boca", city: "Buenos Aires", famousFor: "Colorful neighborhood known for tango, street art, and Italian heritage", interestingFact: "La Boca's buildings were painted with leftover ship paint from the nearby port", imageSearchQuery: "La Boca Buenos Aires colorful buildings tango" },
    { name: "Tierra del Fuego", city: "Ushuaia", famousFor: "The 'End of the World' — southernmost city with dramatic landscapes", interestingFact: "Ushuaia is the southernmost city in the world and a gateway to Antarctica", imageSearchQuery: "Ushuaia Tierra del Fuego National Park" },
    { name: "Quebrada de Humahuaca", city: "Jujuy", famousFor: "UNESCO-listed valley with colorful rock formations and Inca heritage", interestingFact: "The Cerro de los Siete Colores displays seven distinct rock colors", imageSearchQuery: "Quebrada de Humahuaca Jujuy Argentina seven colors" },
  ],
  peru: [
    { name: "Machu Picchu", city: "Cusco", famousFor: "Ancient Inca citadel set high in the Andes, a New Seven Wonder", interestingFact: "It was unknown to the outside world until 1911 when discovered by Hiram Bingham", imageSearchQuery: "Machu Picchu Peru Inca citadel panoramic" },
    { name: "Sacred Valley", city: "Cusco", famousFor: "Fertile valley with Inca ruins, traditional markets, and terraced hillsides", interestingFact: "The Incas built agricultural terraces that are still functional today", imageSearchQuery: "Sacred Valley Ollantaytambo ruins Peru" },
    { name: "Nazca Lines", city: "Nazca", famousFor: "Mysterious giant geoglyphs etched into the desert, best seen from the air", interestingFact: "The lines were made between 500 BC and 500 AD but their purpose remains unknown", imageSearchQuery: "Nazca Lines geoglyph hummingbird" },
    { name: "Lake Titicaca", city: "Puno", famousFor: "World's highest navigable lake, shared between Peru and Bolivia", interestingFact: "The Uros people live on floating islands made entirely of reeds on the lake", imageSearchQuery: "Lake Titicaca Uros floating islands Peru" },
    { name: "Colca Canyon", city: "Arequipa", famousFor: "One of the world's deepest canyons and home to Andean condors", interestingFact: "Colca Canyon is twice as deep as the Grand Canyon", imageSearchQuery: "Colca Canyon Arequipa Peru condor" },
  ],
  portugal: [
    { name: "Belém Tower", city: "Lisbon", famousFor: "Iconic 16th-century fortified tower and UNESCO World Heritage Site", interestingFact: "It served as the departure point for Portuguese explorers during the Age of Discovery", imageSearchQuery: "Belem Tower Lisbon Portugal waterfront" },
    { name: "Sintra Palaces", city: "Sintra", famousFor: "Colorful Pena Palace and mystical Quinta da Regaleira", interestingFact: "Lord Byron called Sintra 'the most beautiful village in the world'", imageSearchQuery: "Pena Palace Sintra Portugal colorful" },
    { name: "Douro Valley", city: "Porto", famousFor: "Terraced vineyards along the Douro River, birthplace of Port wine", interestingFact: "The Douro Valley is the oldest demarcated wine region in the world", imageSearchQuery: "Douro Valley Porto Portugal terraced vineyards" },
    { name: "Ribeira District", city: "Porto", famousFor: "Colorful riverside neighborhood and UNESCO World Heritage Site", interestingFact: "Porto's name gave Portugal its name and Port wine its identity", imageSearchQuery: "Ribeira Porto Portugal riverside colorful" },
    { name: "Algarve Caves", city: "Algarve", famousFor: "Dramatic sea caves and golden cliffs along the southern coast", interestingFact: "Benagil Cave is accessible only by boat and has a natural skylight in the ceiling", imageSearchQuery: "Algarve sea caves Benagil Portugal" },
  ],
  russia: [
    { name: "Red Square", city: "Moscow", famousFor: "Iconic public square surrounded by the Kremlin, St. Basil's, and GUM", interestingFact: "The square's name comes from the Russian word 'krasnaya' which originally meant 'beautiful'", imageSearchQuery: "Red Square Moscow St Basils Cathedral" },
    { name: "Hermitage Museum", city: "St. Petersburg", famousFor: "One of the world's largest museums with over 3 million artworks", interestingFact: "If you spent 1 minute at each exhibit, it would take 11 years to see everything", imageSearchQuery: "Hermitage Museum Winter Palace St Petersburg" },
    { name: "Lake Baikal", city: "Irkutsk", famousFor: "World's deepest and oldest freshwater lake", interestingFact: "Lake Baikal holds 20% of the world's unfrozen surface fresh water", imageSearchQuery: "Lake Baikal Siberia Russia ice winter" },
    { name: "St. Basil's Cathedral", city: "Moscow", famousFor: "Colorful onion domes that are an iconic symbol of Russia", interestingFact: "Legend says Ivan the Terrible blinded the architect so he could never build anything more beautiful", imageSearchQuery: "St Basils Cathedral Moscow colorful domes" },
    { name: "Trans-Siberian Railway", city: "Moscow to Vladivostok", famousFor: "World's longest railway line spanning 9,289 km across Russia", interestingFact: "The journey takes about 6 days and crosses 7 time zones", imageSearchQuery: "Trans-Siberian Railway train station Vladivostok" },
  ],
  indonesia: [
    { name: "Borobudur", city: "Yogyakarta", famousFor: "World's largest Buddhist temple, a UNESCO World Heritage Site", interestingFact: "The temple has 72 bell-shaped stupas, each containing a Buddha statue", imageSearchQuery: "Borobudur Temple Yogyakarta sunrise Indonesia" },
    { name: "Bali Temples", city: "Bali", famousFor: "Stunning Hindu temples including Tanah Lot and Uluwatu", interestingFact: "Bali has over 20,000 temples — at least one in every home", imageSearchQuery: "Tanah Lot Temple Bali sunset Indonesia" },
    { name: "Komodo National Park", city: "East Nusa Tenggara", famousFor: "Home to the Komodo dragon, the world's largest lizard", interestingFact: "Komodo dragons can grow up to 3 meters long and weigh over 70 kg", imageSearchQuery: "Komodo dragon National Park Indonesia" },
    { name: "Raja Ampat Islands", city: "West Papua", famousFor: "Pristine marine paradise with the highest coral reef biodiversity on Earth", interestingFact: "Raja Ampat has more marine species than anywhere else on the planet", imageSearchQuery: "Raja Ampat Islands Wayag Indonesia" },
    { name: "Ubud Rice Terraces", city: "Bali", famousFor: "Iconic UNESCO-listed rice terraces using traditional Subak irrigation", interestingFact: "The Subak water management system dates back to the 9th century", imageSearchQuery: "Tegalalang Rice Terraces Ubud Bali green" },
  ],
  ...extraAttractionsData,
};

export const knownPhrasesData = {
  nepal: [
    { english: "Hello", local: "नमस्ते (Namaste)", pronunciation: "nah-mas-tay" },
    { english: "Thank you", local: "धन्यवाद (Dhanyabad)", pronunciation: "dhun-yah-bahd" },
    { english: "Please", local: "कृपया (Kripaya)", pronunciation: "kri-pah-yah" },
    { english: "Excuse me", local: "माफ गर्नुहोस् (Maaf garnuhos)", pronunciation: "maaf gar-noo-hohs" },
    { english: "Goodbye", local: "नमस्ते (Namaste)", pronunciation: "nah-mas-tay" },
    { english: "How much?", local: "कति हो? (Kati ho?)", pronunciation: "kah-tee ho" },
    { english: "Yes", local: "हो (Ho)", pronunciation: "ho" },
    { english: "No", local: "होइन (Hoina)", pronunciation: "hoy-na" },
    { english: "Help", local: "मद्दत (Maddat)", pronunciation: "mud-dat" },
    { english: "Where is...?", local: "...कहाँ छ? (Kaha chha?)", pronunciation: "kah-haa chha" },
  ],
  japan: [
    { english: "Hello", local: "こんにちは (Konnichiwa)", pronunciation: "kohn-nee-chee-wah" },
    { english: "Thank you", local: "ありがとう (Arigatou)", pronunciation: "ah-ree-gah-toh" },
    { english: "Please", local: "お願いします (Onegaishimasu)", pronunciation: "oh-neh-gai-shee-mahs" },
    { english: "Excuse me", local: "すみません (Sumimasen)", pronunciation: "soo-mee-mah-sen" },
    { english: "Goodbye", local: "さようなら (Sayounara)", pronunciation: "sah-yoh-nah-rah" },
    { english: "How much?", local: "いくらですか (Ikura desu ka)", pronunciation: "ee-koo-rah des-kah" },
    { english: "Yes", local: "はい (Hai)", pronunciation: "hai" },
    { english: "No", local: "いいえ (Iie)", pronunciation: "ee-eh" },
    { english: "Help", local: "助けて (Tasukete)", pronunciation: "tah-soo-keh-teh" },
    { english: "Where is...?", local: "...はどこですか (Wa doko desu ka)", pronunciation: "wah doh-koh des-kah" },
  ],
  france: [
    { english: "Hello", local: "Bonjour", pronunciation: "bohn-zhoor" },
    { english: "Thank you", local: "Merci", pronunciation: "mehr-see" },
    { english: "Please", local: "S'il vous plaît", pronunciation: "seel voo pleh" },
    { english: "Excuse me", local: "Excusez-moi", pronunciation: "ex-koo-zay mwah" },
    { english: "Goodbye", local: "Au revoir", pronunciation: "oh reh-vwahr" },
    { english: "How much?", local: "Combien?", pronunciation: "kohm-bee-ehn" },
    { english: "Yes", local: "Oui", pronunciation: "wee" },
    { english: "No", local: "Non", pronunciation: "nohn" },
    { english: "Help", local: "Au secours!", pronunciation: "oh suh-koor" },
    { english: "Where is...?", local: "Où est...?", pronunciation: "oo eh" },
  ],
  'united states': [
    { english: "Hello", local: "Hello / Hi", pronunciation: "heh-loh / hai" },
    { english: "Thank you", local: "Thank you / Thanks", pronunciation: "thank yoo" },
    { english: "Please", local: "Please", pronunciation: "pleez" },
    { english: "Excuse me", local: "Excuse me", pronunciation: "ex-kyooz me" },
    { english: "Goodbye", local: "Goodbye / Bye", pronunciation: "good-bye" },
    { english: "How much?", local: "How much is this?", pronunciation: "how much iz this" },
    { english: "Yes", local: "Yes / Yeah", pronunciation: "yes / yeh" },
    { english: "No", local: "No / Nope", pronunciation: "noh" },
    { english: "Help", local: "Help!", pronunciation: "help" },
    { english: "Where is...?", local: "Where is...?", pronunciation: "wehr iz" },
  ],
  brazil: [
    { english: "Hello", local: "Olá", pronunciation: "oh-lah" },
    { english: "Thank you", local: "Obrigado/Obrigada", pronunciation: "oh-bree-gah-doo (m) / oh-bree-gah-dah (f)" },
    { english: "Please", local: "Por favor", pronunciation: "pohr fah-vohr" },
    { english: "Excuse me", local: "Com licença", pronunciation: "kohm lee-sen-sah" },
    { english: "Goodbye", local: "Tchau", pronunciation: "chow" },
    { english: "How much?", local: "Quanto custa?", pronunciation: "kwahn-too koos-tah" },
    { english: "Yes", local: "Sim", pronunciation: "seem" },
    { english: "No", local: "Não", pronunciation: "now" },
    { english: "Help", local: "Socorro!", pronunciation: "soh-koh-hoo" },
    { english: "Where is...?", local: "Onde fica...?", pronunciation: "ohn-jee fee-kah" },
  ],
  mexico: [
    { english: "Hello", local: "Hola", pronunciation: "oh-lah" },
    { english: "Thank you", local: "Gracias", pronunciation: "grah-see-ahs" },
    { english: "Please", local: "Por favor", pronunciation: "pohr fah-vohr" },
    { english: "Excuse me", local: "Disculpe", pronunciation: "dees-kool-peh" },
    { english: "Goodbye", local: "Adiós", pronunciation: "ah-dee-ohs" },
    { english: "How much?", local: "¿Cuánto cuesta?", pronunciation: "kwahn-toh kwes-tah" },
    { english: "Yes", local: "Sí", pronunciation: "see" },
    { english: "No", local: "No", pronunciation: "noh" },
    { english: "Help", local: "¡Ayuda!", pronunciation: "ah-yoo-dah" },
    { english: "Where is...?", local: "¿Dónde está...?", pronunciation: "dohn-deh es-tah" },
  ],
  india: [
    { english: "Hello", local: "नमस्ते (Namaste)", pronunciation: "nah-mas-tay" },
    { english: "Thank you", local: "धन्यवाद (Dhanyavaad)", pronunciation: "dhun-yah-vahd" },
    { english: "Please", local: "कृपया (Kripaya)", pronunciation: "kri-pah-yah" },
    { english: "Excuse me", local: "माफ कीजिए (Maaf kijiye)", pronunciation: "maaf kee-jee-yay" },
    { english: "Goodbye", local: "अलविदा (Alvida)", pronunciation: "al-vee-dah" },
    { english: "How much?", local: "कितना है? (Kitna hai?)", pronunciation: "kit-nah hai" },
    { english: "Yes", local: "हाँ (Haan)", pronunciation: "haan" },
    { english: "No", local: "नहीं (Nahin)", pronunciation: "nah-heen" },
    { english: "Help", local: "मदद! (Madad!)", pronunciation: "muh-dud" },
    { english: "Where is...?", local: "...कहाँ है? (Kahan hai?)", pronunciation: "kah-haan hai" },
  ],
  thailand: [
    { english: "Hello", local: "สวัสดี (Sawasdee)", pronunciation: "sah-waht-dee" },
    { english: "Thank you", local: "ขอบคุณ (Khob khun)", pronunciation: "kohp koon" },
    { english: "Please", local: "กรุณา (Karuna)", pronunciation: "gah-roo-nah" },
    { english: "Excuse me", local: "ขอโทษ (Kho thot)", pronunciation: "kaw toht" },
    { english: "Goodbye", local: "ลาก่อน (La gon)", pronunciation: "lah gohn" },
    { english: "How much?", local: "เท่าไร่ (Tao rai)", pronunciation: "tow-rai" },
    { english: "Yes", local: "ครับ/ค่ะ (Krab/Ka)", pronunciation: "krahp (m) / kah (f)" },
    { english: "No", local: "ไม่ (Mai)", pronunciation: "mai" },
    { english: "Help", local: "ช่วยด้วย! (Chuay duay!)", pronunciation: "choo-ay doo-ay" },
    { english: "Where is...?", local: "...อยู่ที่ไหน (Yu tee nai)", pronunciation: "yoo tee nai" },
  ],
  'south korea': [
    { english: "Hello", local: "안녕하세요 (Annyeonghaseyo)", pronunciation: "ahn-nyeong-hah-seh-yo" },
    { english: "Thank you", local: "감사합니다 (Gamsahamnida)", pronunciation: "gahm-sah-hahm-nee-dah" },
    { english: "Please", local: "주세요 (Juseyo)", pronunciation: "joo-seh-yo" },
    { english: "Excuse me", local: "실례합니다 (Sillyehamnida)", pronunciation: "sheel-lyeh-hahm-nee-dah" },
    { english: "Goodbye", local: "안녕히 가세요 (Annyeonghi gaseyo)", pronunciation: "ahn-nyeong-hee gah-seh-yo" },
    { english: "How much?", local: "얼마예요? (Eolmayeyo?)", pronunciation: "uhl-mah-yeh-yo" },
    { english: "Yes", local: "네 (Ne)", pronunciation: "neh" },
    { english: "No", local: "아니요 (Aniyo)", pronunciation: "ah-nee-yo" },
    { english: "Help", local: "도와주세요! (Dowajuseyo!)", pronunciation: "doh-wah-joo-seh-yo" },
    { english: "Where is...?", local: "...어디예요? (Eodiyeyo?)", pronunciation: "uh-dee-yeh-yo" },
  ],
  'korea (republic of)': [
    { english: "Hello", local: "안녕하세요 (Annyeonghaseyo)", pronunciation: "ahn-nyeong-hah-seh-yo" },
    { english: "Thank you", local: "감사합니다 (Gamsahamnida)", pronunciation: "gahm-sah-hahm-nee-dah" },
    { english: "Please", local: "주세요 (Juseyo)", pronunciation: "joo-seh-yo" },
    { english: "Excuse me", local: "실례합니다 (Sillyehamnida)", pronunciation: "sheel-lyeh-hahm-nee-dah" },
    { english: "Goodbye", local: "안녕히 가세요 (Annyeonghi gaseyo)", pronunciation: "ahn-nyeong-hee gah-seh-yo" },
    { english: "How much?", local: "얼마예요? (Eolmayeyo?)", pronunciation: "uhl-mah-yeh-yo" },
    { english: "Yes", local: "네 (Ne)", pronunciation: "neh" },
    { english: "No", local: "아니요 (Aniyo)", pronunciation: "ah-nee-yo" },
    { english: "Help", local: "도와주세요! (Dowajuseyo!)", pronunciation: "doh-wah-joo-seh-yo" },
    { english: "Where is...?", local: "...어디예요? (Eodiyeyo?)", pronunciation: "uh-dee-yeh-yo" },
  ],
  china: [
    { english: "Hello", local: "你好 (Nǐ hǎo)", pronunciation: "nee how" },
    { english: "Thank you", local: "谢谢 (Xièxiè)", pronunciation: "shyeh-shyeh" },
    { english: "Please", local: "请 (Qǐng)", pronunciation: "ching" },
    { english: "Excuse me", local: "对不起 (Duìbùqǐ)", pronunciation: "dway-boo-chee" },
    { english: "Goodbye", local: "再见 (Zàijiàn)", pronunciation: "zai-jee-en" },
    { english: "How much?", local: "多少钱? (Duōshǎo qián?)", pronunciation: "dwoh-shaow chee-en" },
    { english: "Yes", local: "是 (Shì)", pronunciation: "shih" },
    { english: "No", local: "不是 (Bùshì)", pronunciation: "boo-shih" },
    { english: "Help", local: "救命! (Jiùmìng!)", pronunciation: "jyoh-ming" },
    { english: "Where is...?", local: "...在哪里? (Zài nǎlǐ?)", pronunciation: "zai nah-lee" },
  ],
  germany: [
    { english: "Hello", local: "Hallo / Guten Tag", pronunciation: "hah-loh / goo-ten tahg" },
    { english: "Thank you", local: "Danke", pronunciation: "dahn-keh" },
    { english: "Please", local: "Bitte", pronunciation: "bit-teh" },
    { english: "Excuse me", local: "Entschuldigung", pronunciation: "ent-shool-dee-goong" },
    { english: "Goodbye", local: "Auf Wiedersehen", pronunciation: "owf vee-der-zeh-en" },
    { english: "How much?", local: "Wie viel kostet das?", pronunciation: "vee feel kos-tet dahs" },
    { english: "Yes", local: "Ja", pronunciation: "yah" },
    { english: "No", local: "Nein", pronunciation: "nine" },
    { english: "Help", local: "Hilfe!", pronunciation: "hill-feh" },
    { english: "Where is...?", local: "Wo ist...?", pronunciation: "voh ist" },
  ],
  italy: [
    { english: "Hello", local: "Ciao / Buongiorno", pronunciation: "chow / bwon-jor-noh" },
    { english: "Thank you", local: "Grazie", pronunciation: "grah-tsee-eh" },
    { english: "Please", local: "Per favore", pronunciation: "pehr fah-voh-reh" },
    { english: "Excuse me", local: "Scusi", pronunciation: "skoo-zee" },
    { english: "Goodbye", local: "Arrivederci", pronunciation: "ah-ree-veh-dehr-chee" },
    { english: "How much?", local: "Quanto costa?", pronunciation: "kwahn-toh koh-stah" },
    { english: "Yes", local: "Sì", pronunciation: "see" },
    { english: "No", local: "No", pronunciation: "noh" },
    { english: "Help", local: "Aiuto!", pronunciation: "ah-yoo-toh" },
    { english: "Where is...?", local: "Dov'è...?", pronunciation: "doh-veh" },
  ],
  'united kingdom': [
    { english: "Hello", local: "Hello / Hiya", pronunciation: "heh-loh / hi-yah" },
    { english: "Thank you", local: "Thank you / Cheers", pronunciation: "thank yoo / cheerz" },
    { english: "Please", local: "Please", pronunciation: "pleez" },
    { english: "Excuse me", local: "Excuse me / Pardon", pronunciation: "ex-kyooz me / par-dun" },
    { english: "Goodbye", local: "Goodbye / Cheerio", pronunciation: "good-bye / cheer-ee-oh" },
    { english: "How much?", local: "How much is this?", pronunciation: "how much iz this" },
    { english: "Yes", local: "Yes", pronunciation: "yes" },
    { english: "No", local: "No", pronunciation: "noh" },
    { english: "Help", local: "Help!", pronunciation: "help" },
    { english: "Where is...?", local: "Where is...?", pronunciation: "wehr iz" },
  ],
  australia: [
    { english: "Hello", local: "G'day", pronunciation: "guh-day" },
    { english: "Thank you", local: "Thanks / Ta", pronunciation: "thanks / tah" },
    { english: "Please", local: "Please", pronunciation: "pleez" },
    { english: "Excuse me", local: "Excuse me / Sorry", pronunciation: "ex-kyooz me" },
    { english: "Goodbye", local: "See ya / Catch ya later", pronunciation: "see yah / catch yah" },
    { english: "How much?", local: "How much is this?", pronunciation: "how much iz this" },
    { english: "Yes", local: "Yeah / Yep", pronunciation: "yeh / yep" },
    { english: "No", local: "No / Nah", pronunciation: "noh / nah" },
    { english: "Help", local: "Help!", pronunciation: "help" },
    { english: "Where is...?", local: "Where's...?", pronunciation: "wehrz" },
  ],
  spain: [
    { english: "Hello", local: "Hola", pronunciation: "oh-lah" },
    { english: "Thank you", local: "Gracias", pronunciation: "grah-see-ahs" },
    { english: "Please", local: "Por favor", pronunciation: "pohr fah-vohr" },
    { english: "Excuse me", local: "Perdone", pronunciation: "pehr-doh-neh" },
    { english: "Goodbye", local: "Adiós", pronunciation: "ah-dee-ohs" },
    { english: "How much?", local: "¿Cuánto cuesta?", pronunciation: "kwahn-toh kwes-tah" },
    { english: "Yes", local: "Sí", pronunciation: "see" },
    { english: "No", local: "No", pronunciation: "noh" },
    { english: "Help", local: "¡Socorro!", pronunciation: "soh-koh-roh" },
    { english: "Where is...?", local: "¿Dónde está...?", pronunciation: "dohn-deh es-tah" },
  ],
  egypt: [
    { english: "Hello", local: "السلام عليكم (As-salamu alaykum)", pronunciation: "ahs-sah-lah-moo ah-lay-koom" },
    { english: "Thank you", local: "شكرا (Shukran)", pronunciation: "shoo-krahn" },
    { english: "Please", local: "من فضلك (Min fadlak)", pronunciation: "min fahd-lahk" },
    { english: "Excuse me", local: "لو سمحت (Law samaht)", pronunciation: "law sah-maht" },
    { english: "Goodbye", local: "مع السلامة (Ma'a salama)", pronunciation: "mah-ah sah-lah-mah" },
    { english: "How much?", local: "بكام ده? (Bikam da?)", pronunciation: "bee-kahm dah" },
    { english: "Yes", local: "أيوة (Aiwa)", pronunciation: "eye-wah" },
    { english: "No", local: "لا (La)", pronunciation: "lah" },
    { english: "Help", local: "مساعدة! (Musa'da!)", pronunciation: "moo-sah-dah" },
    { english: "Where is...?", local: "...فين? (Fein?)", pronunciation: "fein" },
  ],
  turkey: [
    { english: "Hello", local: "Merhaba", pronunciation: "mehr-hah-bah" },
    { english: "Thank you", local: "Teşekkür ederim", pronunciation: "teh-shehk-kur eh-deh-reem" },
    { english: "Please", local: "Lütfen", pronunciation: "loot-fen" },
    { english: "Excuse me", local: "Affedersiniz", pronunciation: "ahf-feh-dehr-see-neez" },
    { english: "Goodbye", local: "Hoşça kal", pronunciation: "hosh-chah kahl" },
    { english: "How much?", local: "Ne kadar?", pronunciation: "neh kah-dahr" },
    { english: "Yes", local: "Evet", pronunciation: "eh-vet" },
    { english: "No", local: "Hayır", pronunciation: "hai-yuhr" },
    { english: "Help", local: "İmdat!", pronunciation: "im-daht" },
    { english: "Where is...?", local: "...nerede?", pronunciation: "neh-reh-deh" },
  ],
  vietnam: [
    { english: "Hello", local: "Xin chào", pronunciation: "sin chow" },
    { english: "Thank you", local: "Cảm ơn", pronunciation: "kahm uhn" },
    { english: "Please", local: "Làm ơn", pronunciation: "lahm uhn" },
    { english: "Excuse me", local: "Xin lỗi", pronunciation: "sin loy" },
    { english: "Goodbye", local: "Tạm biệt", pronunciation: "tahm bee-yet" },
    { english: "How much?", local: "Bao nhiêu?", pronunciation: "bow nyee-oo" },
    { english: "Yes", local: "Vâng / Dạ", pronunciation: "vuhng / yah" },
    { english: "No", local: "Không", pronunciation: "kohm" },
    { english: "Help", local: "Cứu tôi!", pronunciation: "koo-oo toy" },
    { english: "Where is...?", local: "...ở đâu?", pronunciation: "uh dow" },
  ],
  greece: [
    { english: "Hello", local: "Γεια σας (Yia sas)", pronunciation: "yah-sahs" },
    { english: "Thank you", local: "Ευχαριστώ (Efcharistó)", pronunciation: "ef-khah-ree-stoh" },
    { english: "Please", local: "Παρακαλώ (Parakaló)", pronunciation: "pah-rah-kah-loh" },
    { english: "Excuse me", local: "Συγνώμη (Signómi)", pronunciation: "seeg-noh-mee" },
    { english: "Goodbye", local: "Αντίο (Adío)", pronunciation: "ah-dee-oh" },
    { english: "How much?", local: "Πόσο κάνει; (Póso kani?)", pronunciation: "poh-soh kah-nee" },
    { english: "Yes", local: "Ναι (Ne)", pronunciation: "neh" },
    { english: "No", local: "Όχι (Óchi)", pronunciation: "oh-hee" },
    { english: "Help", local: "Βοήθεια! (Voíthia!)", pronunciation: "voh-ee-thee-ah" },
    { english: "Where is...?", local: "Πού είναι; (Poú íne?)", pronunciation: "poo ee-neh" },
  ],
  canada: [
    { english: "Hello", local: "Hello / Bonjour", pronunciation: "heh-loh / bohn-zhoor" },
    { english: "Thank you", local: "Thank you / Merci", pronunciation: "thank yoo / mehr-see" },
    { english: "Please", local: "Please / S'il vous plaît", pronunciation: "pleez / seel voo pleh" },
    { english: "Excuse me", local: "Excuse me / Excusez-moi", pronunciation: "ex-kyooz me / ex-koo-zay mwah" },
    { english: "Goodbye", local: "Goodbye / Au revoir", pronunciation: "good-bye / oh reh-vwahr" },
    { english: "How much?", local: "How much? / Combien?", pronunciation: "how much / kohm-bee-ehn" },
    { english: "Yes", local: "Yes / Oui", pronunciation: "yes / wee" },
    { english: "No", local: "No / Non", pronunciation: "noh / nohn" },
    { english: "Help", local: "Help! / Au secours!", pronunciation: "help / oh suh-koor" },
    { english: "Where is...?", local: "Where is...? / Où est...?", pronunciation: "wehr iz / oo eh" },
  ],
  argentina: [
    { english: "Hello", local: "Hola", pronunciation: "oh-lah" },
    { english: "Thank you", local: "Gracias", pronunciation: "grah-see-ahs" },
    { english: "Please", local: "Por favor", pronunciation: "pohr fah-vohr" },
    { english: "Excuse me", local: "Disculpa", pronunciation: "dees-kool-pah" },
    { english: "Goodbye", local: "Chau", pronunciation: "chow" },
    { english: "How much?", local: "¿Cuánto sale?", pronunciation: "kwahn-toh sah-leh" },
    { english: "Yes", local: "Sí", pronunciation: "see" },
    { english: "No", local: "No", pronunciation: "noh" },
    { english: "Help", local: "¡Ayuda!", pronunciation: "ah-yoo-dah" },
    { english: "Where is...?", local: "¿Dónde queda...?", pronunciation: "dohn-deh keh-dah" },
  ],
  peru: [
    { english: "Hello", local: "Hola", pronunciation: "oh-lah" },
    { english: "Thank you", local: "Gracias", pronunciation: "grah-see-ahs" },
    { english: "Please", local: "Por favor", pronunciation: "pohr fah-vohr" },
    { english: "Excuse me", local: "Disculpe", pronunciation: "dees-kool-peh" },
    { english: "Goodbye", local: "Adiós / Chau", pronunciation: "ah-dee-ohs / chow" },
    { english: "How much?", local: "¿Cuánto cuesta?", pronunciation: "kwahn-toh kwes-tah" },
    { english: "Yes", local: "Sí", pronunciation: "see" },
    { english: "No", local: "No", pronunciation: "noh" },
    { english: "Help", local: "¡Ayuda!", pronunciation: "ah-yoo-dah" },
    { english: "Where is...?", local: "¿Dónde está...?", pronunciation: "dohn-deh es-tah" },
  ],
  portugal: [
    { english: "Hello", local: "Olá", pronunciation: "oh-lah" },
    { english: "Thank you", local: "Obrigado/Obrigada", pronunciation: "oh-bree-gah-doo (m) / oh-bree-gah-dah (f)" },
    { english: "Please", local: "Por favor", pronunciation: "pohr fah-vohr" },
    { english: "Excuse me", local: "Com licença", pronunciation: "kohm lee-sen-sah" },
    { english: "Goodbye", local: "Adeus", pronunciation: "ah-day-oosh" },
    { english: "How much?", local: "Quanto custa?", pronunciation: "kwahn-too koos-tah" },
    { english: "Yes", local: "Sim", pronunciation: "seem" },
    { english: "No", local: "Não", pronunciation: "now" },
    { english: "Help", local: "Socorro!", pronunciation: "soh-koh-hoo" },
    { english: "Where is...?", local: "Onde fica...?", pronunciation: "ohn-jee fee-kah" },
  ],
  russia: [
    { english: "Hello", local: "Здравствуйте (Zdravstvuyte)", pronunciation: "zdrahst-voo-teh" },
    { english: "Thank you", local: "Спасибо (Spasibo)", pronunciation: "spah-see-boh" },
    { english: "Please", local: "Пожалуйста (Pozhaluysta)", pronunciation: "pah-ZHAHL-stah" },
    { english: "Excuse me", local: "Извините (Izvinite)", pronunciation: "eez-vee-nee-teh" },
    { english: "Goodbye", local: "До свидания (Do svidaniya)", pronunciation: "dah svee-dah-nee-yah" },
    { english: "How much?", local: "Сколько стоит? (Skolko stoit?)", pronunciation: "skohl-koh stoh-eet" },
    { english: "Yes", local: "Да (Da)", pronunciation: "dah" },
    { english: "No", local: "Нет (Nyet)", pronunciation: "nyet" },
    { english: "Help", local: "Помогите! (Pomogite!)", pronunciation: "pah-mah-gee-teh" },
    { english: "Where is...?", local: "Где...? (Gde?)", pronunciation: "gdyeh" },
  ],
  indonesia: [
    { english: "Hello", local: "Halo / Selamat", pronunciation: "hah-loh / seh-lah-maht" },
    { english: "Thank you", local: "Terima kasih", pronunciation: "teh-ree-mah kah-see" },
    { english: "Please", local: "Tolong", pronunciation: "toh-long" },
    { english: "Excuse me", local: "Permisi", pronunciation: "per-mee-see" },
    { english: "Goodbye", local: "Selamat tinggal", pronunciation: "seh-lah-maht ting-gahl" },
    { english: "How much?", local: "Berapa?", pronunciation: "beh-rah-pah" },
    { english: "Yes", local: "Ya", pronunciation: "yah" },
    { english: "No", local: "Tidak", pronunciation: "tee-dahk" },
    { english: "Help", local: "Tolong!", pronunciation: "toh-long" },
    { english: "Where is...?", local: "Di mana...?", pronunciation: "dee mah-nah" },
  ],
  ...extraPhrasesData,
};

export const knownPricesData = {
  nepal: { hotel: "$15-60 per night", meal: "$2-10", streetFood: "$0.50-2", coffee: "$0.50-2", transport: "$0.25-1", taxi: "$0.50-2 per km" },
  japan: { hotel: "$80-250 per night", meal: "$10-30", streetFood: "$3-8", coffee: "$3-5", transport: "$2-5", taxi: "$5-10 per km" },
  france: { hotel: "$100-300 per night", meal: "$15-40", streetFood: "$5-10", coffee: "$2-5", transport: "$2-3", taxi: "$2-4 per km" },
  'united states': { hotel: "$100-300 per night", meal: "$15-40", streetFood: "$5-12", coffee: "$3-6", transport: "$2-3", taxi: "$2-4 per km" },
  brazil: { hotel: "$30-120 per night", meal: "$5-20", streetFood: "$2-5", coffee: "$1-3", transport: "$1-2", taxi: "$1-3 per km" },
  mexico: { hotel: "$30-100 per night", meal: "$5-15", streetFood: "$1-4", coffee: "$1-3", transport: "$0.50-1", taxi: "$1-2 per km" },
  india: { hotel: "$15-80 per night", meal: "$2-10", streetFood: "$0.50-2", coffee: "$0.50-2", transport: "$0.25-0.50", taxi: "$0.50-1 per km" },
  thailand: { hotel: "$20-80 per night", meal: "$3-10", streetFood: "$1-3", coffee: "$1-3", transport: "$0.50-1", taxi: "$1-2 per km" },
  'south korea': { hotel: "$50-200 per night", meal: "$8-20", streetFood: "$2-5", coffee: "$3-5", transport: "$1-2", taxi: "$2-4 per km" },
  'korea (republic of)': { hotel: "$50-200 per night", meal: "$8-20", streetFood: "$2-5", coffee: "$3-5", transport: "$1-2", taxi: "$2-4 per km" },
  china: { hotel: "$30-150 per night", meal: "$3-15", streetFood: "$1-3", coffee: "$2-5", transport: "$0.50-1", taxi: "$1-2 per km" },
  germany: { hotel: "$80-200 per night", meal: "$10-25", streetFood: "$3-8", coffee: "$2-4", transport: "$2-4", taxi: "$2-3 per km" },
  italy: { hotel: "$70-250 per night", meal: "$12-30", streetFood: "$3-8", coffee: "$1-3", transport: "$1.50-2", taxi: "$2-3 per km" },
  'united kingdom': { hotel: "$90-300 per night", meal: "$12-35", streetFood: "$5-10", coffee: "$3-5", transport: "$3-6", taxi: "$3-5 per km" },
  australia: { hotel: "$80-250 per night", meal: "$15-35", streetFood: "$5-12", coffee: "$3-5", transport: "$3-5", taxi: "$3-5 per km" },
  spain: { hotel: "$60-180 per night", meal: "$10-25", streetFood: "$3-7", coffee: "$1-3", transport: "$1.50-2", taxi: "$1-2 per km" },
  egypt: { hotel: "$20-80 per night", meal: "$3-10", streetFood: "$0.50-2", coffee: "$0.50-2", transport: "$0.25-0.50", taxi: "$0.50-1 per km" },
  turkey: { hotel: "$30-120 per night", meal: "$5-15", streetFood: "$1-3", coffee: "$1-3", transport: "$0.50-1", taxi: "$0.50-2 per km" },
  vietnam: { hotel: "$15-60 per night", meal: "$2-8", streetFood: "$0.50-2", coffee: "$0.50-2", transport: "$0.25-0.50", taxi: "$0.50-1 per km" },
  greece: { hotel: "$60-200 per night", meal: "$10-25", streetFood: "$3-7", coffee: "$2-4", transport: "$1.50-2", taxi: "$1-2 per km" },
  canada: { hotel: "$80-250 per night", meal: "$15-35", streetFood: "$5-10", coffee: "$3-5", transport: "$3-4", taxi: "$2-4 per km" },
  argentina: { hotel: "$25-100 per night", meal: "$5-15", streetFood: "$1-4", coffee: "$1-3", transport: "$0.50-1", taxi: "$1-2 per km" },
  peru: { hotel: "$20-80 per night", meal: "$3-12", streetFood: "$1-3", coffee: "$1-2", transport: "$0.50-1", taxi: "$0.50-2 per km" },
  portugal: { hotel: "$50-150 per night", meal: "$8-20", streetFood: "$3-6", coffee: "$1-2", transport: "$1.50-2", taxi: "$1-2 per km" },
  russia: { hotel: "$40-150 per night", meal: "$5-20", streetFood: "$2-5", coffee: "$2-4", transport: "$0.50-1", taxi: "$1-3 per km" },
  indonesia: { hotel: "$15-80 per night", meal: "$2-8", streetFood: "$0.50-2", coffee: "$1-2", transport: "$0.25-0.50", taxi: "$0.50-1 per km" },
  ...extraPricesData,
};

export const knownBestTimeToVisitData = {
  nepal: { bestMonths: "October to November (post-monsoon, clear skies for trekking and mountain views) and March to April (pre-monsoon, warmer weather).", rainySeason: "June to September (monsoon season, heavy rainfall, can affect travel and trekking).", cheapestSeason: "Monsoon (June-September) and winter (December-February, though colder in higher altitudes).", majorFestivals: ["Dashain (September/October)", "Tihar (October/November)", "Holi (March)", "Indra Jatra (September)"] },
  japan: { bestMonths: "March to May (cherry blossom season, mild weather) and September to November (autumn foliage, comfortable temperatures).", rainySeason: "June to mid-July (tsuyu rainy season, humid and wet across most regions).", cheapestSeason: "January to February (cold winter, fewer tourists outside ski areas).", majorFestivals: ["Cherry Blossom Season (March-April)", "Obon Festival (August)", "Gion Matsuri (July, Kyoto)", "New Year (January)"] },
  france: { bestMonths: "April to June (spring blooms, mild weather) and September to October (harvest season, fewer crowds).", rainySeason: "November to March (cool and rainy, especially in northern France).", cheapestSeason: "November to March (off-season, lower hotel and flight prices).", majorFestivals: ["Bastille Day (July 14)", "Cannes Film Festival (May)", "Nice Carnival (February)", "Fête de la Musique (June 21)"] },
  'united states': { bestMonths: "April to June and September to November (pleasant weather in most regions, fall foliage in the northeast).", rainySeason: "Varies widely by region; Southeast is wettest June to September, Pacific Northwest October to March.", cheapestSeason: "January to March (post-holiday lull, excluding ski destinations).", majorFestivals: ["Independence Day (July 4)", "Thanksgiving (November)", "Mardi Gras (February-March, New Orleans)", "Halloween (October 31)"] },
  brazil: { bestMonths: "April to June and August to October (dry season, pleasant temperatures across most regions).", rainySeason: "December to March (heavy tropical rainfall, especially in the Amazon and Rio).", cheapestSeason: "March to May (shoulder season, after Carnival crowds leave).", majorFestivals: ["Carnival (February-March)", "Festas Juninas (June)", "Reveillon/New Year (December 31)", "Oktoberfest Blumenau (October)"] },
  mexico: { bestMonths: "December to April (dry season, warm days, cool evenings, ideal for beaches and ruins).", rainySeason: "June to October (afternoon storms, hurricane season on coasts).", cheapestSeason: "May to June and September to November (shoulder seasons, lower prices).", majorFestivals: ["Day of the Dead (November 1-2)", "Independence Day (September 16)", "Guelaguetza (July, Oaxaca)", "Semana Santa (March-April)"] },
  india: { bestMonths: "October to March (cool, dry winter season ideal for sightseeing across most regions).", rainySeason: "June to September (southwest monsoon, heavy rains nationwide).", cheapestSeason: "April to June (extreme heat in most regions, fewer tourists).", majorFestivals: ["Diwali (October-November)", "Holi (March)", "Navratri/Dussehra (October)", "Republic Day (January 26)"] },
  thailand: { bestMonths: "November to February (cool and dry season, most comfortable for travel).", rainySeason: "June to October (monsoon season, frequent heavy showers, especially afternoons).", cheapestSeason: "March to May (hot season, extreme heat but great hotel deals).", majorFestivals: ["Songkran Water Festival (April 13-15)", "Loy Krathong (November)", "Yi Peng Lantern Festival (November)", "Thai New Year (April)"] },
  'south korea': { bestMonths: "March to May (cherry blossoms, mild spring) and September to November (stunning autumn foliage).", rainySeason: "June to August (hot, humid monsoon season called jangma).", cheapestSeason: "December to February (cold winters, but great for skiing and hot springs).", majorFestivals: ["Chuseok (September-October)", "Seollal/Lunar New Year (January-February)", "Cherry Blossom Festival (April)", "Boryeong Mud Festival (July)"] },
  'korea (republic of)': { bestMonths: "March to May (cherry blossoms, mild spring) and September to November (stunning autumn foliage).", rainySeason: "June to August (hot, humid monsoon season called jangma).", cheapestSeason: "December to February (cold winters, but great for skiing and hot springs).", majorFestivals: ["Chuseok (September-October)", "Seollal/Lunar New Year (January-February)", "Cherry Blossom Festival (April)", "Boryeong Mud Festival (July)"] },
  china: { bestMonths: "April to May and September to October (mild temperatures, clear skies across most regions).", rainySeason: "June to August (heavy monsoon rains in southern and eastern China).", cheapestSeason: "November to March (cold winter, fewer tourists except Chinese New Year).", majorFestivals: ["Chinese New Year (January-February)", "Mid-Autumn Festival (September-October)", "Dragon Boat Festival (June)", "Lantern Festival (February)"] },
  germany: { bestMonths: "May to September (warm, long daylight hours, outdoor beer gardens and festivals).", rainySeason: "Year-round moderate rainfall, heaviest in summer thunderstorms.", cheapestSeason: "November to March (cold and grey, but magical Christmas markets in December).", majorFestivals: ["Oktoberfest (September-October, Munich)", "Christmas Markets (December)", "Karneval/Fasching (February-March)", "Berlin Festival of Lights (October)"] },
  italy: { bestMonths: "April to June and September to October (warm but not scorching, fewer crowds than peak summer).", rainySeason: "November to March (cool and wet, especially in the north).", cheapestSeason: "November to March (off-season, significant discounts on hotels).", majorFestivals: ["Venice Carnival (February)", "Ferragosto (August 15)", "Easter celebrations (March-April)", "Palio di Siena (July and August)"] },
  'united kingdom': { bestMonths: "May to September (longest days, warmest weather, though rain is always possible).", rainySeason: "October to March (frequent rain, short daylight hours, grey skies).", cheapestSeason: "November to March (excluding Christmas and New Year holidays).", majorFestivals: ["Bonfire Night (November 5)", "Notting Hill Carnival (August)", "Edinburgh Fringe Festival (August)", "Glastonbury Festival (June)"] },
  australia: { bestMonths: "September to November and March to May (mild autumn/spring, comfortable across most regions).", rainySeason: "December to March in northern tropical regions (cyclone season).", cheapestSeason: "June to August (Australian winter, except ski areas; great for northern tropical visits).", majorFestivals: ["Australia Day (January 26)", "Vivid Sydney (May-June)", "Melbourne Cup (November)", "Sydney New Year Fireworks (December 31)"] },
  spain: { bestMonths: "April to June and September to October (warm weather, fewer crowds, perfect for sightseeing).", rainySeason: "November to March (coolest and wettest months, especially in the north).", cheapestSeason: "November to March (off-season prices, mild weather in the south).", majorFestivals: ["La Tomatina (August, Buñol)", "Running of the Bulls/San Fermín (July, Pamplona)", "Semana Santa (March-April)", "Las Fallas (March, Valencia)"] },
  egypt: { bestMonths: "October to April (cooler temperatures, comfortable for exploring pyramids and temples).", rainySeason: "Egypt rarely gets rain; occasional light showers on the Mediterranean coast in winter.", cheapestSeason: "May to September (extreme heat, but much lower prices and fewer crowds).", majorFestivals: ["Ramadan (varies yearly)", "Sham el-Nessim (April, spring festival)", "Abu Simbel Sun Festival (February 22 and October 22)", "Cairo International Film Festival (November)"] },
  turkey: { bestMonths: "April to June and September to November (warm, dry weather perfect for coastal and historical visits).", rainySeason: "December to March (wet and cold, especially in Istanbul and the Black Sea coast).", cheapestSeason: "November to March (winter off-season, except ski resorts).", majorFestivals: ["Ramadan (varies yearly)", "Cappadocia Hot Air Balloon Festival", "Whirling Dervish ceremonies (December, Konya)", "Istanbul Music Festival (June)"] },
  vietnam: { bestMonths: "February to April (dry, mild weather) and October to December (cooler, less humid in the north).", rainySeason: "May to September (heavy monsoon rains, especially in central and south regions).", cheapestSeason: "May to September (monsoon season means fewer tourists and lower prices).", majorFestivals: ["Tet/Lunar New Year (January-February)", "Mid-Autumn Festival (September)", "Hoi An Lantern Festival (monthly, full moon)", "Hung Kings' Temple Festival (April)"] },
  greece: { bestMonths: "April to June and September to October (warm, sunny, perfect for islands and ruins without summer crowds).", rainySeason: "November to March (cool and rainy on the mainland, milder on islands).", cheapestSeason: "November to March (off-season, many island businesses close).", majorFestivals: ["Greek Easter (March-April)", "Athens & Epidaurus Festival (June-August)", "Carnival/Apokries (February-March)", "Ohi Day (October 28)"] },
  canada: { bestMonths: "June to September (warm summer, long daylight hours, ideal for outdoor activities).", rainySeason: "March to May with regional variation; Pacific coast is wettest October to March.", cheapestSeason: "October to April (cold winter months, excellent deals outside ski season and holidays).", majorFestivals: ["Canada Day (July 1)", "Montreal Jazz Festival (June-July)", "Calgary Stampede (July)", "Toronto International Film Festival (September)"] },
  argentina: { bestMonths: "October to April (Argentine spring/summer, warm weather, Patagonia accessible).", rainySeason: "November to March (summer thunderstorms, heaviest in the northeast).", cheapestSeason: "June to August (Argentine winter, cold in Patagonia but cheaper across the country).", majorFestivals: ["Carnival (February, especially Gualeguaychú)", "Tango Festival (August, Buenos Aires)", "Vendimia Wine Harvest (March, Mendoza)", "Independence Day (July 9)"] },
  peru: { bestMonths: "May to September (dry season in the Andes and Machu Picchu, clear skies for trekking).", rainySeason: "November to March (wet season, heavy rains in the highlands and jungle).", cheapestSeason: "November to March (rainy season means fewer tourists, lower prices).", majorFestivals: ["Inti Raymi/Festival of the Sun (June 24, Cusco)", "Qoyllur Rit'i (May-June)", "Carnaval de Cajamarca (February)", "Señor de los Milagros (October, Lima)"] },
  portugal: { bestMonths: "March to May and September to October (mild, sunny weather, fewer tourists).", rainySeason: "November to March (wettest months, especially in the north).", cheapestSeason: "November to March (winter off-season, lower prices across the country).", majorFestivals: ["Santos Populares/Saint Anthony (June, Lisbon)", "Carnival (February)", "Festa de São João (June, Porto)", "Fado Festivals (year-round, Lisbon)"] },
  russia: { bestMonths: "May to September (warm weather, White Nights in St. Petersburg in June).", rainySeason: "July to August (warm but frequent rain showers in western Russia).", cheapestSeason: "November to March (harsh winter, but beautiful snowy landscapes and fewer tourists).", majorFestivals: ["Maslenitsa/Pancake Week (February-March)", "Victory Day (May 9)", "White Nights Festival (June, St. Petersburg)", "New Year celebrations (December 31-January 1)"] },
  indonesia: { bestMonths: "April to October (dry season, ideal for Bali, Java, and island hopping).", rainySeason: "November to March (wet monsoon season, heavy tropical downpours).", cheapestSeason: "February to March (end of rainy season, lowest tourist numbers).", majorFestivals: ["Nyepi/Day of Silence (March, Bali)", "Galungan (varies, Bali)", "Independence Day (August 17)", "Waisak/Vesak at Borobudur (May)"] },
  ...extraBestTimeToVisitData,
};

export const knownFunFactsData = {
  nepal: ["Nepal's flag is the only non-rectangular national flag in the world", "Nepal is home to 8 of the world's 14 highest peaks above 8,000 meters", "The birthplace of Siddhartha Gautama (Buddha) is in Lumbini, Nepal", "Nepal has never been colonized by a foreign power", "The country went from a monarchy to a republic in 2008"],
  japan: ["Japan has more than 6,800 islands", "Vending machines in Japan sell everything from hot meals to umbrellas", "There are more pets than children in Japan", "Japan has the world's oldest company, Kongo Gumi, founded in 578 AD", "Trains in Japan are so punctual that delays of even 1 minute are announced"],
  france: ["France is the most visited country in the world with over 90 million tourists annually", "The Louvre Museum has about 380,000 objects in its collection", "France has over 400 varieties of cheese", "French was the official language of England for about 300 years", "The first public bus system was launched in Nantes, France in 1826"],
  'united states': ["The US has no official language at the federal level", "Alaska is both the northernmost and westernmost state", "The US has more public libraries than McDonald's restaurants", "The Statue of Liberty was a gift from France in 1886", "Yellowstone was the world's first national park, established in 1872"],
  brazil: ["Brazil has the largest Japanese community outside Japan", "The Amazon Rainforest produces about 20% of the world's oxygen", "Brazil borders every South American country except Chile and Ecuador", "Football (soccer) is so popular that Brazil has won the FIFA World Cup 5 times", "The name 'Brazil' comes from the brazilwood tree"],
  mexico: ["Mexico City is sinking at a rate of about 10 inches per year", "Mexico introduced chocolate, corn, and chilies to the world", "The country has 35 UNESCO World Heritage Sites", "The Chihuahua dog breed is named after the Mexican state", "Mexico is home to the world's smallest volcano, Cuexcomate"],
  india: ["India has the world's largest postal system with over 150,000 post offices", "The game of chess was invented in India", "India is the world's largest democracy", "Kumbh Mela gathering is visible from space due to its massive crowd", "India produces the most films per year of any country"],
  thailand: ["Thailand is the only Southeast Asian country never colonized by a European power", "The country's name means 'Land of the Free'", "Bangkok's full ceremonial name has 168 characters, making it the longest city name in the world", "Thailand is home to the world's smallest mammal, the bumblebee bat", "Muay Thai has been the country's national sport for centuries"],
  'south korea': ["South Korea has the fastest average internet speed in the world", "Korean age system: everyone is considered 1 year old at birth", "South Korea has a dedicated 'Toilet Culture Park' museum", "K-pop and Korean dramas have created the global 'Korean Wave' (Hallyu)", "South Korea is one of the most digitally connected countries on Earth"],
  'korea (republic of)': ["South Korea has the fastest average internet speed in the world", "Korean age system: everyone is considered 1 year old at birth", "South Korea has a dedicated 'Toilet Culture Park' museum", "K-pop and Korean dramas have created the global 'Korean Wave' (Hallyu)", "South Korea is one of the most digitally connected countries on Earth"],
  china: ["China's Great Wall is over 13,000 miles long", "Paper, printing, gunpowder, and the compass were all invented in China", "China has more English speakers than the United States", "The country has a bridge that connects to each of 3 different countries", "Half of the world's pigs live in China"],
  germany: ["Germany has over 1,500 different types of beer", "The first printed book (Gutenberg Bible) was made in Germany", "Germany has over 20,000 castles", "Oktoberfest in Munich attracts over 6 million visitors annually", "The autobahn has sections with no speed limit"],
  italy: ["Italy has more UNESCO World Heritage Sites than any other country", "The University of Bologna, founded in 1088, is the oldest in the Western world", "Italy has a fountain that dispenses free wine 24/7 (in Caldari di Ortona)", "There are about 3,000 lakes in Italy", "The average Italian consumes 26 kg of pasta per year"],
  'united kingdom': ["The UK invented the World Wide Web (Tim Berners-Lee, 1989)", "Queen Elizabeth II was a trained mechanic during World War II", "London's Underground is the world's oldest metro system, opened in 1863", "Big Ben refers to the bell, not the clock tower", "The British drink about 165 million cups of tea per day"],
  australia: ["Australia is both a continent and a country", "The Great Barrier Reef is the largest living structure on Earth", "Australia has more sheep than people — about 3 sheep per person", "The country has over 10,000 beaches — enough to visit a new one every day for 27 years", "Kangaroos and emus cannot walk backward, which is why they're on the coat of arms"],
  spain: ["Spain has the second-highest number of UNESCO World Heritage Sites", "La Tomatina wastes approximately 150,000 tomatoes each year", "Spanish is spoken by over 580 million people worldwide", "Spain has one of the lowest birth rates in the world", "Running with the bulls in Pamplona has taken place since the 14th century"],
  egypt: ["The Great Pyramid of Giza was the tallest man-made structure for over 3,800 years", "Ancient Egyptians invented toothpaste, paper, and the 365-day calendar", "Cleopatra lived closer in time to the Moon landing than to the construction of the pyramids", "Egypt's Suez Canal shortens the trip between Europe and Asia by about 7,000 km", "Ancient Egyptians worshipped over 1,400 different gods and goddesses"],
  turkey: ["Turkey introduced tulips to the Netherlands, not the other way around", "Istanbul is the only city in the world spanning two continents (Europe and Asia)", "Turkey is home to two of the Seven Wonders of the Ancient World", "Turkish is the most widely spoken of the Turkic languages", "Santa Claus (Saint Nicholas) was born in Patara, southern Turkey"],
  vietnam: ["Vietnam is the world's second-largest coffee producer after Brazil", "Motorbikes outnumber cars by about 45 to 1", "The Vietnamese language has 6 different tones", "Halong Bay has nearly 2,000 limestone islands and islets", "Vietnam has been named the happiest country in Asia multiple times"],
  greece: ["Greece has more archaeological museums than any other country", "The Greek alphabet has been in use for over 2,700 years", "No point in Greece is more than 85 miles from the sea", "Greece has about 6,000 islands but only 227 are inhabited", "The Olympic Games originated in Greece in 776 BC"],
  canada: ["Canada has the longest coastline of any country in the world", "There are more lakes in Canada than in the rest of the world combined", "Canada produces 71% of the world's maple syrup", "The country has two official languages: English and French", "Canada's national parks system covers an area larger than many countries"],
  argentina: ["Argentina is named after argentum, the Latin word for silver", "Argentina has the widest avenue in the world — Avenida 9 de Julio has 16 lanes", "Tango was born in the neighborhoods of Buenos Aires", "Argentina spans 3,500 km from north to south", "Ushuaia is the southernmost city in the world"],
  peru: ["Machu Picchu was unknown to the outside world until 1911", "Peru has over 4,000 varieties of native potatoes", "The Nazca Lines can only be fully seen from the air", "Lake Titicaca is the highest navigable lake in the world at 3,812m", "Peru was the center of the Inca Empire, the largest empire in pre-Columbian America"],
  portugal: ["Portugal is one of the oldest countries in Europe, founded in 1143", "The Portuguese Empire was the first global maritime empire", "Port wine can only be called Port if it comes from the Douro Valley", "Lisbon is older than Rome by four centuries", "Portugal decriminalized all drugs in 2001 and saw addiction rates drop"],
  russia: ["Russia spans 11 time zones, more than any other country", "Lake Baikal contains about 20% of the world's unfrozen freshwater", "Russia has a larger surface area than Pluto", "The Trans-Siberian Railway is 9,289 km long, the world's longest", "Moscow's metro stations are considered underground palaces with chandeliers and mosaics"],
  indonesia: ["Indonesia has over 17,000 islands, making it the world's largest archipelago", "It is home to the Komodo dragon, the world's largest lizard", "Indonesia has about 700 different languages", "Borobudur is the world's largest Buddhist temple", "Bali has more than 20,000 temples — at least one in every home compound"],
  ...extraFunFactsData,
};
