// Additional country data for top 50 countries (25 new countries)
// Countries: Malaysia, Saudi Arabia, Morocco, Colombia, South Africa, Singapore, Philippines, New Zealand,
// Ireland, Netherlands, Switzerland, Austria, Sweden, Norway, Denmark, Czech Republic, Poland, Hungary,
// Croatia, UAE, Israel, Jordan, Sri Lanka, Cambodia, Cuba

export const extraAttractionsData = {
  malaysia: [
    { name: "Petronas Twin Towers", city: "Kuala Lumpur", famousFor: "Iconic 88-story twin skyscrapers and symbol of modern Malaysia", interestingFact: "They were the world's tallest buildings from 1998 to 2004", imageSearchQuery: "Petronas Twin Towers Kuala Lumpur night" },
    { name: "George Town Heritage", city: "Penang", famousFor: "UNESCO-listed historic quarter with stunning street art and colonial architecture", interestingFact: "George Town has one of the largest collections of pre-war buildings in Southeast Asia", imageSearchQuery: "George Town Penang street art heritage" },
    { name: "Batu Caves", city: "Kuala Lumpur", famousFor: "Limestone caves with Hindu temples and a 42.7m gold statue of Lord Murugan", interestingFact: "The caves are approximately 400 million years old", imageSearchQuery: "Batu Caves Kuala Lumpur colorful stairs" },
    { name: "Mount Kinabalu", city: "Sabah", famousFor: "Southeast Asia's highest peak at 4,095m in Malaysian Borneo", interestingFact: "It's one of the youngest non-volcanic mountains in the world", imageSearchQuery: "Mount Kinabalu Sabah Borneo sunrise" },
    { name: "Langkawi Sky Bridge", city: "Langkawi", famousFor: "Curved pedestrian bridge suspended 660m above sea level with panoramic views", interestingFact: "The 125m bridge is supported by a single pylon and cables", imageSearchQuery: "Langkawi Sky Bridge Malaysia panoramic" },
  ],
  'saudi arabia': [
    { name: "Masjid al-Haram", city: "Mecca", famousFor: "The holiest mosque in Islam, surrounding the Kaaba", interestingFact: "It can accommodate up to 4 million worshippers during Hajj season", imageSearchQuery: "Masjid al-Haram Mecca aerial Kaaba" },
    { name: "Al-Ula", city: "Medina Province", famousFor: "Ancient Nabataean tombs of Hegra (Madain Saleh), Saudi's first UNESCO site", interestingFact: "Hegra has 111 monumental tombs carved into sandstone outcrops", imageSearchQuery: "AlUla Hegra Madain Saleh tombs Saudi Arabia" },
    { name: "Edge of the World", city: "Riyadh", famousFor: "Dramatic cliff edge overlooking an endless desert plain", interestingFact: "The cliffs were once part of an ancient seabed millions of years ago", imageSearchQuery: "Edge of the World Riyadh Saudi Arabia cliff" },
    { name: "Masjid an-Nabawi", city: "Medina", famousFor: "The Prophet's Mosque, second holiest site in Islam", interestingFact: "Its iconic green dome was originally white and was painted green in 1837", imageSearchQuery: "Masjid Nabawi Medina green dome night" },
    { name: "Jeddah Corniche", city: "Jeddah", famousFor: "30km waterfront promenade with the King Fahd Fountain", interestingFact: "King Fahd Fountain shoots water 312m high, making it the tallest of its kind", imageSearchQuery: "King Fahd Fountain Jeddah Corniche waterfront" },
  ],
  morocco: [
    { name: "Jemaa el-Fnaa", city: "Marrakech", famousFor: "Vibrant medieval square with storytellers, musicians, and food stalls", interestingFact: "UNESCO declared it a 'Masterpiece of the Oral and Intangible Heritage of Humanity'", imageSearchQuery: "Jemaa el-Fnaa Marrakech square night" },
    { name: "Hassan II Mosque", city: "Casablanca", famousFor: "One of the largest mosques in the world with a 210m minaret", interestingFact: "Part of the mosque is built over the Atlantic Ocean with a glass floor", imageSearchQuery: "Hassan II Mosque Casablanca ocean sunset" },
    { name: "Chefchaouen", city: "Chefchaouen", famousFor: "The 'Blue Pearl' — a mountain town entirely painted in shades of blue", interestingFact: "The blue color tradition may have been introduced by Jewish refugees in the 1930s", imageSearchQuery: "Chefchaouen blue city Morocco streets" },
    { name: "Ait Benhaddou", city: "Ouarzazate", famousFor: "Fortified ksar (village) used as a filming location for many Hollywood movies", interestingFact: "It appeared in Game of Thrones, Gladiator, and Lawrence of Arabia", imageSearchQuery: "Ait Benhaddou Morocco fortified village" },
    { name: "Sahara Desert Erg Chebbi", city: "Merzouga", famousFor: "Towering sand dunes reaching up to 150 meters in height", interestingFact: "The orange dunes change color throughout the day from gold to deep red", imageSearchQuery: "Erg Chebbi Sahara Desert Morocco dunes camel" },
  ],
  colombia: [
    { name: "Cartagena Old Town", city: "Cartagena", famousFor: "Colorful colonial walled city and UNESCO World Heritage Site", interestingFact: "The city walls took nearly 200 years to build (1586-1796)", imageSearchQuery: "Cartagena Colombia old town colorful colonial streets" },
    { name: "Cocora Valley", city: "Salento", famousFor: "Home to the world's tallest palm trees (wax palms up to 60m)", interestingFact: "The wax palm is Colombia's national tree and can live for 200 years", imageSearchQuery: "Valle de Cocora Salento tall wax palms Colombia" },
    { name: "Caño Cristales", city: "Meta", famousFor: "The 'River of Five Colors' or 'Liquid Rainbow'", interestingFact: "The river turns red, yellow, green, blue, and black due to aquatic plants", imageSearchQuery: "Caño Cristales river five colors Colombia" },
    { name: "Ciudad Perdida", city: "Sierra Nevada", famousFor: "Lost City built around 800 AD, older than Machu Picchu", interestingFact: "It was rediscovered in 1972 by treasure hunters and requires a 4-day trek to reach", imageSearchQuery: "Ciudad Perdida Lost City Colombia terraces" },
    { name: "Salt Cathedral of Zipaquirá", city: "Zipaquirá", famousFor: "Underground cathedral built within salt mines 200m below ground", interestingFact: "It was carved out of a salt mine that has been active since the 5th century", imageSearchQuery: "Salt Cathedral Zipaquira Colombia underground" },
  ],
  'south africa': [
    { name: "Table Mountain", city: "Cape Town", famousFor: "Iconic flat-topped mountain and one of the New7Wonders of Nature", interestingFact: "It's one of the oldest mountains in the world, about 600 million years old", imageSearchQuery: "Table Mountain Cape Town aerial view" },
    { name: "Kruger National Park", city: "Mpumalanga", famousFor: "One of Africa's largest game reserves with the Big Five", interestingFact: "The park is roughly the same size as Israel or Wales", imageSearchQuery: "Kruger National Park safari Big Five wildlife" },
    { name: "Cape of Good Hope", city: "Cape Town", famousFor: "Dramatic headland at the southwestern tip of Africa", interestingFact: "Despite popular belief, it is not the southernmost point of Africa — that's Cape Agulhas", imageSearchQuery: "Cape of Good Hope Cape Town scenic coastline" },
    { name: "Blyde River Canyon", city: "Mpumalanga", famousFor: "Third largest canyon in the world and the largest green canyon", interestingFact: "The Three Rondavels rock formation resembles traditional African huts", imageSearchQuery: "Blyde River Canyon Mpumalanga Three Rondavels" },
    { name: "Robben Island", city: "Cape Town", famousFor: "Historic prison island where Nelson Mandela was held for 18 years", interestingFact: "Former prisoners now serve as guides, sharing firsthand accounts", imageSearchQuery: "Robben Island Cape Town Nelson Mandela prison" },
  ],
  singapore: [
    { name: "Marina Bay Sands", city: "Singapore", famousFor: "Iconic hotel with a rooftop infinity pool spanning three towers", interestingFact: "The SkyPark is longer than the Eiffel Tower laid on its side", imageSearchQuery: "Marina Bay Sands Singapore skyline night" },
    { name: "Gardens by the Bay", city: "Singapore", famousFor: "Futuristic garden with Supertree Grove and Cloud Forest dome", interestingFact: "The Supertrees generate solar power and collect rainwater", imageSearchQuery: "Gardens by the Bay Supertree Grove Singapore night lights" },
    { name: "Sentosa Island", city: "Singapore", famousFor: "Resort island with beaches, Universal Studios, and attractions", interestingFact: "Sentosa was once a British military fortress called Pulau Blakang Mati", imageSearchQuery: "Sentosa Island Singapore beach resort aerial" },
    { name: "Chinatown Heritage Centre", city: "Singapore", famousFor: "Recreated shophouses showing life of early Chinese immigrants", interestingFact: "Singapore's Chinatown is one of the most well-preserved in Southeast Asia", imageSearchQuery: "Singapore Chinatown heritage colorful shophouses" },
    { name: "Merlion Park", city: "Singapore", famousFor: "Iconic half-lion half-fish statue symbolizing Singapore", interestingFact: "The Merlion spouts water from its mouth and stands 8.6m tall", imageSearchQuery: "Merlion Park Singapore statue waterfront" },
  ],
  philippines: [
    { name: "Chocolate Hills", city: "Bohol", famousFor: "Over 1,200 perfectly cone-shaped hills that turn brown in dry season", interestingFact: "The hills are thought to be the remains of uplifted coral deposits and marine limestone", imageSearchQuery: "Chocolate Hills Bohol Philippines aerial" },
    { name: "El Nido", city: "Palawan", famousFor: "Stunning limestone cliffs, lagoons, and pristine beaches", interestingFact: "El Nido's Big and Small Lagoons are among the most photographed spots in Asia", imageSearchQuery: "El Nido Palawan lagoon limestone cliffs Philippines" },
    { name: "Mayon Volcano", city: "Albay", famousFor: "The world's most perfectly shaped volcanic cone", interestingFact: "It has erupted over 50 times in the last 400 years", imageSearchQuery: "Mayon Volcano Albay Philippines perfect cone" },
    { name: "Tubbataha Reef", city: "Palawan", famousFor: "UNESCO-listed marine park with one of the highest coral diversities on the planet", interestingFact: "It's home to half of all coral species found worldwide", imageSearchQuery: "Tubbataha Reef Natural Park Palawan coral diving" },
    { name: "Rice Terraces of the Philippine Cordilleras", city: "Ifugao", famousFor: "2,000-year-old hand-carved rice terraces called the 'Eighth Wonder of the World'", interestingFact: "If placed end to end, the terraces would circle half the globe", imageSearchQuery: "Banaue Rice Terraces Ifugao Philippines green" },
  ],
  'new zealand': [
    { name: "Milford Sound", city: "Fiordland", famousFor: "Dramatic fiord with towering peaks, waterfalls, and wildlife", interestingFact: "Rudyard Kipling called it the 'eighth wonder of the world'", imageSearchQuery: "Milford Sound Fiordland New Zealand Mitre Peak" },
    { name: "Hobbiton Movie Set", city: "Matamata", famousFor: "The real filming location of the Shire from Lord of the Rings", interestingFact: "The set has 44 hobbit holes and a fully functioning Green Dragon Inn", imageSearchQuery: "Hobbiton Movie Set Matamata New Zealand Shire" },
    { name: "Tongariro Alpine Crossing", city: "Tongariro", famousFor: "New Zealand's most popular day hike through volcanic terrain", interestingFact: "Mount Ngauruhoe served as Mount Doom in the Lord of the Rings films", imageSearchQuery: "Tongariro Alpine Crossing Emerald Lakes volcanic" },
    { name: "Waitomo Glowworm Caves", city: "Waitomo", famousFor: "Underground caves illuminated by thousands of bioluminescent glowworms", interestingFact: "The glowworms are unique to New Zealand and are actually fly larvae", imageSearchQuery: "Waitomo Glowworm Caves New Zealand blue lights" },
    { name: "Queenstown", city: "Queenstown", famousFor: "Adventure capital of the world — bungee, skiing, and jet boating", interestingFact: "Commercial bungee jumping was invented here at the Kawarau Bridge in 1988", imageSearchQuery: "Queenstown New Zealand Remarkables lake scenic" },
  ],
  ireland: [
    { name: "Cliffs of Moher", city: "County Clare", famousFor: "Dramatic sea cliffs rising 214m above the Atlantic Ocean", interestingFact: "On a clear day, you can see the Aran Islands and Galway Bay from the top", imageSearchQuery: "Cliffs of Moher County Clare Ireland Atlantic" },
    { name: "Ring of Kerry", city: "County Kerry", famousFor: "179km scenic drive through mountains, lakes, and coastline", interestingFact: "The route passes through some of Ireland's last remaining Gaelic-speaking communities", imageSearchQuery: "Ring of Kerry scenic drive Ireland coastline" },
    { name: "Trinity College Library", city: "Dublin", famousFor: "Home to the Book of Kells, a 9th-century illuminated manuscript", interestingFact: "The Long Room inspired the Jedi Archives in Star Wars", imageSearchQuery: "Trinity College Library Dublin Long Room" },
    { name: "Giant's Causeway", city: "County Antrim", famousFor: "40,000 interlocking basalt columns formed by ancient volcanic activity", interestingFact: "Legend says it was built by the giant Finn McCool to fight a Scottish giant", imageSearchQuery: "Giant's Causeway Northern Ireland basalt columns" },
    { name: "Newgrange", city: "County Meath", famousFor: "5,000-year-old passage tomb older than Stonehenge and the Egyptian pyramids", interestingFact: "At winter solstice, sunlight illuminates the inner chamber for exactly 17 minutes", imageSearchQuery: "Newgrange passage tomb County Meath Ireland" },
  ],
  netherlands: [
    { name: "Anne Frank House", city: "Amsterdam", famousFor: "The preserved hiding place where Anne Frank wrote her famous diary", interestingFact: "Over 1.2 million people visit annually, making it Amsterdam's most visited museum", imageSearchQuery: "Anne Frank House Amsterdam canal" },
    { name: "Keukenhof Gardens", city: "Lisse", famousFor: "World's largest flower garden with 7 million tulips planted annually", interestingFact: "The garden is only open for 8 weeks each spring", imageSearchQuery: "Keukenhof Gardens tulips Lisse Netherlands colorful" },
    { name: "Rijksmuseum", city: "Amsterdam", famousFor: "National museum housing Rembrandt's The Night Watch and Vermeer's Milkmaid", interestingFact: "The museum has over 1 million objects, with 8,000 on display", imageSearchQuery: "Rijksmuseum Amsterdam exterior museum" },
    { name: "Kinderdijk Windmills", city: "Kinderdijk", famousFor: "19 UNESCO-listed windmills built around 1740 for water management", interestingFact: "The windmills pumped water to keep the low-lying land dry", imageSearchQuery: "Kinderdijk windmills Netherlands UNESCO" },
    { name: "Vondelpark", city: "Amsterdam", famousFor: "Amsterdam's most famous park with over 10 million visitors per year", interestingFact: "The park has its own open-air theater that hosts free performances in summer", imageSearchQuery: "Vondelpark Amsterdam green park" },
  ],
  switzerland: [
    { name: "Matterhorn", city: "Zermatt", famousFor: "One of the most iconic and photographed mountains in the world", interestingFact: "The Toblerone chocolate bar logo features the Matterhorn", imageSearchQuery: "Matterhorn Zermatt Switzerland reflection lake" },
    { name: "Lake Geneva", city: "Geneva", famousFor: "Europe's largest Alpine lake shared between Switzerland and France", interestingFact: "The Jet d'Eau fountain shoots water 140m into the air", imageSearchQuery: "Lake Geneva Jet d'Eau fountain Swiss Alps" },
    { name: "Jungfraujoch", city: "Bernese Oberland", famousFor: "The 'Top of Europe' — highest railway station in Europe at 3,454m", interestingFact: "The railway tunnel through the Eiger took 16 years to build", imageSearchQuery: "Jungfraujoch Top of Europe Swiss Alps snow" },
    { name: "Chapel Bridge", city: "Lucerne", famousFor: "Europe's oldest covered wooden bridge, built in 1333", interestingFact: "The bridge has interior paintings depicting events from Swiss history", imageSearchQuery: "Chapel Bridge Lucerne Switzerland wooden bridge tower" },
    { name: "Rhine Falls", city: "Schaffhausen", famousFor: "Europe's largest waterfall by volume, 150m wide and 23m high", interestingFact: "You can take a boat to the rock in the middle of the falls", imageSearchQuery: "Rhine Falls Schaffhausen Switzerland waterfall" },
  ],
  austria: [
    { name: "Schönbrunn Palace", city: "Vienna", famousFor: "Former imperial summer residence with 1,441 rooms and stunning gardens", interestingFact: "Mozart performed his first concert here at age six", imageSearchQuery: "Schönbrunn Palace Vienna gardens baroque" },
    { name: "Hallstatt", city: "Hallstatt", famousFor: "Fairy-tale lakeside village often called the most beautiful in the world", interestingFact: "China built a full-scale replica of Hallstatt in Guangdong province", imageSearchQuery: "Hallstatt Austria village lake Alps reflection" },
    { name: "St. Stephen's Cathedral", city: "Vienna", famousFor: "Gothic cathedral with its distinctive mosaic roof of 230,000 tiles", interestingFact: "The south tower took 65 years to build and stands 136.4m tall", imageSearchQuery: "St Stephen's Cathedral Vienna Gothic roof tiles" },
    { name: "Salzburg Old Town", city: "Salzburg", famousFor: "Mozart's birthplace and filming location of The Sound of Music", interestingFact: "The Salzburg Festival has been running since 1920 and is one of the world's premier music events", imageSearchQuery: "Salzburg old town fortress Hohensalzburg Austria" },
    { name: "Grossglockner High Alpine Road", city: "Carinthia", famousFor: "Austria's highest mountain pass road with breathtaking Alpine vistas", interestingFact: "The road has 36 hairpin turns and reaches an altitude of 2,504m", imageSearchQuery: "Grossglockner High Alpine Road Austria scenic mountain" },
  ],
  sweden: [
    { name: "Vasa Museum", city: "Stockholm", famousFor: "Houses the Vasa, a 17th-century warship that sank on its maiden voyage", interestingFact: "The ship sank just 1,300m into its first voyage in 1628 and was salvaged 333 years later", imageSearchQuery: "Vasa Museum Stockholm warship Sweden" },
    { name: "Gamla Stan", city: "Stockholm", famousFor: "One of the best-preserved medieval old towns in Europe", interestingFact: "The narrowest street, Mårten Trotzigs gränd, is only 90cm wide", imageSearchQuery: "Gamla Stan Stockholm old town colorful buildings" },
    { name: "ICEHOTEL", city: "Jukkasjärvi", famousFor: "World's first hotel made entirely of ice and snow, rebuilt every winter", interestingFact: "It uses 2,500 tons of ice from the Torne River and melts each spring", imageSearchQuery: "ICEHOTEL Jukkasjärvi Sweden ice sculpture interior" },
    { name: "Abisko National Park", city: "Abisko", famousFor: "One of the best places on Earth to see the Northern Lights", interestingFact: "The park has a unique microclimate that keeps skies clear more often", imageSearchQuery: "Abisko Northern Lights Aurora Borealis Sweden" },
    { name: "Stockholm Archipelago", city: "Stockholm", famousFor: "Over 30,000 islands, skerries, and rocks stretching into the Baltic Sea", interestingFact: "It's the largest archipelago in Sweden and second largest in the Baltic Sea", imageSearchQuery: "Stockholm Archipelago islands Baltic Sea Sweden" },
  ],
  norway: [
    { name: "Geirangerfjord", city: "Geiranger", famousFor: "UNESCO-listed fjord with cascading waterfalls and deep blue waters", interestingFact: "The Seven Sisters waterfall drops 250m directly into the fjord", imageSearchQuery: "Geirangerfjord Norway fjord Seven Sisters waterfall" },
    { name: "Trolltunga", city: "Odda", famousFor: "Gravity-defying rock formation jutting 700m above Lake Ringedalsvatnet", interestingFact: "The tongue-shaped rock broke off during the last ice age 10,000 years ago", imageSearchQuery: "Trolltunga Norway rock formation cliff" },
    { name: "Northern Lights in Tromsø", city: "Tromsø", famousFor: "One of the best locations in the world for Aurora Borealis viewing", interestingFact: "Tromsø is the largest city in the Arctic Circle with over 75,000 people", imageSearchQuery: "Northern Lights Tromsø Norway Aurora Borealis" },
    { name: "Preikestolen (Pulpit Rock)", city: "Stavanger", famousFor: "Flat-topped cliff rising 604m above Lysefjorden", interestingFact: "The rock plateau measures about 25 by 25 meters and has no guardrails", imageSearchQuery: "Preikestolen Pulpit Rock Norway Lysefjorden" },
    { name: "Lofoten Islands", city: "Nordland", famousFor: "Dramatic peaks, sheltered bays, and traditional fishing villages", interestingFact: "Despite being above the Arctic Circle, Lofoten has the largest temperature anomaly in the world", imageSearchQuery: "Lofoten Islands Norway fishing village Reine" },
  ],
  denmark: [
    { name: "Tivoli Gardens", city: "Copenhagen", famousFor: "One of the world's oldest amusement parks, opened in 1843", interestingFact: "Walt Disney visited Tivoli and it inspired him to create Disneyland", imageSearchQuery: "Tivoli Gardens Copenhagen night lights amusement park" },
    { name: "Nyhavn", city: "Copenhagen", famousFor: "Colorful 17th-century waterfront with restaurants and historic ships", interestingFact: "Hans Christian Andersen lived in Nyhavn at three different addresses", imageSearchQuery: "Nyhavn Copenhagen colorful waterfront Denmark" },
    { name: "The Little Mermaid", city: "Copenhagen", famousFor: "Iconic bronze statue inspired by Hans Christian Andersen's fairy tale", interestingFact: "The statue is only 1.25m tall and has been vandalized numerous times since 1913", imageSearchQuery: "Little Mermaid statue Copenhagen harbor Denmark" },
    { name: "Kronborg Castle", city: "Helsingør", famousFor: "Renaissance castle and the setting of Shakespeare's Hamlet", interestingFact: "Shakespeare never actually visited the castle — he set Hamlet there based on stories", imageSearchQuery: "Kronborg Castle Helsingør Denmark Hamlet" },
    { name: "Legoland Billund", city: "Billund", famousFor: "The original Legoland theme park, built in the hometown of Lego", interestingFact: "The park used over 65 million Lego bricks in its Miniland displays", imageSearchQuery: "Legoland Billund Denmark Miniland Lego" },
  ],
  'czech republic': [
    { name: "Charles Bridge", city: "Prague", famousFor: "Medieval stone bridge lined with 30 baroque statues over the Vltava River", interestingFact: "Construction began in 1357 and the bridge took 45 years to complete", imageSearchQuery: "Charles Bridge Prague Vltava River statues sunrise" },
    { name: "Prague Castle", city: "Prague", famousFor: "The largest ancient castle complex in the world (70,000 sq meters)", interestingFact: "It has been the seat of Czech rulers for over 1,000 years", imageSearchQuery: "Prague Castle complex aerial view Czech Republic" },
    { name: "Old Town Square", city: "Prague", famousFor: "Medieval square with the famous Astronomical Clock dating to 1410", interestingFact: "The Astronomical Clock is the oldest still-operating astronomical clock in the world", imageSearchQuery: "Prague Old Town Square Astronomical Clock" },
    { name: "Český Krumlov", city: "Český Krumlov", famousFor: "Fairy-tale medieval town with a massive castle overlooking the Vltava River", interestingFact: "The castle has a 300-year-old Baroque theater still in working condition", imageSearchQuery: "Český Krumlov castle town river Czech Republic" },
    { name: "Kutná Hora Bone Church", city: "Kutná Hora", famousFor: "Sedlec Ossuary decorated with bones of over 40,000 people", interestingFact: "The bone chandelier contains at least one of every bone in the human body", imageSearchQuery: "Sedlec Ossuary Kutná Hora bone church interior" },
  ],
  czechia: [
    { name: "Charles Bridge", city: "Prague", famousFor: "Medieval stone bridge lined with 30 baroque statues over the Vltava River", interestingFact: "Construction began in 1357 and the bridge took 45 years to complete", imageSearchQuery: "Charles Bridge Prague Vltava River statues sunrise" },
    { name: "Prague Castle", city: "Prague", famousFor: "The largest ancient castle complex in the world (70,000 sq meters)", interestingFact: "It has been the seat of Czech rulers for over 1,000 years", imageSearchQuery: "Prague Castle complex aerial view Czech Republic" },
    { name: "Old Town Square", city: "Prague", famousFor: "Medieval square with the famous Astronomical Clock dating to 1410", interestingFact: "The Astronomical Clock is the oldest still-operating astronomical clock in the world", imageSearchQuery: "Prague Old Town Square Astronomical Clock" },
    { name: "Český Krumlov", city: "Český Krumlov", famousFor: "Fairy-tale medieval town with a massive castle overlooking the Vltava River", interestingFact: "The castle has a 300-year-old Baroque theater still in working condition", imageSearchQuery: "Český Krumlov castle town river Czech Republic" },
    { name: "Kutná Hora Bone Church", city: "Kutná Hora", famousFor: "Sedlec Ossuary decorated with bones of over 40,000 people", interestingFact: "The bone chandelier contains at least one of every bone in the human body", imageSearchQuery: "Sedlec Ossuary Kutná Hora bone church interior" },
  ],
  poland: [
    { name: "Wawel Castle", city: "Kraków", famousFor: "Historic royal castle and cathedral complex on Wawel Hill", interestingFact: "Legend says a dragon once lived in a cave beneath the castle", imageSearchQuery: "Wawel Castle Kraków Poland aerial view" },
    { name: "Auschwitz-Birkenau", city: "Oświęcim", famousFor: "Former Nazi concentration camp, now a UNESCO memorial and museum", interestingFact: "Over 2 million people visit annually to pay respects and learn about the Holocaust", imageSearchQuery: "Auschwitz Birkenau memorial entrance gate" },
    { name: "Wieliczka Salt Mine", city: "Wieliczka", famousFor: "Underground salt mine with chapels, sculptures, and an underground lake", interestingFact: "The mine has been in operation since the 13th century and extends 327m deep", imageSearchQuery: "Wieliczka Salt Mine Chapel St Kinga underground" },
    { name: "Old Town Market Square", city: "Warsaw", famousFor: "Meticulously rebuilt medieval square after World War II destruction", interestingFact: "85% of Warsaw was destroyed in WWII and the Old Town was rebuilt from paintings and photos", imageSearchQuery: "Warsaw Old Town Market Square colorful buildings" },
    { name: "Białowieża Forest", city: "Podlasie", famousFor: "Europe's last primeval forest, home to the European bison", interestingFact: "Some oak trees in the forest are over 500 years old", imageSearchQuery: "Białowieża Forest European bison Poland primeval" },
  ],
  hungary: [
    { name: "Hungarian Parliament Building", city: "Budapest", famousFor: "Neo-Gothic masterpiece on the Danube, third largest parliament building in the world", interestingFact: "It has 691 rooms, 29 staircases, and 40 kg of gold used in decoration", imageSearchQuery: "Hungarian Parliament Building Budapest Danube night" },
    { name: "Széchenyi Thermal Bath", city: "Budapest", famousFor: "Europe's largest medicinal thermal bath complex built in 1913", interestingFact: "Budapest has more thermal springs than any other capital city in the world", imageSearchQuery: "Széchenyi Thermal Bath Budapest outdoor pool" },
    { name: "Fisherman's Bastion", city: "Budapest", famousFor: "Neo-Romanesque terrace with panoramic views of the Danube and Parliament", interestingFact: "Its seven towers represent the seven Magyar tribes that founded Hungary", imageSearchQuery: "Fisherman's Bastion Budapest panoramic view Danube" },
    { name: "Buda Castle", city: "Budapest", famousFor: "Historic castle complex that has been the seat of Hungarian kings since 1265", interestingFact: "The castle has been destroyed and rebuilt at least six times throughout history", imageSearchQuery: "Buda Castle Budapest hilltop Danube aerial" },
    { name: "Lake Balaton", city: "Veszprém", famousFor: "Central Europe's largest freshwater lake, called the 'Hungarian Sea'", interestingFact: "The lake is 77km long but only 12m deep at its deepest point", imageSearchQuery: "Lake Balaton Hungary sunset sailboats" },
  ],
  croatia: [
    { name: "Dubrovnik Old Town", city: "Dubrovnik", famousFor: "The 'Pearl of the Adriatic' with medieval walls featured in Game of Thrones", interestingFact: "It was one of the first European cities to have a public pharmacy (1317) and quarantine system (1377)", imageSearchQuery: "Dubrovnik Old Town walls aerial Adriatic Croatia" },
    { name: "Plitvice Lakes National Park", city: "Lika-Senj", famousFor: "16 cascading turquoise lakes connected by waterfalls", interestingFact: "New travertine barriers form constantly, so the landscape is always changing", imageSearchQuery: "Plitvice Lakes National Park waterfalls turquoise Croatia" },
    { name: "Diocletian's Palace", city: "Split", famousFor: "Ancient Roman palace built for Emperor Diocletian around 305 AD", interestingFact: "About 3,000 people still live within the palace walls today", imageSearchQuery: "Diocletian's Palace Split Croatia Roman ruins" },
    { name: "Hvar Island", city: "Hvar", famousFor: "Sunniest island in the Adriatic with lavender fields and nightlife", interestingFact: "Hvar gets 2,724 hours of sunshine per year, more than any Croatian island", imageSearchQuery: "Hvar Island Croatia harbor fortress aerial" },
    { name: "Krka National Park", city: "Šibenik", famousFor: "Seven travertine waterfalls including the stunning Skradinski Buk", interestingFact: "The second city in the world to have an alternating current power supply was Šibenik, powered by Krka", imageSearchQuery: "Krka National Park Skradinski Buk waterfall Croatia" },
  ],
  'united arab emirates': [
    { name: "Burj Khalifa", city: "Dubai", famousFor: "The world's tallest building at 828m with 163 floors", interestingFact: "It takes a window-cleaning team 3 months to clean all the exterior glass", imageSearchQuery: "Burj Khalifa Dubai skyline night lights" },
    { name: "Sheikh Zayed Grand Mosque", city: "Abu Dhabi", famousFor: "One of the world's largest mosques with 82 domes and 1,000 columns", interestingFact: "It has the world's largest hand-knotted carpet, made by 1,200 artisans", imageSearchQuery: "Sheikh Zayed Grand Mosque Abu Dhabi white marble" },
    { name: "Palm Jumeirah", city: "Dubai", famousFor: "Artificial archipelago shaped like a palm tree visible from space", interestingFact: "It added 520km of beaches to the Dubai shoreline", imageSearchQuery: "Palm Jumeirah Dubai aerial view artificial island" },
    { name: "Dubai Frame", city: "Dubai", famousFor: "150m-tall picture frame offering views of old and new Dubai", interestingFact: "The glass floor at the top is transparent, giving a vertiginous view down", imageSearchQuery: "Dubai Frame golden landmark skyline" },
    { name: "Louvre Abu Dhabi", city: "Abu Dhabi", famousFor: "First Louvre museum outside France, with a stunning domed roof", interestingFact: "The dome weighs 7,500 tons — heavier than the Eiffel Tower", imageSearchQuery: "Louvre Abu Dhabi dome architecture rain of light" },
  ],
  israel: [
    { name: "Western Wall", city: "Jerusalem", famousFor: "Holiest site in Judaism, part of the ancient Temple Mount retaining wall", interestingFact: "Millions of written prayers are placed into the wall's crevices each year", imageSearchQuery: "Western Wall Jerusalem Israel prayer" },
    { name: "Dead Sea", city: "Ein Bokek", famousFor: "Earth's lowest point on land at 430m below sea level", interestingFact: "The salt content is so high (34%) that no one can sink — you float naturally", imageSearchQuery: "Dead Sea Israel floating salt crystals" },
    { name: "Masada Fortress", city: "Southern District", famousFor: "Ancient hilltop fortress with dramatic views over the Dead Sea", interestingFact: "Jewish rebels made their last stand here against the Romans in 73 AD", imageSearchQuery: "Masada fortress aerial Dead Sea Israel" },
    { name: "Old City of Jerusalem", city: "Jerusalem", famousFor: "Sacred to three religions with the Church of the Holy Sepulchre, Western Wall, and Dome of the Rock", interestingFact: "The Old City covers only 0.9 sq km but contains sites sacred to billions of people", imageSearchQuery: "Old City Jerusalem Dome of the Rock panoramic" },
    { name: "Bahá'í Gardens", city: "Haifa", famousFor: "Stunning terraced gardens cascading down Mount Carmel", interestingFact: "The 19 terraces represent the first 18 disciples of the Báb plus the Báb himself", imageSearchQuery: "Bahá'í Gardens Haifa Israel terraces Mount Carmel" },
  ],
  jordan: [
    { name: "Petra", city: "Wadi Musa", famousFor: "The 'Rose City' carved into pink sandstone cliffs by the Nabataeans", interestingFact: "Only 15% of Petra has been excavated — 85% remains underground", imageSearchQuery: "Petra Treasury Al-Khazneh Jordan rose sandstone" },
    { name: "Wadi Rum", city: "Aqaba", famousFor: "Mars-like desert landscape used to film The Martian and Lawrence of Arabia", interestingFact: "It's called the 'Valley of the Moon' due to its otherworldly terrain", imageSearchQuery: "Wadi Rum desert Jordan red sand rock formations" },
    { name: "Dead Sea (Jordan)", city: "Sweimeh", famousFor: "Float effortlessly in the world's saltiest body of water", interestingFact: "Dead Sea mud contains minerals used in beauty products worldwide", imageSearchQuery: "Dead Sea Jordan floating mud salt" },
    { name: "Jerash Ruins", city: "Jerash", famousFor: "One of the best-preserved Roman cities outside Italy", interestingFact: "The Oval Plaza and colonnaded streets are remarkably intact after 2,000 years", imageSearchQuery: "Jerash ruins Roman columns forum Jordan" },
    { name: "Aqaba Coral Reef", city: "Aqaba", famousFor: "Red Sea coral reefs with world-class diving and snorkeling", interestingFact: "The reefs are home to over 500 species of fish and 157 species of coral", imageSearchQuery: "Aqaba coral reef Red Sea Jordan diving" },
  ],
  'sri lanka': [
    { name: "Sigiriya Rock Fortress", city: "Matale", famousFor: "5th-century rock fortress rising 200m above the surrounding plain", interestingFact: "King Kashyapa built a palace on top and decorated the walls with frescoes of celestial maidens", imageSearchQuery: "Sigiriya Rock Fortress Sri Lanka aerial ancient" },
    { name: "Temple of the Tooth", city: "Kandy", famousFor: "Sacred Buddhist temple housing a relic of the tooth of Buddha", interestingFact: "The tooth relic has been fought over by kings for centuries", imageSearchQuery: "Temple of the Tooth Kandy Sri Lanka sacred" },
    { name: "Galle Fort", city: "Galle", famousFor: "UNESCO-listed 16th-century Portuguese fort with Dutch colonial charm", interestingFact: "It survived the 2004 tsunami largely intact due to its massive walls", imageSearchQuery: "Galle Fort Sri Lanka colonial lighthouse coast" },
    { name: "Ella Nine Arch Bridge", city: "Ella", famousFor: "Iconic colonial-era railway bridge set among lush green hills and tea plantations", interestingFact: "The bridge was built without steel, using only bricks, cement, and stone", imageSearchQuery: "Nine Arch Bridge Ella Sri Lanka train green" },
    { name: "Yala National Park", city: "Hambantota", famousFor: "Highest density of leopards in the world", interestingFact: "The park is also home to sloth bears, elephants, and over 200 bird species", imageSearchQuery: "Yala National Park Sri Lanka leopard safari" },
  ],
  cambodia: [
    { name: "Angkor Wat", city: "Siem Reap", famousFor: "The world's largest religious monument, a masterpiece of Khmer architecture", interestingFact: "It appears on Cambodia's national flag — the only building to feature on a country's flag", imageSearchQuery: "Angkor Wat Siem Reap Cambodia sunrise reflection" },
    { name: "Bayon Temple", city: "Siem Reap", famousFor: "Mysterious temple with over 200 serene stone faces", interestingFact: "The faces are thought to represent King Jayavarman VII or the bodhisattva Avalokiteshvara", imageSearchQuery: "Bayon Temple faces Angkor Thom Cambodia stone" },
    { name: "Ta Prohm Temple", city: "Siem Reap", famousFor: "Temple engulfed by giant tree roots, featured in Tomb Raider", interestingFact: "It was deliberately left unrestored to show nature's power over human structures", imageSearchQuery: "Ta Prohm Temple tree roots Tomb Raider Cambodia" },
    { name: "Royal Palace", city: "Phnom Penh", famousFor: "Opulent palace complex with the Silver Pagoda containing 5,000 silver tiles", interestingFact: "The palace has been the residence of Cambodian kings since 1866", imageSearchQuery: "Royal Palace Phnom Penh Cambodia Silver Pagoda" },
    { name: "Tonle Sap Lake", city: "Siem Reap", famousFor: "Southeast Asia's largest freshwater lake with floating villages", interestingFact: "The lake expands from 2,500 sq km to 16,000 sq km during monsoon season", imageSearchQuery: "Tonle Sap floating village Cambodia lake" },
  ],
  cuba: [
    { name: "Old Havana", city: "Havana", famousFor: "UNESCO-listed colonial quarter with colorful buildings and classic cars", interestingFact: "There are over 60,000 vintage American cars still running in Cuba", imageSearchQuery: "Old Havana Cuba colorful buildings vintage cars" },
    { name: "Viñales Valley", city: "Pinar del Río", famousFor: "Dramatic limestone mogotes and tobacco plantations", interestingFact: "Some of the world's finest cigar tobacco is grown in this valley", imageSearchQuery: "Viñales Valley Cuba mogotes tobacco fields" },
    { name: "Trinidad", city: "Trinidad", famousFor: "Perfectly preserved colonial town frozen in the 18th century", interestingFact: "The cobblestone streets and pastel buildings have barely changed since the sugar trade era", imageSearchQuery: "Trinidad Cuba colonial colorful cobblestone streets" },
    { name: "El Malecón", city: "Havana", famousFor: "8km seaside promenade that's the social heart of Havana", interestingFact: "Locals call it 'the world's longest sofa' because people sit on the wall for hours", imageSearchQuery: "El Malecón Havana Cuba waterfront sunset waves" },
    { name: "Varadero Beach", city: "Matanzas", famousFor: "20km of pristine white sand beach on the Hicacos Peninsula", interestingFact: "It was once a private resort for the wealthy, including Al Capone", imageSearchQuery: "Varadero Beach Cuba white sand turquoise water" },
  ],
};

export const extraPhrasesData = {
  malaysia: [
    { english: "Hello", local: "Hai / Apa khabar", pronunciation: "hi / ah-pah kah-bar" },
    { english: "Thank you", local: "Terima kasih", pronunciation: "teh-ree-mah kah-see" },
    { english: "Please", local: "Sila / Tolong", pronunciation: "see-lah / toh-long" },
    { english: "Excuse me", local: "Maafkan saya", pronunciation: "mah-ahf-kahn sah-yah" },
    { english: "Goodbye", local: "Selamat tinggal", pronunciation: "seh-lah-maht ting-gahl" },
    { english: "How much?", local: "Berapa harga?", pronunciation: "beh-rah-pah har-gah" },
    { english: "Yes", local: "Ya", pronunciation: "yah" },
    { english: "No", local: "Tidak", pronunciation: "tee-dahk" },
    { english: "Help", local: "Tolong", pronunciation: "toh-long" },
    { english: "Where is...?", local: "Di mana...?", pronunciation: "dee mah-nah" },
  ],
  'saudi arabia': [
    { english: "Hello", local: "السلام عليكم (Assalamu Alaikum)", pronunciation: "as-sah-lah-moo ah-lay-koom" },
    { english: "Thank you", local: "شكراً (Shukran)", pronunciation: "shook-rahn" },
    { english: "Please", local: "من فضلك (Min fadlak)", pronunciation: "min fahd-lahk" },
    { english: "Excuse me", local: "عفواً (Afwan)", pronunciation: "ahf-wahn" },
    { english: "Goodbye", local: "مع السلامة (Ma'a salama)", pronunciation: "mah-ah sah-lah-mah" },
    { english: "How much?", local: "بكم؟ (Bikam?)", pronunciation: "bee-kahm" },
    { english: "Yes", local: "نعم (Na'am)", pronunciation: "nah-ahm" },
    { english: "No", local: "لا (La)", pronunciation: "lah" },
    { english: "Help", local: "مساعدة (Musa'ada)", pronunciation: "moo-sah-ah-dah" },
    { english: "Where is...?", local: "أين...؟ (Ayna...?)", pronunciation: "ay-nah" },
  ],
  morocco: [
    { english: "Hello", local: "السلام عليكم (Assalamu Alaikum)", pronunciation: "as-sah-lah-moo ah-lay-koom" },
    { english: "Thank you", local: "شكراً (Shukran)", pronunciation: "shook-rahn" },
    { english: "Please", local: "من فضلك (Min fadlak)", pronunciation: "min fahd-lahk" },
    { english: "Excuse me", local: "سمح لي (Smeh li)", pronunciation: "smeh lee" },
    { english: "Goodbye", local: "بسلامة (Bslama)", pronunciation: "biss-lah-mah" },
    { english: "How much?", local: "بشحال؟ (Bshhal?)", pronunciation: "bish-hahl" },
    { english: "Yes", local: "إيه (Iyeh)", pronunciation: "ee-yeh" },
    { english: "No", local: "لا (La)", pronunciation: "lah" },
    { english: "Help", local: "عاونني (Aawni)", pronunciation: "ah-ow-nee" },
    { english: "Where is...?", local: "فين...؟ (Fin...?)", pronunciation: "feen" },
  ],
  colombia: [
    { english: "Hello", local: "Hola / ¡Buenos días!", pronunciation: "oh-lah / bweh-nohs dee-ahs" },
    { english: "Thank you", local: "Gracias", pronunciation: "grah-see-ahs" },
    { english: "Please", local: "Por favor", pronunciation: "pohr fah-vohr" },
    { english: "Excuse me", local: "Disculpe", pronunciation: "dees-kool-peh" },
    { english: "Goodbye", local: "Adiós / Chao", pronunciation: "ah-dee-ohs / chow" },
    { english: "How much?", local: "¿Cuánto cuesta?", pronunciation: "kwahn-toh kwes-tah" },
    { english: "Yes", local: "Sí", pronunciation: "see" },
    { english: "No", local: "No", pronunciation: "noh" },
    { english: "Help", local: "Ayuda", pronunciation: "ah-yoo-dah" },
    { english: "Where is...?", local: "¿Dónde está...?", pronunciation: "dohn-deh es-tah" },
  ],
  'south africa': [
    { english: "Hello", local: "Sawubona / Hallo", pronunciation: "sah-woo-boh-nah / hah-loh" },
    { english: "Thank you", local: "Ngiyabonga / Dankie", pronunciation: "ngee-yah-bohn-gah / dahn-kee" },
    { english: "Please", local: "Ngicela / Asseblief", pronunciation: "ngee-seh-lah / ah-seh-bleef" },
    { english: "Excuse me", local: "Uxolo / Verskoon my", pronunciation: "oo-kso-loh / fehr-skoon may" },
    { english: "Goodbye", local: "Sala kahle / Totsiens", pronunciation: "sah-lah kah-leh / toht-seens" },
    { english: "How much?", local: "Malini? / Hoeveel?", pronunciation: "mah-lee-nee / hoo-feel" },
    { english: "Yes", local: "Yebo / Ja", pronunciation: "yeh-boh / yah" },
    { english: "No", local: "Cha / Nee", pronunciation: "chah / nee" },
    { english: "Help", local: "Usizo / Help", pronunciation: "oo-see-zoh / help" },
    { english: "Where is...?", local: "Kuphi...? / Waar is...?", pronunciation: "koo-pee / vahr is" },
  ],
  singapore: [
    { english: "Hello", local: "你好 (Nǐ hǎo) / Hello lah", pronunciation: "nee how / heh-loh lah" },
    { english: "Thank you", local: "谢谢 (Xièxiè) / Thank you", pronunciation: "syeh-syeh" },
    { english: "Please", local: "请 (Qǐng)", pronunciation: "ching" },
    { english: "Excuse me", local: "不好意思 (Bù hǎo yìsi)", pronunciation: "boo how ee-suh" },
    { english: "Goodbye", local: "再见 (Zàijiàn) / Bye bye", pronunciation: "zai-jee-en" },
    { english: "How much?", local: "多少钱 (Duōshǎo qián)?", pronunciation: "dwoh-shaow chee-en" },
    { english: "Yes", local: "是 (Shì) / Can", pronunciation: "shih / kan" },
    { english: "No", local: "不是 (Bù shì) / Cannot", pronunciation: "boo shih / kan-not" },
    { english: "Help", local: "帮忙 (Bāngmáng)", pronunciation: "bahng-mahng" },
    { english: "Where is...?", local: "...在哪里？(...Zài nǎlǐ?)", pronunciation: "zai nah-lee" },
  ],
  philippines: [
    { english: "Hello", local: "Kumusta", pronunciation: "koo-moos-tah" },
    { english: "Thank you", local: "Salamat", pronunciation: "sah-lah-maht" },
    { english: "Please", local: "Pakiusap", pronunciation: "pah-kee-oo-sahp" },
    { english: "Excuse me", local: "Paumanhin", pronunciation: "pow-mahn-hin" },
    { english: "Goodbye", local: "Paalam", pronunciation: "pah-ah-lahm" },
    { english: "How much?", local: "Magkano?", pronunciation: "mahg-kah-noh" },
    { english: "Yes", local: "Oo", pronunciation: "oh-oh" },
    { english: "No", local: "Hindi", pronunciation: "hin-dee" },
    { english: "Help", local: "Tulong", pronunciation: "too-long" },
    { english: "Where is...?", local: "Nasaan ang...?", pronunciation: "nah-sah-ahn ahng" },
  ],
  'new zealand': [
    { english: "Hello", local: "Kia ora", pronunciation: "kee-ah oh-rah" },
    { english: "Thank you", local: "Ngā mihi / Cheers", pronunciation: "ngah mee-hee / cheers" },
    { english: "Please", local: "Koa / Please", pronunciation: "koh-ah" },
    { english: "Excuse me", local: "Aroha mai", pronunciation: "ah-roh-hah my" },
    { english: "Goodbye", local: "Ka kite anō", pronunciation: "kah kee-teh ah-noh" },
    { english: "How much?", local: "E hia?", pronunciation: "eh hee-ah" },
    { english: "Yes", local: "Āe", pronunciation: "ay" },
    { english: "No", local: "Kāo", pronunciation: "koh" },
    { english: "Help", local: "Āwhina", pronunciation: "ah-fee-nah" },
    { english: "Where is...?", local: "Kei hea...?", pronunciation: "kay heh-ah" },
  ],
  ireland: [
    { english: "Hello", local: "Dia dhuit (Irish) / Hello", pronunciation: "dee-ah gwit" },
    { english: "Thank you", local: "Go raibh maith agat", pronunciation: "guh rev mah ah-gut" },
    { english: "Please", local: "Le do thoil", pronunciation: "leh duh hull" },
    { english: "Excuse me", local: "Gabh mo leithscéal", pronunciation: "gov muh leh-shkayl" },
    { english: "Goodbye", local: "Slán", pronunciation: "slawn" },
    { english: "How much?", local: "Cé mhéad?", pronunciation: "kay vayd" },
    { english: "Yes", local: "Sea / Is ea", pronunciation: "shah / iss ah" },
    { english: "No", local: "Ní hea", pronunciation: "nee hah" },
    { english: "Help", local: "Cabhair", pronunciation: "kow-er" },
    { english: "Where is...?", local: "Cá bhfuil...?", pronunciation: "kaw will" },
  ],
  netherlands: [
    { english: "Hello", local: "Hallo / Hoi", pronunciation: "hah-loh / hoy" },
    { english: "Thank you", local: "Dank je wel", pronunciation: "dahnk yeh vel" },
    { english: "Please", local: "Alstublieft", pronunciation: "ahl-stoo-bleeft" },
    { english: "Excuse me", local: "Pardon", pronunciation: "par-dawn" },
    { english: "Goodbye", local: "Tot ziens / Doei", pronunciation: "tot zeens / doo-ee" },
    { english: "How much?", local: "Hoeveel kost het?", pronunciation: "hoo-feel kost het" },
    { english: "Yes", local: "Ja", pronunciation: "yah" },
    { english: "No", local: "Nee", pronunciation: "nay" },
    { english: "Help", local: "Help", pronunciation: "help" },
    { english: "Where is...?", local: "Waar is...?", pronunciation: "vahr is" },
  ],
  switzerland: [
    { english: "Hello", local: "Grüezi (Swiss German)", pronunciation: "grew-eh-tsee" },
    { english: "Thank you", local: "Merci vielmal / Danke", pronunciation: "mehr-see feel-mahl / dahn-keh" },
    { english: "Please", local: "Bitte", pronunciation: "bit-teh" },
    { english: "Excuse me", local: "Entschuldigung", pronunciation: "ent-shool-dee-goong" },
    { english: "Goodbye", local: "Uf Wiederluege / Tschüss", pronunciation: "oof vee-der-loo-eh-geh / tshews" },
    { english: "How much?", local: "Wieviel kostet das?", pronunciation: "vee-feel kos-tet dahs" },
    { english: "Yes", local: "Ja", pronunciation: "yah" },
    { english: "No", local: "Nein", pronunciation: "nine" },
    { english: "Help", local: "Hilfe", pronunciation: "hill-feh" },
    { english: "Where is...?", local: "Wo ist...?", pronunciation: "voh ist" },
  ],
  austria: [
    { english: "Hello", local: "Grüß Gott / Servus", pronunciation: "grews goht / sehr-voos" },
    { english: "Thank you", local: "Danke", pronunciation: "dahn-keh" },
    { english: "Please", local: "Bitte", pronunciation: "bit-teh" },
    { english: "Excuse me", local: "Entschuldigung", pronunciation: "ent-shool-dee-goong" },
    { english: "Goodbye", local: "Auf Wiedersehen / Servus", pronunciation: "owf vee-der-zay-en / sehr-voos" },
    { english: "How much?", local: "Wieviel kostet das?", pronunciation: "vee-feel kos-tet dahs" },
    { english: "Yes", local: "Ja", pronunciation: "yah" },
    { english: "No", local: "Nein", pronunciation: "nine" },
    { english: "Help", local: "Hilfe", pronunciation: "hill-feh" },
    { english: "Where is...?", local: "Wo ist...?", pronunciation: "voh ist" },
  ],
  sweden: [
    { english: "Hello", local: "Hej", pronunciation: "hey" },
    { english: "Thank you", local: "Tack", pronunciation: "tahk" },
    { english: "Please", local: "Snälla / Var så god", pronunciation: "sneh-lah / vahr so good" },
    { english: "Excuse me", local: "Ursäkta mig", pronunciation: "oor-sek-tah may" },
    { english: "Goodbye", local: "Hej då", pronunciation: "hey doh" },
    { english: "How much?", local: "Hur mycket kostar det?", pronunciation: "hoor mew-keh kos-tar deh" },
    { english: "Yes", local: "Ja", pronunciation: "yah" },
    { english: "No", local: "Nej", pronunciation: "nay" },
    { english: "Help", local: "Hjälp", pronunciation: "yelp" },
    { english: "Where is...?", local: "Var är...?", pronunciation: "vahr air" },
  ],
  norway: [
    { english: "Hello", local: "Hei", pronunciation: "hay" },
    { english: "Thank you", local: "Takk", pronunciation: "tahk" },
    { english: "Please", local: "Vær så snill", pronunciation: "vehr so snill" },
    { english: "Excuse me", local: "Unnskyld meg", pronunciation: "oon-shild may" },
    { english: "Goodbye", local: "Ha det bra", pronunciation: "hah deh brah" },
    { english: "How much?", local: "Hvor mye koster det?", pronunciation: "voor mew-eh kos-ter deh" },
    { english: "Yes", local: "Ja", pronunciation: "yah" },
    { english: "No", local: "Nei", pronunciation: "nay" },
    { english: "Help", local: "Hjelp", pronunciation: "yelp" },
    { english: "Where is...?", local: "Hvor er...?", pronunciation: "voor air" },
  ],
  denmark: [
    { english: "Hello", local: "Hej", pronunciation: "hi" },
    { english: "Thank you", local: "Tak", pronunciation: "tahk" },
    { english: "Please", local: "Vær så venlig", pronunciation: "vehr so ven-lee" },
    { english: "Excuse me", local: "Undskyld mig", pronunciation: "oon-skyld my" },
    { english: "Goodbye", local: "Farvel / Hej hej", pronunciation: "fahr-vel / hi hi" },
    { english: "How much?", local: "Hvor meget koster det?", pronunciation: "voor my-et kos-ter deh" },
    { english: "Yes", local: "Ja", pronunciation: "yah" },
    { english: "No", local: "Nej", pronunciation: "nay" },
    { english: "Help", local: "Hjælp", pronunciation: "yelp" },
    { english: "Where is...?", local: "Hvor er...?", pronunciation: "voor air" },
  ],
  'czech republic': [
    { english: "Hello", local: "Dobrý den / Ahoj", pronunciation: "dob-ree den / ah-hoy" },
    { english: "Thank you", local: "Děkuji", pronunciation: "dye-koo-yee" },
    { english: "Please", local: "Prosím", pronunciation: "proh-seem" },
    { english: "Excuse me", local: "Promiňte", pronunciation: "proh-min-teh" },
    { english: "Goodbye", local: "Na shledanou / Čau", pronunciation: "nah skhleh-dah-noh / chow" },
    { english: "How much?", local: "Kolik to stojí?", pronunciation: "koh-lik toh stoh-yee" },
    { english: "Yes", local: "Ano", pronunciation: "ah-noh" },
    { english: "No", local: "Ne", pronunciation: "neh" },
    { english: "Help", local: "Pomoc", pronunciation: "poh-mohts" },
    { english: "Where is...?", local: "Kde je...?", pronunciation: "gdeh yeh" },
  ],
  czechia: [
    { english: "Hello", local: "Dobrý den / Ahoj", pronunciation: "dob-ree den / ah-hoy" },
    { english: "Thank you", local: "Děkuji", pronunciation: "dye-koo-yee" },
    { english: "Please", local: "Prosím", pronunciation: "proh-seem" },
    { english: "Excuse me", local: "Promiňte", pronunciation: "proh-min-teh" },
    { english: "Goodbye", local: "Na shledanou / Čau", pronunciation: "nah skhleh-dah-noh / chow" },
    { english: "How much?", local: "Kolik to stojí?", pronunciation: "koh-lik toh stoh-yee" },
    { english: "Yes", local: "Ano", pronunciation: "ah-noh" },
    { english: "No", local: "Ne", pronunciation: "neh" },
    { english: "Help", local: "Pomoc", pronunciation: "poh-mohts" },
    { english: "Where is...?", local: "Kde je...?", pronunciation: "gdeh yeh" },
  ],
  poland: [
    { english: "Hello", local: "Cześć / Dzień dobry", pronunciation: "cheshch / jen dob-rih" },
    { english: "Thank you", local: "Dziękuję", pronunciation: "jen-koo-yeh" },
    { english: "Please", local: "Proszę", pronunciation: "proh-sheh" },
    { english: "Excuse me", local: "Przepraszam", pronunciation: "psheh-prah-shahm" },
    { english: "Goodbye", local: "Do widzenia", pronunciation: "doh vee-dzeh-nyah" },
    { english: "How much?", local: "Ile to kosztuje?", pronunciation: "ee-leh toh kosh-too-yeh" },
    { english: "Yes", local: "Tak", pronunciation: "tahk" },
    { english: "No", local: "Nie", pronunciation: "nyeh" },
    { english: "Help", local: "Pomoc", pronunciation: "poh-mohts" },
    { english: "Where is...?", local: "Gdzie jest...?", pronunciation: "gdjeh yest" },
  ],
  hungary: [
    { english: "Hello", local: "Szia / Jó napot", pronunciation: "see-yah / yoh nah-pot" },
    { english: "Thank you", local: "Köszönöm", pronunciation: "kuh-suh-nuhm" },
    { english: "Please", local: "Kérem", pronunciation: "keh-rem" },
    { english: "Excuse me", local: "Elnézést", pronunciation: "el-neh-zaysht" },
    { english: "Goodbye", local: "Viszontlátásra / Szia", pronunciation: "vee-sont-lah-tash-rah / see-yah" },
    { english: "How much?", local: "Mennyibe kerül?", pronunciation: "men-nyee-beh keh-rewl" },
    { english: "Yes", local: "Igen", pronunciation: "ee-gen" },
    { english: "No", local: "Nem", pronunciation: "nem" },
    { english: "Help", local: "Segítség", pronunciation: "sheh-geet-shayg" },
    { english: "Where is...?", local: "Hol van...?", pronunciation: "hol vahn" },
  ],
  croatia: [
    { english: "Hello", local: "Bok / Zdravo", pronunciation: "bohk / zdrah-voh" },
    { english: "Thank you", local: "Hvala", pronunciation: "hvah-lah" },
    { english: "Please", local: "Molim", pronunciation: "moh-leem" },
    { english: "Excuse me", local: "Oprostite", pronunciation: "oh-proh-stee-teh" },
    { english: "Goodbye", local: "Doviđenja", pronunciation: "doh-vee-jen-yah" },
    { english: "How much?", local: "Koliko košta?", pronunciation: "koh-lee-koh kosh-tah" },
    { english: "Yes", local: "Da", pronunciation: "dah" },
    { english: "No", local: "Ne", pronunciation: "neh" },
    { english: "Help", local: "Pomoć", pronunciation: "poh-mohch" },
    { english: "Where is...?", local: "Gdje je...?", pronunciation: "gd-yeh yeh" },
  ],
  'united arab emirates': [
    { english: "Hello", local: "السلام عليكم (Assalamu Alaikum)", pronunciation: "as-sah-lah-moo ah-lay-koom" },
    { english: "Thank you", local: "شكراً (Shukran)", pronunciation: "shook-rahn" },
    { english: "Please", local: "من فضلك (Min fadlak)", pronunciation: "min fahd-lahk" },
    { english: "Excuse me", local: "عفواً (Afwan)", pronunciation: "ahf-wahn" },
    { english: "Goodbye", local: "مع السلامة (Ma'a salama)", pronunciation: "mah-ah sah-lah-mah" },
    { english: "How much?", local: "بكم؟ (Bikam?)", pronunciation: "bee-kahm" },
    { english: "Yes", local: "نعم (Na'am)", pronunciation: "nah-ahm" },
    { english: "No", local: "لا (La)", pronunciation: "lah" },
    { english: "Help", local: "مساعدة (Musa'ada)", pronunciation: "moo-sah-ah-dah" },
    { english: "Where is...?", local: "أين...؟ (Ayna...?)", pronunciation: "ay-nah" },
  ],
  israel: [
    { english: "Hello", local: "שלום (Shalom)", pronunciation: "shah-lohm" },
    { english: "Thank you", local: "תודה (Toda)", pronunciation: "toh-dah" },
    { english: "Please", local: "בבקשה (Bevakasha)", pronunciation: "beh-vah-kah-shah" },
    { english: "Excuse me", local: "סליחה (Slicha)", pronunciation: "slee-khah" },
    { english: "Goodbye", local: "להתראות (Lehitraot)", pronunciation: "leh-hit-rah-oht" },
    { english: "How much?", local: "כמה זה? (Kama ze?)", pronunciation: "kah-mah zeh" },
    { english: "Yes", local: "כן (Ken)", pronunciation: "ken" },
    { english: "No", local: "לא (Lo)", pronunciation: "loh" },
    { english: "Help", local: "עזרה (Ezra)", pronunciation: "ez-rah" },
    { english: "Where is...?", local: "?...איפה (Eifo...?)", pronunciation: "ay-foh" },
  ],
  jordan: [
    { english: "Hello", local: "مرحبا (Marhaba)", pronunciation: "mar-hah-bah" },
    { english: "Thank you", local: "شكراً (Shukran)", pronunciation: "shook-rahn" },
    { english: "Please", local: "من فضلك (Min fadlak)", pronunciation: "min fahd-lahk" },
    { english: "Excuse me", local: "عفواً (Afwan)", pronunciation: "ahf-wahn" },
    { english: "Goodbye", local: "مع السلامة (Ma'a salama)", pronunciation: "mah-ah sah-lah-mah" },
    { english: "How much?", local: "قديش؟ (Gaddesh?)", pronunciation: "gahd-desh" },
    { english: "Yes", local: "أيوا (Aiwa)", pronunciation: "ay-wah" },
    { english: "No", local: "لا (La)", pronunciation: "lah" },
    { english: "Help", local: "مساعدة (Musa'ada)", pronunciation: "moo-sah-ah-dah" },
    { english: "Where is...?", local: "وين...؟ (Wein...?)", pronunciation: "wayn" },
  ],
  'sri lanka': [
    { english: "Hello", local: "ආයුබෝවන් (Ayubowan)", pronunciation: "ah-yoo-boh-wahn" },
    { english: "Thank you", local: "ස්තූතියි (Sthuthiyi)", pronunciation: "stoo-tee-yee" },
    { english: "Please", local: "කරුණාකර (Karunakara)", pronunciation: "kah-roo-nah-kah-rah" },
    { english: "Excuse me", local: "සමාවන්න (Samawanna)", pronunciation: "sah-mah-wahn-nah" },
    { english: "Goodbye", local: "ගිහින් එන්නම් (Gihin ennam)", pronunciation: "gee-hin en-nahm" },
    { english: "How much?", local: "කීයද? (Keeyada?)", pronunciation: "kee-yah-dah" },
    { english: "Yes", local: "ඔව් (Ow)", pronunciation: "oh-oo" },
    { english: "No", local: "නැහැ (Naehae)", pronunciation: "neh-heh" },
    { english: "Help", local: "උදව් (Udaw)", pronunciation: "oo-dau" },
    { english: "Where is...?", local: "...කොහේද? (...Koheda?)", pronunciation: "koh-heh-dah" },
  ],
  cambodia: [
    { english: "Hello", local: "សួស្តី (Suostei)", pronunciation: "soo-oss-day" },
    { english: "Thank you", local: "អរគុណ (Arkun)", pronunciation: "ar-koon" },
    { english: "Please", local: "សូម (Som)", pronunciation: "sohm" },
    { english: "Excuse me", local: "សូមទោស (Som toh)", pronunciation: "sohm toh" },
    { english: "Goodbye", local: "លាហើយ (Lea haey)", pronunciation: "lee-ah hai" },
    { english: "How much?", local: "ថ្លៃប៉ុន្មាន? (Tlai ponman?)", pronunciation: "tlai pohn-mahn" },
    { english: "Yes", local: "បាទ/ចាស (Bat/Jas)", pronunciation: "baht / jahs" },
    { english: "No", local: "ទេ (Te)", pronunciation: "tay" },
    { english: "Help", local: "ជួយ (Chuoy)", pronunciation: "choo-oy" },
    { english: "Where is...?", local: "...នៅឯណា? (...Nov ae na?)", pronunciation: "nov ay nah" },
  ],
  cuba: [
    { english: "Hello", local: "¡Hola! / ¿Qué bolá?", pronunciation: "oh-lah / keh boh-lah" },
    { english: "Thank you", local: "Gracias", pronunciation: "grah-see-ahs" },
    { english: "Please", local: "Por favor", pronunciation: "pohr fah-vohr" },
    { english: "Excuse me", local: "Disculpe / Permiso", pronunciation: "dees-kool-peh / pehr-mee-soh" },
    { english: "Goodbye", local: "Adiós / Hasta luego", pronunciation: "ah-dee-ohs / ahs-tah lweh-goh" },
    { english: "How much?", local: "¿Cuánto cuesta?", pronunciation: "kwahn-toh kwes-tah" },
    { english: "Yes", local: "Sí", pronunciation: "see" },
    { english: "No", local: "No", pronunciation: "noh" },
    { english: "Help", local: "Ayuda", pronunciation: "ah-yoo-dah" },
    { english: "Where is...?", local: "¿Dónde está...?", pronunciation: "dohn-deh es-tah" },
  ],
};

export const extraPricesData = {
  malaysia: { hotel: "$20-80 per night", meal: "$2-10", streetFood: "$1-3", coffee: "$1-3", transport: "$0.50-2", taxi: "$1-3 per km" },
  'saudi arabia': { hotel: "$60-200 per night", meal: "$8-25", streetFood: "$2-5", coffee: "$3-6", transport: "$1-3", taxi: "$1-2 per km" },
  morocco: { hotel: "$15-80 per night", meal: "$3-12", streetFood: "$1-3", coffee: "$1-2", transport: "$0.30-1", taxi: "$0.50-2 per km" },
  colombia: { hotel: "$15-70 per night", meal: "$3-10", streetFood: "$1-3", coffee: "$0.50-2", transport: "$0.50-1", taxi: "$1-2 per km" },
  'south africa': { hotel: "$25-120 per night", meal: "$5-15", streetFood: "$2-5", coffee: "$1.50-3", transport: "$1-3", taxi: "$1-2 per km" },
  singapore: { hotel: "$80-300 per night", meal: "$3-15", streetFood: "$2-5", coffee: "$3-6", transport: "$1-3", taxi: "$3-5 per km" },
  philippines: { hotel: "$10-60 per night", meal: "$2-8", streetFood: "$0.50-2", coffee: "$1-3", transport: "$0.25-1", taxi: "$0.50-2 per km" },
  'new zealand': { hotel: "$60-200 per night", meal: "$10-25", streetFood: "$5-10", coffee: "$3-5", transport: "$2-5", taxi: "$3-5 per km" },
  ireland: { hotel: "$80-250 per night", meal: "$12-30", streetFood: "$5-10", coffee: "$3-5", transport: "$2-5", taxi: "$2-4 per km" },
  netherlands: { hotel: "$80-250 per night", meal: "$12-25", streetFood: "$5-10", coffee: "$2.50-4", transport: "$2-5", taxi: "$2-4 per km" },
  switzerland: { hotel: "$120-400 per night", meal: "$20-50", streetFood: "$8-15", coffee: "$4-7", transport: "$3-8", taxi: "$5-8 per km" },
  austria: { hotel: "$70-200 per night", meal: "$10-25", streetFood: "$4-8", coffee: "$3-5", transport: "$2-4", taxi: "$2-4 per km" },
  sweden: { hotel: "$80-250 per night", meal: "$12-30", streetFood: "$5-10", coffee: "$3-6", transport: "$3-6", taxi: "$3-6 per km" },
  norway: { hotel: "$100-300 per night", meal: "$15-40", streetFood: "$8-15", coffee: "$4-7", transport: "$3-8", taxi: "$4-8 per km" },
  denmark: { hotel: "$80-250 per night", meal: "$15-35", streetFood: "$5-12", coffee: "$4-6", transport: "$3-6", taxi: "$3-6 per km" },
  'czech republic': { hotel: "$30-120 per night", meal: "$5-15", streetFood: "$2-5", coffee: "$2-4", transport: "$1-3", taxi: "$1-3 per km" },
  czechia: { hotel: "$30-120 per night", meal: "$5-15", streetFood: "$2-5", coffee: "$2-4", transport: "$1-3", taxi: "$1-3 per km" },
  poland: { hotel: "$25-100 per night", meal: "$5-15", streetFood: "$2-5", coffee: "$2-4", transport: "$1-2", taxi: "$1-3 per km" },
  hungary: { hotel: "$25-100 per night", meal: "$5-15", streetFood: "$2-5", coffee: "$1.50-3", transport: "$1-2", taxi: "$1-2 per km" },
  croatia: { hotel: "$40-150 per night", meal: "$8-20", streetFood: "$3-7", coffee: "$1.50-3", transport: "$1-3", taxi: "$1-3 per km" },
  'united arab emirates': { hotel: "$80-400 per night", meal: "$8-30", streetFood: "$3-8", coffee: "$4-7", transport: "$1-3", taxi: "$2-4 per km" },
  israel: { hotel: "$80-250 per night", meal: "$10-25", streetFood: "$5-10", coffee: "$3-5", transport: "$2-5", taxi: "$2-5 per km" },
  jordan: { hotel: "$30-150 per night", meal: "$5-15", streetFood: "$1-4", coffee: "$2-4", transport: "$0.50-2", taxi: "$1-3 per km" },
  'sri lanka': { hotel: "$15-80 per night", meal: "$2-8", streetFood: "$0.50-2", coffee: "$1-3", transport: "$0.25-1", taxi: "$0.50-1.50 per km" },
  cambodia: { hotel: "$10-60 per night", meal: "$2-8", streetFood: "$0.50-2", coffee: "$1-3", transport: "$0.25-1", taxi: "$0.50-2 per km" },
  cuba: { hotel: "$20-100 per night", meal: "$5-15", streetFood: "$1-3", coffee: "$0.50-2", transport: "$0.25-1", taxi: "$1-3 per km" },
};

export const extraBestTimeToVisitData = {
  malaysia: { bestMonths: "March to October (dry season on the west coast, warm tropical weather throughout).", rainySeason: "November to February (northeast monsoon brings heavy rain to the east coast).", cheapestSeason: "February to March (between peak seasons, good deals available).", majorFestivals: ["Hari Raya Aidilfitri (varies)", "Chinese New Year (January-February)", "Thaipusam (January-February)", "Deepavali (October-November)"] },
  'saudi arabia': { bestMonths: "November to February (cooler winter temperatures, comfortable for sightseeing at 15-25°C).", rainySeason: "Saudi Arabia is mostly arid; scattered rainfall November to April in western highlands.", cheapestSeason: "May to September (extreme heat deters visitors, hotel prices drop significantly).", majorFestivals: ["Ramadan (varies yearly)", "Eid al-Fitr (varies)", "Eid al-Adha (varies)", "Janadriyah Festival (February)"] },
  morocco: { bestMonths: "March to May and September to November (mild temperatures, perfect for exploring medinas and desert).", rainySeason: "November to March (occasional rain in the north, cooler Atlas Mountain temperatures).", cheapestSeason: "June to August (hot in interior cities, but great for coastal visits).", majorFestivals: ["Ramadan (varies yearly)", "Fes Festival of World Sacred Music (June)", "Marrakech International Film Festival (November-December)", "Rose Festival (May, Kelaat M'Gouna)"] },
  colombia: { bestMonths: "December to March and July to August (driest months, ideal for Cartagena, Bogotá, and coffee region).", rainySeason: "April to June and September to November (frequent afternoon showers across most regions).", cheapestSeason: "September to November (rainy season means fewer tourists and lower prices).", majorFestivals: ["Carnival de Barranquilla (February)", "Feria de las Flores (August, Medellín)", "Festival de la Leyenda Vallenata (April)", "Christmas Lights (December, nationwide)"] },
  'south africa': { bestMonths: "May to September (dry winter season, best for safari game viewing as animals gather at water sources).", rainySeason: "October to March (summer thunderstorms, especially in Johannesburg and eastern regions).", cheapestSeason: "May to August (winter low season, except for whale watching in Hermanus).", majorFestivals: ["Cape Town Jazz Festival (March)", "National Arts Festival (June-July, Grahamstown)", "Heritage Day (September 24)", "Diwali (October-November, Durban)"] },
  singapore: { bestMonths: "February to April (driest months with least rainfall and clearest skies).", rainySeason: "November to January (northeast monsoon, frequent heavy afternoon showers).", cheapestSeason: "August to October (post-summer, fewer tourists, reasonable hotel rates).", majorFestivals: ["Chinese New Year (January-February)", "Singapore Food Festival (July)", "National Day (August 9)", "Deepavali (October-November)"] },
  philippines: { bestMonths: "November to April (dry season, perfect for beaches, island hopping, and diving).", rainySeason: "June to October (southwest monsoon, heavy rains and occasional typhoons).", cheapestSeason: "June to October (monsoon season keeps crowds away, major discounts on resorts).", majorFestivals: ["Sinulog Festival (January, Cebu)", "Ati-Atihan Festival (January, Kalibo)", "Pahiyas Festival (May, Lucban)", "MassKara Festival (October, Bacolod)"] },
  'new zealand': { bestMonths: "December to February (warm summer, best for beaches, hiking, and outdoor activities).", rainySeason: "Year-round moderate rainfall; west coast is wettest, especially May to September.", cheapestSeason: "May to September (winter, except ski areas; lower prices and fewer international tourists).", majorFestivals: ["Waitangi Day (February 6)", "World of WearableArt Awards (September-October)", "Rhythm & Alps Festival (December-January)", "Matariki (Māori New Year, June-July)"] },
  ireland: { bestMonths: "May to September (longest daylight hours, warmest weather at 15-20°C, festivals season).", rainySeason: "October to March (frequent rain, short days, but cozy pub atmosphere).", cheapestSeason: "November to March (off-season, lower accommodation prices except Christmas).", majorFestivals: ["St. Patrick's Day (March 17)", "Galway International Arts Festival (July)", "Dublin Fringe Festival (September)", "Samhain/Halloween (October 31, its origin)"] },
  netherlands: { bestMonths: "April to May (tulip season, mild weather, King's Day festivities) and June to August (warm summer).", rainySeason: "October to March (cold, wet, and windy with short daylight hours).", cheapestSeason: "November to March (off-season, excluding Christmas and New Year holidays).", majorFestivals: ["King's Day (April 27)", "Keukenhof Tulip Season (March-May)", "Amsterdam Dance Event (October)", "Sinterklaas (December 5)"] },
  switzerland: { bestMonths: "June to September (warm Alpine summer, ideal for hiking and lake activities) and December to March (ski season).", rainySeason: "May and November (transitional months with more rainfall and overcast skies).", cheapestSeason: "April to May and October to November (shoulder seasons, lower hotel prices).", majorFestivals: ["Fasnacht/Carnival (February-March, Basel)", "Montreux Jazz Festival (July)", "Swiss National Day (August 1)", "Zürcher Sechseläuten (April, Zürich)"] },
  austria: { bestMonths: "June to September (warm, long days, ideal for Alpine hiking and city sightseeing) and December to March (ski season).", rainySeason: "May to August (summer thunderstorms, especially in the Alps).", cheapestSeason: "April to May and October to November (shoulder seasons, reasonable prices).", majorFestivals: ["Vienna Opera Ball (February)", "Salzburg Festival (July-August)", "Vienna Christmas Markets (November-December)", "Austrian National Day (October 26)"] },
  sweden: { bestMonths: "June to August (warm, endless daylight with midnight sun in the north).", rainySeason: "September to November (autumn rains, temperatures dropping).", cheapestSeason: "January to April (cold, dark winter, but great for Northern Lights and skiing).", majorFestivals: ["Midsummer/Midsommar (June)", "Nobel Prize Ceremony (December 10)", "Lucia Celebrations (December 13)", "Gothenburg Film Festival (January-February)"] },
  norway: { bestMonths: "June to August (midnight sun, warmest weather, best for fjord cruises and hiking).", rainySeason: "September to November (autumn rains, especially on the western coast).", cheapestSeason: "January to April (cold and dark, but cheapest flights and hotels; great for Northern Lights).", majorFestivals: ["Constitution Day (May 17)", "Bergen International Festival (May-June)", "Midnight Sun Marathon (June, Tromsø)", "Northern Lights season (October-March)"] },
  denmark: { bestMonths: "June to August (warmest weather, longest days, outdoor café culture at its best).", rainySeason: "October to March (cold, wet, windy, and dark with only 7 hours of daylight).", cheapestSeason: "November to March (winter off-season, except Christmas market period).", majorFestivals: ["Roskilde Festival (June-July)", "Copenhagen Jazz Festival (July)", "Tivoli Halloween (October)", "Christmas Markets (November-December)"] },
  'czech republic': { bestMonths: "April to June and September to October (mild temperatures, beautiful spring blooms or autumn foliage).", rainySeason: "July to August (warm but with frequent summer thunderstorms).", cheapestSeason: "November to March (cold winter, but magical Christmas markets in December).", majorFestivals: ["Prague Spring International Music Festival (May-June)", "Signal Light Festival (October, Prague)", "Easter Markets (March-April)", "Christmas Markets (December)"] },
  czechia: { bestMonths: "April to June and September to October (mild temperatures, beautiful spring blooms or autumn foliage).", rainySeason: "July to August (warm but with frequent summer thunderstorms).", cheapestSeason: "November to March (cold winter, but magical Christmas markets in December).", majorFestivals: ["Prague Spring International Music Festival (May-June)", "Signal Light Festival (October, Prague)", "Easter Markets (March-April)", "Christmas Markets (December)"] },
  poland: { bestMonths: "May to September (warm weather, outdoor festivals, long daylight hours).", rainySeason: "July to August (summer thunderstorms, though generally brief).", cheapestSeason: "November to March (cold winter, budget-friendly except Christmas period).", majorFestivals: ["Wianki Midsummer Festival (June, Kraków)", "Pierogi Festival (August, Kraków)", "All Saints' Day (November 1)", "Christmas Markets (December)"] },
  hungary: { bestMonths: "April to June and September to October (pleasant temperatures, fewer crowds, festival season).", rainySeason: "May to June (spring rains) and November (autumn rains).", cheapestSeason: "November to March (cold winter, but thermal baths are perfect, and prices are lowest).", majorFestivals: ["Budapest Spring Festival (April)", "Sziget Festival (August)", "Budapest Wine Festival (September)", "Christmas Markets (November-December)"] },
  croatia: { bestMonths: "May to June and September to October (warm, sunny, fewer crowds than peak summer).", rainySeason: "November to March (cooler and wet, especially inland; coast is milder).", cheapestSeason: "November to March (off-season, many coastal businesses close).", majorFestivals: ["Dubrovnik Summer Festival (July-August)", "Ultra Europe Festival (July, Split)", "Rijeka Carnival (February)", "Spancirfest (August, Varazdin)"] },
  'united arab emirates': { bestMonths: "November to March (pleasant 20-30°C temperatures, clear skies, outdoor activities comfortable).", rainySeason: "UAE rarely gets rain; occasional brief showers in January and February.", cheapestSeason: "May to September (extreme heat over 45°C, but indoor attractions and massive hotel discounts).", majorFestivals: ["Dubai Shopping Festival (January-February)", "Abu Dhabi Grand Prix (November)", "Ramadan (varies yearly)", "Dubai Food Festival (February-March)"] },
  israel: { bestMonths: "March to May and September to November (mild temperatures, comfortable for sightseeing).", rainySeason: "December to March (rainy season, especially in the north; snow possible in Jerusalem).", cheapestSeason: "January to February (winter, excluding Jewish holidays).", majorFestivals: ["Passover/Pesach (March-April)", "Hanukkah (November-December)", "Purim (February-March)", "Tel Aviv Pride (June)"] },
  jordan: { bestMonths: "March to May and September to November (mild temperatures, perfect for Petra and desert trekking).", rainySeason: "December to February (cool and occasional rain, especially in Amman and the north).", cheapestSeason: "June to August (extreme heat in Wadi Rum and Aqaba, but lower prices).", majorFestivals: ["Ramadan (varies yearly)", "Jerash Festival of Culture and Arts (July-August)", "Jordan Independence Day (May 25)", "Eid al-Adha (varies)"] },
  'sri lanka': { bestMonths: "December to March (dry season on west/south coast) and May to September (dry on east coast).", rainySeason: "May to August (southwest monsoon, wet west coast) and October to January (northeast monsoon, wet east coast).", cheapestSeason: "April to June and September to November (shoulder seasons between monsoons).", majorFestivals: ["Sinhala & Tamil New Year (April 13-14)", "Vesak Poya (May)", "Kandy Esala Perahera (July-August)", "Deepavali (October-November)"] },
  cambodia: { bestMonths: "November to February (cool dry season, most comfortable temperatures at 25-30°C).", rainySeason: "June to October (heavy monsoon rains, especially in afternoon; lush green landscapes).", cheapestSeason: "June to October (wet season means fewer tourists and lower prices).", majorFestivals: ["Khmer New Year/Choul Chnam Thmey (April 13-16)", "Water Festival/Bon Om Touk (November)", "Royal Ploughing Ceremony (May)", "Pchum Ben (September-October)"] },
  cuba: { bestMonths: "November to April (dry season, warm days at 25-30°C, perfect for beaches and exploring).", rainySeason: "May to October (hurricane season, heavy afternoon storms, high humidity).", cheapestSeason: "May to October (wet season, lower tourist numbers, hotel discounts up to 30%).", majorFestivals: ["Havana Jazz Festival (January)", "Carnival de Santiago (July)", "Havana Biennial (varies)", "Festival del Habano (February)"] },
};

export const extraFunFactsData = {
  malaysia: ["Malaysia is home to the world's largest flower, the Rafflesia, which can grow up to 1 meter across", "The Petronas Twin Towers were the tallest buildings in the world from 1998 to 2004", "Malaysia has one of the oldest tropical rainforests in the world, estimated at 130 million years old", "The country has three federal territories: Kuala Lumpur, Putrajaya, and Labuan", "Malaysian cuisine reflects its Malay, Chinese, and Indian multicultural heritage"],
  'saudi arabia': ["Saudi Arabia has no permanent rivers or lakes", "The Empty Quarter (Rub' al Khali) is the largest continuous sand desert in the world", "Saudi Arabia is the world's largest country without a river", "The country was founded in 1932 by King Abdulaziz Ibn Saud", "Camel beauty contests are a major cultural event, with millions in prize money"],
  morocco: ["Morocco was the first country to recognize the United States as an independent nation in 1777", "The University of al-Qarawiyyin in Fez, founded in 859 AD, is the world's oldest existing university", "Morocco is the world's largest exporter of phosphates", "Moroccan tea ceremony involves pouring mint tea from a great height to create a frothy top", "The country spans from the Mediterranean coast to the Sahara Desert"],
  colombia: ["Colombia is the only South American country with coastlines on both the Pacific Ocean and Caribbean Sea", "It produces about 80% of the world's emeralds", "Colombia has more species of birds than any other country — over 1,900", "The country is named after Christopher Columbus, though he never actually set foot there", "Colombian coffee is renowned worldwide and the Coffee Cultural Landscape is a UNESCO site"],
  'south africa': ["South Africa has three capital cities: Pretoria (executive), Cape Town (legislative), and Bloemfontein (judicial)", "It has 11 official languages, the most of any country in the world", "The world's first heart transplant was performed in Cape Town in 1967", "South Africa is home to the Cradle of Humankind, where some of the oldest human fossils were found", "Table Mountain is one of the oldest mountains in the world, about 600 million years old"],
  singapore: ["Singapore is both a city and a country — one of only three surviving city-states", "It has the world's first night zoo, the Night Safari", "Chewing gum has been banned in Singapore since 1992", "Singapore is one of the greenest cities in Asia, with nearly 50% green cover", "The country has no natural freshwater sources and imports water from Malaysia"],
  philippines: ["The Philippines is the world's leading producer of coconuts", "It has the shortest coastline per land area among island nations with 36,289 km of coast", "The Philippine eagle is one of the largest and most powerful eagles in the world", "Filipinos send more text messages per day than any other country", "The country was named after King Philip II of Spain in the 16th century"],
  'new zealand': ["New Zealand was the first country to give women the right to vote in 1893", "There are more sheep than people — roughly 6 sheep per person", "New Zealand is the youngest country to rise from the sea, formed about 23 million years ago", "The country has no native land mammals except bats", "Queenstown is considered the adventure capital of the world — bungee jumping was commercialized there"],
  ireland: ["Ireland has no snakes — legend credits St. Patrick with driving them out", "The harp, not the shamrock, is the official symbol of Ireland", "Halloween originated from the ancient Celtic festival of Samhain in Ireland", "Ireland is the only country in the world that has a musical instrument (the harp) as its national symbol", "The Guinness Book of World Records was created at the Guinness Brewery in Dublin"],
  netherlands: ["The Netherlands literally means 'low lands' — about a third of the country is below sea level", "There are more bicycles than people in the Netherlands", "The Dutch invented the stock exchange in Amsterdam in 1602", "Gin (jenever) was invented in the Netherlands, not England", "The country's famous orange color comes from the House of Orange-Nassau, not the flag"],
  switzerland: ["Switzerland has four official languages: German, French, Italian, and Romansh", "Swiss watches account for over 50% of the world's luxury watch market", "Switzerland has been neutral in armed conflicts since 1815", "The Swiss consume more chocolate per capita than any other nation — about 10 kg per person per year", "The country has over 7,000 lakes and 1,500 of them were formed by glaciers"],
  austria: ["The world's oldest zoo, Tiergarten Schönbrunn, is in Vienna (opened in 1752)", "Austria produced composers like Mozart, Schubert, Strauss, Haydn, and Mahler", "The Austrian flag is one of the oldest national flags, dating back to at least 1230", "Red Bull was co-founded by Austrian Dietrich Mateschitz in 1987", "The famous Sacher torte was invented in Vienna in 1832 by 16-year-old Franz Sacher"],
  sweden: ["Sweden has an official Twitter account (@Sweden) run by a different citizen each week", "IKEA, Spotify, Volvo, and H&M are all Swedish companies", "Sweden has a hotel made entirely of ice that is rebuilt from scratch every winter", "The Nobel Prize was established by Swedish inventor Alfred Nobel in 1895", "Sweden introduced the first ombudsman in 1809 — a Swedish word adopted globally"],
  norway: ["Norway introduced salmon sushi to Japan in the 1980s", "The country has the longest road tunnel in the world — the Laerdal Tunnel at 24.5 km", "Norway knighted a penguin (Sir Nils Olav) at Edinburgh Zoo", "Brunost (brown cheese) is so beloved that a truckload catching fire once blocked a tunnel for days", "Norway's coastline would stretch halfway around the world if straightened out"],
  denmark: ["Lego was invented in Denmark — the name comes from 'leg godt' meaning 'play well'", "Denmark has the oldest monarchy in Europe, dating back over 1,000 years", "The Danish flag (Dannebrog) is the oldest state flag still in use, dating to 1219", "Danes are consistently ranked among the happiest people in the world", "Copenhagen's Strøget is one of the longest pedestrian shopping streets in Europe at 1.1 km"],
  'czech republic': ["The Czech Republic has the highest beer consumption per capita in the world", "Prague Castle is the largest ancient castle in the world", "The word 'robot' comes from Czech — coined by Karel Čapek in 1920", "The Astronomical Clock in Prague has been operating since 1410", "Contact lenses were invented by Czech chemist Otto Wichterle in 1959"],
  czechia: ["The Czech Republic has the highest beer consumption per capita in the world", "Prague Castle is the largest ancient castle in the world", "The word 'robot' comes from Czech — coined by Karel Čapek in 1920", "The Astronomical Clock in Prague has been operating since 1410", "Contact lenses were invented by Czech chemist Otto Wichterle in 1959"],
  poland: ["Poland's Wieliczka Salt Mine has underground chapels, chandeliers, and even a sanatorium", "Marie Curie (Maria Skłodowska), the first woman to win a Nobel Prize, was born in Warsaw", "Poland's Białowieża Forest is Europe's last primeval forest", "The Polish alphabet has 32 letters, including 9 unique consonant combinations", "Polish astronomer Nicolaus Copernicus proposed that Earth revolves around the Sun"],
  hungary: ["Budapest has the largest thermal water cave system in the world", "The Rubik's Cube was invented by Hungarian professor Ernő Rubik in 1974", "Hungary has won the most Olympic gold medals per capita of any country", "Hungarian is one of the most difficult languages to learn — unrelated to any neighboring language", "The ballpoint pen was invented by Hungarian-Argentine László Bíró"],
  croatia: ["Croatia's Dalmatian coast inspired the name of the Dalmatian dog breed", "The necktie originated in Croatia — the word 'cravat' comes from 'Croat'", "Dubrovnik's Old Town walls are 1,940 meters long and up to 25 meters high", "Croatia has over 1,200 islands, but only 48 are permanently inhabited", "The White House in Washington D.C. was partly built with Croatian limestone from the island of Brač"],
  'united arab emirates': ["The UAE was founded in 1971, making it one of the youngest countries in the world", "Dubai's Palm Jumeirah is the largest artificial island visible from space", "The Burj Khalifa in Dubai is the tallest building in the world at 828 meters", "Abu Dhabi's Yas Marina Circuit hosts the Formula 1 Abu Dhabi Grand Prix", "The UAE has one of the most diverse populations — over 80% of residents are expatriates"],
  israel: ["Israel is the only country to have revived a dead language (Hebrew) as its national language", "The Dead Sea is the lowest point on Earth's surface at 430 meters below sea level", "Israel has more museums per capita than any other country", "Tel Aviv has over 4,000 Bauhaus-style buildings, the largest concentration in the world", "Israel was the first country to ban underweight fashion models by law"],
  jordan: ["Petra was voted one of the New7Wonders of the World in 2007", "Jordan's Dead Sea shore is the lowest dry point on Earth", "The Jordanian city of Jerash is one of the best-preserved Roman cities outside Italy", "The country is 80% desert", "Wadi Rum is nicknamed 'Mars on Earth' and NASA has used it for Mars simulations"],
  'sri lanka': ["Sri Lanka was the first country in the world to have a female prime minister (Sirimavo Bandaranaike in 1960)", "The country produces some of the world's finest Ceylon tea, the 3rd largest tea producer globally", "Sri Lanka has the oldest known tree planted by humans — the Sri Maha Bodhi, planted in 288 BC", "The island was known as Ceylon until it changed its name to Sri Lanka in 1972", "Sri Lanka has the highest biodiversity density in Asia"],
  cambodia: ["Angkor Wat is the largest religious monument in the world, covering 162.6 hectares", "Cambodia's flag is the only national flag that features a building (Angkor Wat)", "The Khmer Empire once controlled much of Southeast Asia", "Cambodia uses both the Cambodian riel and the US dollar as currency", "Tonle Sap Lake reverses its flow direction twice a year with the monsoon seasons"],
  cuba: ["Cuba has two currencies: the Cuban peso and the convertible peso", "There are over 60,000 vintage American cars from the 1940s-50s still running in Cuba", "Cuba has one of the highest literacy rates in the world at 99.8%", "Havana's Malecón seawall stretches 8 km along the coast", "Cuba is the largest island in the Caribbean"],
};
