// Extra map category data for additional countries.

export const extraMapCategoryData = {
  // New 25 countries
  malaysia: {
    bestFoodAreas: ["Jalan Alor, Kuala Lumpur", "Gurney Drive Hawkers, Penang", "Jonker Street, Malacca", "Bukit Bintang Food Court, KL", "Kota Kinabalu Filipino Market, Sabah"],
    nightlifeZones: ["Changkat Bukit Bintang, Kuala Lumpur", "TREC KL, Kuala Lumpur", "Upper Penang Road, Penang", "Bangsar, Kuala Lumpur", "Jalan Mesui, KL"],
    instagrammableSpots: ["Petronas Twin Towers KLCC, KL", "Batu Caves Rainbow Stairs, KL", "Chefchaouen of Malaysia Jalan Alor, KL", "The Top Rainbow Skywalk, Penang", "Langkawi Sky Bridge, Langkawi"],
    areasToAvoid: ["Chow Kit area at night, KL", "Brickfields at late night", "Remote areas of Sabah near Philippine border"],
    bestBeaches: ["Langkawi Beach, Kedah", "Perhentian Islands, Terengganu", "Redang Island, Terengganu", "Tioman Island, Pahang", "Tanjung Rhu Beach, Langkawi"],
  },
  'saudi arabia': {
    bestFoodAreas: ["Al Balad Historic District, Jeddah", "Tahlia Street, Riyadh", "Al Khobar Corniche, Eastern Province", "Bujairi Terrace, Diriyah", "Al Madinah food souqs, Medina"],
    nightlifeZones: ["Boulevard Riyadh City", "Jeddah Waterfront", "KAFD District, Riyadh", "Al Khobar Corniche", "The Zone, Riyadh"],
    instagrammableSpots: ["Edge of the World, Riyadh", "Al-Ula Elephant Rock, Medina Province", "KAFD Sphere, Riyadh", "Hegra Tombs, Al-Ula", "King Fahd Fountain, Jeddah"],
    areasToAvoid: ["Yemen border regions", "Remote desert areas without guides", "Near military installations"],
  },
  morocco: {
    bestFoodAreas: ["Jemaa el-Fnaa food stalls, Marrakech", "Rue des Consuls, Rabat", "Fez Medina food stalls, Fez", "Habous Quarter, Casablanca", "Essaouira Port fish grills, Essaouira"],
    nightlifeZones: ["Guéliz, Marrakech", "Ain Diab Corniche, Casablanca", "Kasbah Street, Tangier", "Hivernage, Marrakech", "Marina, Agadir"],
    instagrammableSpots: ["Chefchaouen Blue Streets, Chefchaouen", "Jardin Majorelle, Marrakech", "Hassan II Mosque, Casablanca", "Aït Benhaddou, Ouarzazate", "Erg Chebbi Dunes, Merzouga"],
    areasToAvoid: ["Rif Mountains drug-producing regions", "Isolated areas of Western Sahara", "Unlicensed taxis at night"],
    bestBeaches: ["Legzira Beach, Sidi Ifni", "Essaouira Beach, Essaouira", "Agadir Beach, Agadir", "Dakhla Beach, Dakhla", "Taghazout Beach, Agadir"],
  },
  colombia: {
    bestFoodAreas: ["La Candelaria, Bogotá", "Getsemaní, Cartagena", "El Poblado, Medellín", "San Antonio, Cali", "Granada, Cali"],
    nightlifeZones: ["Zona T, Bogotá", "Parque Lleras, Medellín", "Getsemaní, Cartagena", "San Antonio district, Cali", "Zona Rosa, Bogotá"],
    instagrammableSpots: ["Cartagena Old Town Walls, Cartagena", "Guatapé Rock (La Piedra del Peñol), Antioquia", "Cocora Valley Wax Palms, Salento", "Comuna 13 Street Art, Medellín", "Caño Cristales, Meta"],
    areasToAvoid: ["Catatumbo region at night", "Remote border areas with Venezuela", "Certain zones in Cali at night"],
  },
  'south africa': {
    bestFoodAreas: ["V&A Waterfront, Cape Town", "Maboneng Precinct, Johannesburg", "Florida Road, Durban", "Franschhoek Main Road, Western Cape", "Stellenbosch Wine Route, Western Cape"],
    nightlifeZones: ["Long Street, Cape Town", "Maboneng, Johannesburg", "Florida Road, Durban", "Camps Bay, Cape Town", "Melville, Johannesburg"],
    instagrammableSpots: ["Table Mountain Aerial Cableway, Cape Town", "Bo-Kaap Colorful Houses, Cape Town", "Blyde River Canyon, Mpumalanga", "Chapman's Peak Drive, Cape Town", "Cradle of Humankind, Gauteng"],
    areasToAvoid: ["Hillbrow and Berea, Johannesburg at night", "CBD areas after dark in most cities", "Isolated township areas without a guide"],
    bestBeaches: ["Camps Bay Beach, Cape Town", "Muizenberg Beach, Cape Town", "Umhlanga Rocks Beach, Durban", "Clifton Beaches, Cape Town", "Boulders Beach Penguin Colony, Simon's Town"],
  },
  singapore: {
    bestFoodAreas: ["Maxwell Food Centre, Chinatown", "Lau Pa Sat, CBD", "Chomp Chomp Hawker Centre, Serangoon", "Tiong Bahru Market, Tiong Bahru", "Old Airport Road Food Centre, Geylang"],
    nightlifeZones: ["Clarke Quay, Singapore River", "Ann Siang Hill, Chinatown", "Holland Village, Holland", "Boat Quay, Singapore River", "Orchard Road towers, CBD"],
    instagrammableSpots: ["Gardens by the Bay Supertree Grove, Marina Bay", "Marina Bay Sands Infinity Pool, Marina Bay", "Haji Lane, Kampong Glam", "Jewel Changi Airport Waterfall, Changi", "Buddha Tooth Relic Temple, Chinatown"],
    areasToAvoid: ["Geylang Red Light District at late night", "Little India on weekday nights (very crowded)"],
  },
  philippines: {
    bestFoodAreas: ["Poblacion, Makati Manila", "Mercato Centrale Night Market, Taguig", "Carbon Market, Cebu City", "Iloilo La Paz Market, Iloilo", "Binondo Chinatown, Manila"],
    nightlifeZones: ["Poblacion, Makati Manila", "Bonifacio Global City, Taguig", "Station I, Boracay", "Mango Avenue, Cebu City", "Malate, Manila"],
    instagrammableSpots: ["El Nido Big Lagoon, Palawan", "Chocolate Hills, Bohol", "Banaue Rice Terraces, Ifugao", "Mayon Volcano, Albay", "Kawasan Falls, Cebu"],
    areasToAvoid: ["Tondo, Manila at night", "Parts of Mindanao (Marawi, Sulu)", "Quiapo at night, Manila"],
    bestBeaches: ["White Beach, Boracay", "El Nido Beach, Palawan", "Nacpan Beach, El Nido", "Alona Beach, Panglao", "Siargao Cloud 9, Surigao"],
  },
  'new zealand': {
    bestFoodAreas: ["Ponsonby Road, Auckland", "Cuba Street, Wellington", "Eat Street, Rotorua", "Lyttelton Main Street, Christchurch", "Queenstown Mall, Queenstown"],
    nightlifeZones: ["Viaduct Harbour, Auckland", "Courtenay Place, Wellington", "Queenstown CBD, Queenstown", "Victoria Street, Christchurch", "Ponsonby Road, Auckland"],
    instagrammableSpots: ["Milford Sound, Fiordland", "Hobbiton Movie Set, Matamata", "Lake Tekapo Church, Canterbury", "Roy's Peak, Wanaka", "Tongariro Crossing Emerald Lakes, Tongariro"],
    areasToAvoid: ["South Auckland late at night", "Isolated hiking trails alone (inform someone)"],
    bestBeaches: ["Cathedral Cove, Coromandel", "Hot Water Beach, Coromandel", "Piha Beach, Auckland", "Abel Tasman Coast, Nelson", "Mount Maunganui Beach, Bay of Plenty"],
  },
  ireland: {
    bestFoodAreas: ["Temple Bar area, Dublin", "English Market, Cork", "Latin Quarter, Galway", "Dingle Town, Kerry", "Kinsale, Cork"],
    nightlifeZones: ["Temple Bar, Dublin", "Quay Street, Galway", "Oliver Plunkett Street, Cork", "The Docks, Limerick", "Cathedral Quarter, Belfast"],
    instagrammableSpots: ["Cliffs of Moher, County Clare", "Ring of Kerry viewpoints, County Kerry", "Dark Hedges, County Antrim", "Skellig Michael, County Kerry", "Kylemore Abbey, Connemara"],
    areasToAvoid: ["O'Connell Street very late at night, Dublin", "Some inner city areas late at night"],
  },
  netherlands: {
    bestFoodAreas: ["Albert Cuyp Market, Amsterdam", "Markthal, Rotterdam", "De Pijp neighborhood, Amsterdam", "Grote Markt, Haarlem", "Noordermarkt, Amsterdam"],
    nightlifeZones: ["Leidseplein, Amsterdam", "Rembrandtplein, Amsterdam", "Witte de Withstraat, Rotterdam", "Stratumseind, Eindhoven", "Grote Markt, Groningen"],
    instagrammableSpots: ["Keukenhof Tulip Gardens, Lisse", "Kinderdijk Windmills, Kinderdijk", "Rijksmuseum, Amsterdam", "Cube Houses, Rotterdam", "Amsterdam Canal Houses, Amsterdam"],
    areasToAvoid: ["Red Light District late at night alone", "Bijlmer area, Amsterdam Southeast at night"],
  },
  switzerland: {
    bestFoodAreas: ["Bahnhofstrasse, Zürich", "Old Town, Bern", "Carouge, Geneva", "Altstadt, Lucerne", "Markthalle, Basel"],
    nightlifeZones: ["Langstrasse, Zürich", "Bains des Pâquis area, Geneva", "Steinenvorstadt, Basel", "Aarbergergasse, Bern", "Flon Quarter, Lausanne"],
    instagrammableSpots: ["Matterhorn from Stellisee, Zermatt", "Chapel Bridge, Lucerne", "Jungfraujoch Top of Europe, Bernese Oberland", "Rhine Falls, Schaffhausen", "Lake Brienz, Interlaken"],
    areasToAvoid: ["Switzerland is generally very safe — no major areas to avoid"],
  },
  austria: {
    bestFoodAreas: ["Naschmarkt, Vienna", "Getreidegasse, Salzburg", "Grieskai, Graz", "Maria-Theresien-Straße, Innsbruck", "Bäckerstraße, Vienna"],
    nightlifeZones: ["Bermuda Triangle (Bermudadreieck), Vienna", "Gürtel Quarter, Vienna", "Rudolfskai, Salzburg", "Universitätsviertel, Graz", "Bogen, Innsbruck"],
    instagrammableSpots: ["Hallstatt Lake View, Hallstatt", "Schönbrunn Palace Gardens, Vienna", "Salzburg Fortress from Mirabell Garden, Salzburg", "Grossglockner High Alpine Road, Carinthia", "Golden Roof, Innsbruck"],
    areasToAvoid: ["Praterstern area at night, Vienna", "Certain areas near Westbahnhof at night, Vienna"],
  },
  sweden: {
    bestFoodAreas: ["Södermalm, Stockholm", "Haga District, Gothenburg", "Malmö Saluhall, Malmö", "Östermalmshallen, Stockholm", "Feskekörka Fish Market, Gothenburg"],
    nightlifeZones: ["Stureplan, Stockholm", "Avenyn, Gothenburg", "Södermalm/SoFo, Stockholm", "Lilla Torg, Malmö", "Gamla Stan, Stockholm"],
    instagrammableSpots: ["Gamla Stan Old Town, Stockholm", "Abisko Aurora Sky Station, Abisko", "Stockholm Archipelago, Stockholm", "Turning Torso, Malmö", "ICEHOTEL, Jukkasjärvi"],
    areasToAvoid: ["Rinkeby suburb at night, Stockholm", "Rosengård at night, Malmö"],
  },
  norway: {
    bestFoodAreas: ["Mathallen Food Hall, Oslo", "Fisketorget Fish Market, Bergen", "Solsiden, Trondheim", "Strandkaien, Stavanger", "Aker Brygge, Oslo"],
    nightlifeZones: ["Aker Brygge, Oslo", "Bryggen area, Bergen", "Solsiden, Trondheim", "Grünerløkka, Oslo", "Vågen area, Stavanger"],
    instagrammableSpots: ["Trolltunga, Odda", "Preikestolen (Pulpit Rock), Stavanger", "Geirangerfjord, Geiranger", "Lofoten Islands, Nordland", "Northern Lights in Tromsø, Tromsø"],
    areasToAvoid: ["Grønland area late at night, Oslo", "Remote mountain trails without preparation"],
  },
  denmark: {
    bestFoodAreas: ["Torvehallerne, Copenhagen", "Kødbyen (Meatpacking District), Copenhagen", "Strøget area, Copenhagen", "Aarhus Street Food, Aarhus", "Nyhavn, Copenhagen"],
    nightlifeZones: ["Vesterbro/Kødbyen, Copenhagen", "Nyhavn, Copenhagen", "Gothersgade area, Copenhagen", "Jægergårdsgade, Aarhus", "Nørrebro, Copenhagen"],
    instagrammableSpots: ["Nyhavn Colorful Houses, Copenhagen", "Tivoli Gardens, Copenhagen", "The Little Mermaid, Copenhagen", "Mons Klint White Cliffs, Møn", "Kronborg Castle, Helsingør"],
    areasToAvoid: ["Christiania late at night (Pusher Street), Copenhagen", "Nørrebro at very late hours"],
  },
  'czech republic': {
    bestFoodAreas: ["Manifesto Market, Prague", "Lokál pubs, Prague", "Stodolní area, Ostrava", "Zelný trh Market, Brno", "Dlouhá Street, Prague"],
    nightlifeZones: ["Dlouhá Street, Prague Old Town", "Žižkov district, Prague", "Cross Club, Prague", "Stodolní Street, Ostrava", "Veveří, Brno"],
    instagrammableSpots: ["Charles Bridge at sunrise, Prague", "Prague Castle, Prague", "Český Krumlov, South Bohemia", "Astronomical Clock, Prague", "Dancing House, Prague"],
    areasToAvoid: ["Wenceslas Square at very late night, Prague", "Holešovice industrial areas at night, Prague"],
  },
  czechia: {
    bestFoodAreas: ["Manifesto Market, Prague", "Lokál pubs, Prague", "Stodolní area, Ostrava", "Zelný trh Market, Brno", "Dlouhá Street, Prague"],
    nightlifeZones: ["Dlouhá Street, Prague Old Town", "Žižkov district, Prague", "Cross Club, Prague", "Stodolní Street, Ostrava", "Veveří, Brno"],
    instagrammableSpots: ["Charles Bridge at sunrise, Prague", "Prague Castle, Prague", "Český Krumlov, South Bohemia", "Astronomical Clock, Prague", "Dancing House, Prague"],
    areasToAvoid: ["Wenceslas Square at very late night, Prague", "Holešovice industrial areas at night, Prague"],
  },
  poland: {
    bestFoodAreas: ["Kazimierz District, Kraków", "Hala Koszyki, Warsaw", "Plac Nowy, Kraków", "Łazarz Market, Poznań", "Stary Browar area, Poznań"],
    nightlifeZones: ["Kazimierz, Kraków", "Nowy Świat, Warsaw", "Mazowiecka Street, Warsaw", "Łódź OFF Piotrkowska, Łódź", "Stare Miasto, Wrocław"],
    instagrammableSpots: ["Wawel Castle, Kraków", "Warsaw Old Town, Warsaw", "Wieliczka Salt Mine, Wieliczka", "Wrocław Cathedral Island, Wrocław", "Malbork Castle, Malbork"],
    areasToAvoid: ["Praga Północ at night, Warsaw", "Industrial zones of cities after dark"],
  },
  hungary: {
    bestFoodAreas: ["Central Market Hall, Budapest", "Gozsdu Courtyard, Budapest", "Koleves Kert, Budapest", "Liszt Ferenc tér, Budapest", "Karaván Street Food, Budapest"],
    nightlifeZones: ["Ruin Bars in Jewish Quarter, Budapest", "Gozsdu Courtyard, Budapest", "Király utca, Budapest", "Deák Ferenc tér area, Budapest", "Szimpla Kert area, Budapest"],
    instagrammableSpots: ["Parliament from Fisherman's Bastion, Budapest", "Széchenyi Thermal Baths, Budapest", "Szimpla Kert Ruin Bar, Budapest", "Buda Castle, Budapest", "Shoes on the Danube Bank, Budapest"],
    areasToAvoid: ["District VIII (Józsefváros) at night, Budapest", "Keleti station area late at night, Budapest"],
  },
  croatia: {
    bestFoodAreas: ["Dubrovnik Old Town, Dubrovnik", "Dolac Market, Zagreb", "Riva Promenade, Split", "Rovinj Old Town, Rovinj", "Zadar Old Town, Zadar"],
    nightlifeZones: ["Bačvice Beach clubs, Split", "Hvar Town, Hvar Island", "Tkalčićeva Street, Zagreb", "Dubrovnik Old Town bars, Dubrovnik", "Zrće Beach, Pag Island"],
    instagrammableSpots: ["Dubrovnik Old Town Walls, Dubrovnik", "Plitvice Lakes, Lika-Senj", "Hvar Lavender Fields, Hvar", "Zadar Sea Organ, Zadar", "Rovinj Old Town, Rovinj"],
    areasToAvoid: ["Some areas near Slavonski Brod at night", "Former minefields in rural Slavonia — stick to marked paths"],
    bestBeaches: ["Zlatni Rat Beach, Brač", "Stiniva Beach, Vis", "Bačvice Beach, Split", "Dubrovnik Banje Beach, Dubrovnik", "Sakarun Beach, Dugi Otok"],
  },
  'united arab emirates': {
    bestFoodAreas: ["Al Dhiyafah Road, Dubai", "Yas Island Restaurants, Abu Dhabi", "JBR The Walk, Dubai", "Saadiyat Island, Abu Dhabi", "Al Seef Heritage District, Dubai"],
    nightlifeZones: ["JBR and Dubai Marina, Dubai", "Downtown Dubai, Dubai", "Yas Island, Abu Dhabi", "DIFC, Dubai", "Barsha Heights, Dubai"],
    instagrammableSpots: ["Burj Khalifa At The Top, Dubai", "Sheikh Zayed Grand Mosque, Abu Dhabi", "Dubai Frame, Dubai", "Louvre Abu Dhabi, Abu Dhabi", "Palm Jumeirah Boardwalk, Dubai"],
    areasToAvoid: ["UAE is generally very safe — no major areas to avoid", "Sharjah Industrial Area at night"],
    bestBeaches: ["JBR Beach, Dubai", "Saadiyat Island Beach, Abu Dhabi", "Kite Beach, Dubai", "La Mer Beach, Dubai", "Al Mamzar Beach Park, Dubai"],
  },
  israel: {
    bestFoodAreas: ["Carmel Market (Shuk HaCarmel), Tel Aviv", "Machane Yehuda Market, Jerusalem", "Levinsky Market, Tel Aviv", "Nahalat Binyamin, Tel Aviv", "German Colony, Haifa"],
    nightlifeZones: ["Rothschild Boulevard, Tel Aviv", "Florentin, Tel Aviv", "Port Area, Tel Aviv", "Ben Yehuda Street, Jerusalem", "Masada Street, Haifa"],
    instagrammableSpots: ["Western Wall, Jerusalem", "Bahá'í Gardens, Haifa", "Tel Aviv Bauhaus buildings, Tel Aviv", "Masada Sunrise, Dead Sea", "Dead Sea Floating, Ein Bokek"],
    areasToAvoid: ["Gaza border area", "Parts of the West Bank without proper guidance", "Check travel advisories for current situation"],
  },
  jordan: {
    bestFoodAreas: ["Rainbow Street, Amman", "Downtown Al Balad, Amman", "Hashem Restaurant area, Amman", "Aqaba Fish Market, Aqaba", "Madaba, Madaba"],
    nightlifeZones: ["Rainbow Street, Amman", "Abdoun, Amman", "Sweifieh, Amman", "Jabal Amman, Amman", "Aqaba Marina, Aqaba"],
    instagrammableSpots: ["Petra Treasury (Al-Khazneh), Wadi Musa", "Wadi Rum Desert Camp, Aqaba", "Dead Sea, Sweimeh", "Amman Citadel, Amman", "Dana Nature Reserve, Tafila"],
    areasToAvoid: ["Syrian border regions", "Certain areas of downtown Amman very late at night"],
    bestBeaches: ["Aqaba South Beach, Aqaba", "Tala Bay, Aqaba", "Berenice Beach Club, Aqaba"],
  },
  'sri lanka': {
    bestFoodAreas: ["Pettah Market, Colombo", "Galle Face Green street food, Colombo", "Dutch Hospital Shopping Precinct, Colombo", "Galle Fort, Galle", "Kandy Market, Kandy"],
    nightlifeZones: ["Colombo Fort area, Colombo", "Park Street area, Colombo", "Unawatuna Beach bars, Galle", "Mirissa Beach, Matara", "Mount Lavinia, Colombo"],
    instagrammableSpots: ["Sigiriya Rock Fortress, Matale", "Nine Arch Bridge, Ella", "Galle Fort Lighthouse, Galle", "Temple of the Tooth, Kandy", "Nuwara Eliya Tea Plantations, Nuwara Eliya"],
    areasToAvoid: ["Northern Province former conflict areas (use caution)", "Pettah at night, Colombo"],
    bestBeaches: ["Unawatuna Beach, Galle", "Mirissa Beach, Matara", "Arugam Bay, Eastern Province", "Bentota Beach, Bentota", "Tangalle Beach, Hambantota"],
  },
  cambodia: {
    bestFoodAreas: ["Pub Street, Siem Reap", "Russian Market, Phnom Penh", "Street 308, Phnom Penh", "Old Market area, Siem Reap", "Kampot Riverfront, Kampot"],
    nightlifeZones: ["Pub Street, Siem Reap", "Bassac Lane, Phnom Penh", "Street 278 (Golden Street), Phnom Penh", "Otres Beach, Sihanoukville", "Kampot Riverside bars, Kampot"],
    instagrammableSpots: ["Angkor Wat Sunrise, Siem Reap", "Ta Prohm Tree Roots, Siem Reap", "Royal Palace, Phnom Penh", "Kampot Pepper Farms, Kampot", "Koh Rong Sanloem Beach, Sihanoukville"],
    areasToAvoid: ["Parts of Sihanoukville at night (casino areas)", "Remote border areas with Thailand"],
    bestBeaches: ["Koh Rong Sanloem, Sihanoukville", "Otres Beach, Sihanoukville", "Koh Rong Long Beach, Sihanoukville", "Kep Beach, Kep"],
  },
  cuba: {
    bestFoodAreas: ["La Bodeguita del Medio area, Old Havana", "San Cristóbal area, Old Havana", "Plaza Vieja, Old Havana", "Trinidad town center, Trinidad", "Viñales town, Pinar del Río"],
    nightlifeZones: ["Malecón, Havana", "Calle Obispo, Old Havana", "Vedado, Havana", "Casa de la Música, Trinidad", "Casa de la Trova, Santiago de Cuba"],
    instagrammableSpots: ["Old Havana vintage cars, Havana", "Viñales Valley, Pinar del Río", "Trinidad cobblestone streets, Trinidad", "Malecón sunset, Havana", "Plaza Mayor, Trinidad"],
    areasToAvoid: ["Centro Habana at late night", "Isolated areas without street lighting"],
    bestBeaches: ["Varadero Beach, Matanzas", "Playa Paraíso, Cayo Largo", "Playa Ancón, Trinidad", "Guardalavaca Beach, Holguín", "Cayo Coco, Ciego de Ávila"],
  },
};
