// Extra culture, food, and map category data for additional countries + gap fills

export const extraCultureProfiles = {
  // Gap fills for original 25 missing from knownCultureProfiles
  vietnam: {
    traditions: ["Ancestor worship and family altars in every home", "Tet (Lunar New Year) celebrations with kumquat trees and peach blossoms", "Water puppet theater (Mua Roi Nuoc) originating from the Red River Delta", "Ao Dai traditional dress worn on special occasions", "Full moon lantern festivals in Hoi An"],
    socialNorms: ["Use both hands when giving or receiving items", "Remove shoes before entering homes", "Avoid public displays of affection", "Address elders with proper titles", "Bargaining is expected at markets"],
    religionOverview: "Buddhism is the dominant religion (~16% practicing), alongside Taoism, Confucianism, Catholicism, and Cao Dai. Ancestor worship is widely practiced across all faiths.",
    etiquetteTips: ["Remove shoes before entering homes and temples", "Use both hands to pass things to others", "Do not touch someone's head", "Avoid pointing with your finger — use your whole hand", "Dress modestly at religious sites"],
  },
  greece: {
    traditions: ["Easter celebrations with midnight services and fireworks", "Name day celebrations (often more important than birthdays)", "Greek folk dancing (Syrtaki, Kalamatianos)", "Smashing plates at celebrations for good luck", "Olive harvesting traditions dating back millennia"],
    socialNorms: ["Greeks are warm and hospitable — expect offers of food and drink", "Avoid the 'moutza' gesture (open palm toward someone)", "Afternoon siesta (mesimeri) from 2-5 PM is respected", "Punctuality is relaxed — social events start late", "Offer to split the bill but expect the host to insist on paying"],
    religionOverview: "Greek Orthodox Christianity is the dominant religion (~90%), deeply woven into national identity, holidays, and daily life.",
    etiquetteTips: ["Dress modestly when visiting monasteries and churches", "Accept hospitality — refusing food or drink can be rude", "Avoid discussing sensitive topics like the Macedonia naming dispute", "Tipping 5-10% is customary at restaurants", "Greet people with a handshake or two kisses on the cheek"],
  },
  canada: {
    traditions: ["Ice hockey as a national passion and cultural identity", "Indigenous powwow ceremonies and cultural celebrations", "Maple syrup harvesting in spring (sugaring off)", "Thanksgiving in October (not November)", "Multicultural festivals in major cities"],
    socialNorms: ["Canadians are famously polite — saying 'sorry' is common", "Bilingualism (English and French) is valued, especially in Quebec", "Tipping 15-20% is standard at restaurants", "Punctuality is important", "Personal space is respected"],
    religionOverview: "Historically Christian (Catholic ~39%, Protestant ~20%), with growing religious diversity including Islam, Hinduism, Sikhism, and a significant non-religious population.",
    etiquetteTips: ["Always hold doors open for others", "Remove shoes when entering someone's home", "Be on time for appointments and meetings", "Respect Indigenous cultures and territories", "Avoid comparing Canada to the United States"],
  },
  argentina: {
    traditions: ["Tango dance and music originating in Buenos Aires", "Asado (barbecue) gatherings as a social ritual", "Mate tea sharing as a sign of friendship", "Gaucho culture and horsemanship traditions", "Carnival celebrations, especially in Gualeguaychú"],
    socialNorms: ["Greet with a kiss on the cheek, even when first meeting", "Dinner is typically eaten very late — 9-10 PM or later", "Mate is shared from a single cup and straw (bombilla)", "Argentines are passionate about football", "Punctuality is relaxed — arriving 15-30 minutes late is normal"],
    religionOverview: "Predominantly Roman Catholic (~63%), though church attendance has declined. Pope Francis is Argentine. Growing Protestant and non-religious populations.",
    etiquetteTips: ["Accept mate when offered — refusing can be rude", "Greet and goodbye everyone individually with a kiss", "Never pour your own mate first", "Compliment the asado chef (asador)", "Avoid discussing the Falklands/Malvinas conflict"],
  },
  peru: {
    traditions: ["Inti Raymi (Festival of the Sun) in Cusco dating to Inca times", "Marinera dance performed in traditional costumes", "Pachamanca — cooking food underground with hot stones", "Qoyllur Rit'i pilgrimage to glacier shrines", "Elaborate patron saint festivals in every village"],
    socialNorms: ["Greet with a kiss on the cheek among friends", "Punctuality is flexible — 'hora peruana' (Peruvian time)", "Family is central to social life", "Sharing food is a sign of friendship", "Respect for Andean traditions and Pachamama (Mother Earth)"],
    religionOverview: "Predominantly Roman Catholic (~75%), blended with Andean spiritual traditions. Many communities practice syncretic Catholicism incorporating Incan beliefs.",
    etiquetteTips: ["Always greet with Buenos días/tardes/noches", "Try local food when offered — it's a sign of respect", "Ask permission before photographing indigenous people", "Dress warmly for altitude in Cusco and the Andes", "Bargaining is acceptable at markets but not in shops"],
  },
  portugal: {
    traditions: ["Fado music — soulful Portuguese folk music listed by UNESCO", "Santos Populares street festivals in June with sardine grills", "Cork production — Portugal produces over half the world's cork", "Azulejo tile art covering buildings and churches", "Cod fish (bacalhau) prepared in 365 different ways"],
    socialNorms: ["Greet with two kisses on the cheek (right then left)", "Lunch is the main meal, often 1-2 hours", "Be on time for business but expect social gatherings to start late", "Coffee culture is strong — order an 'expresso' (bica in Lisbon)", "Portuguese are modest and dislike boastfulness"],
    religionOverview: "Predominantly Roman Catholic (~81%), deeply integrated into cultural traditions, festivals, and architecture. Growing secularism among younger generations.",
    etiquetteTips: ["Learn a few Portuguese words — locals appreciate the effort", "Don't confuse Portuguese with Spanish", "Tipping 5-10% is appreciated but not mandatory", "Dress smartly — Portuguese tend to dress well", "Visit churches respectfully, covering shoulders and knees"],
  },
  russia: {
    traditions: ["Maslenitsa (Pancake Week) celebrating the end of winter", "Banya (steam bath) culture as a social ritual", "Matryoshka (nesting dolls) as folk art symbols", "New Year celebrations (more important than Christmas)", "Traditional folk dancing and balalaika music"],
    socialNorms: ["Remove shoes when entering someone's home", "Bring a gift when visiting (flowers in odd numbers, not even)", "Toasting with vodka at meals is customary", "Russians may appear reserved in public but are warm privately", "Handshakes are firm — avoid shaking hands across a threshold"],
    religionOverview: "Russian Orthodox Christianity is predominant (~70% identify), with Islam (~10%), Buddhism, and Judaism as minority religions.",
    etiquetteTips: ["Always remove shoes when entering a home", "Bring flowers (odd number) or chocolates as gifts", "Don't whistle indoors — it's believed to bring bad luck", "Learn basic Russian greetings — English is not widely spoken", "Dress for the cold — Russian winters are severe"],
  },
  indonesia: {
    traditions: ["Gamelan orchestra music using bronze percussion instruments", "Batik textile art recognized by UNESCO", "Wayang (shadow puppet) theatrical performances", "Ngaben cremation ceremonies in Bali", "Gotong royong — community mutual cooperation"],
    socialNorms: ["Use the right hand for giving and receiving", "Remove shoes before entering homes and mosques", "Dress modestly, especially outside tourist areas", "Avoid touching someone's head", "Show respect to elders and authority figures"],
    religionOverview: "The world's largest Muslim-majority country (~87% Muslim), with Hindu, Protestant, Catholic, Buddhist, and Confucian minorities. Pancasila philosophy guarantees religious freedom.",
    etiquetteTips: ["Dress modestly at temples — sarongs may be required", "Remove shoes before entering mosques and homes", "Use your right hand for eating and exchanging items", "Avoid pointing with your index finger — use your thumb", "Learn 'Terima kasih' (thank you) — locals will appreciate it"],
  },

  // New 25 countries
  malaysia: {
    traditions: ["Open house traditions during festivals — all races welcome", "Wayang kulit (shadow puppet theater)", "Batik art and traditional weaving", "Silat martial arts", "Thaipusam festival with kavadi (burden-bearing)"],
    socialNorms: ["Use right hand for eating and interactions", "Remove shoes before entering homes and mosques", "Respect for elders (use titles like Encik, Puan)", "Multicultural sensitivity — Malay, Chinese, and Indian customs coexist", "Avoid touching heads or pointing feet at people"],
    religionOverview: "Islam is the official religion (~61%), with significant Buddhist (~20%), Christian (~9%), and Hindu (~6%) communities. Religious diversity is a cornerstone of Malaysian society.",
    etiquetteTips: ["Dress modestly when visiting mosques", "Use your right hand for giving and receiving", "Remove shoes before entering homes", "Avoid public displays of affection", "Try not to use the left hand for social interactions"],
  },
  'saudi arabia': {
    traditions: ["Generous hospitality — guests are honored with Arabic coffee and dates", "Ardah sword dance at celebrations", "Falconry as a revered cultural practice", "Traditional souq (market) shopping", "Hajj pilgrimage traditions"],
    socialNorms: ["Gender-segregated public spaces (changing with Vision 2030 reforms)", "Conservative dress, especially for women (abaya widely worn)", "Arabic coffee ceremony with dates is a sign of welcome", "Friday is the holy day and weekend", "Respect for prayer times (5 times daily)"],
    religionOverview: "Islam is the state religion (nearly 100% Muslim), primarily Sunni with a Shia minority. Saudi Arabia is home to Islam's two holiest cities: Mecca and Medina.",
    etiquetteTips: ["Dress very modestly — cover arms and legs", "Avoid alcohol — it is illegal in Saudi Arabia", "Respect prayer times — businesses close briefly", "Never photograph people without permission", "Use your right hand for greetings and eating"],
  },
  morocco: {
    traditions: ["Mint tea ceremony — pouring from height for froth", "Hammam (public bath) as a social and cleansing ritual", "Berber music and folklore", "Henna art for celebrations and weddings", "Traditional rug and carpet weaving"],
    socialNorms: ["Bargaining is expected and enjoyed at souqs", "Use right hand for eating, especially with shared dishes", "Greet with 'Assalamu Alaikum' and a handshake", "Dress modestly outside tourist areas", "Accept tea when offered — refusing is impolite"],
    religionOverview: "Islam is the state religion (~99% Muslim, predominantly Sunni Maliki). Islamic traditions are deeply embedded in daily life, architecture, and culture.",
    etiquetteTips: ["Dress modestly, covering shoulders and knees", "Always accept offered tea or food", "Use your right hand for eating when sharing dishes", "Bargain respectfully at markets — start at 50% of asking price", "Ask permission before photographing people, especially women"],
  },
  colombia: {
    traditions: ["Cumbia and Vallenato music and dance", "Carnival de Barranquilla (UNESCO-recognized)", "Coffee culture and coffee farm tours", "Aguardiente (anise liquor) toasting at celebrations", "Colorful chiva buses used as party buses"],
    socialNorms: ["Greet with a kiss on the cheek (friends and acquaintances)", "Colombians are very warm and hospitable", "Punctuality is flexible — 'Colombian time'", "Family is extremely important — Sunday family lunches are sacred", "Avoid discussing drug-related stereotypes"],
    religionOverview: "Predominantly Roman Catholic (~79%), with growing evangelical Protestant communities. Catholic traditions influence holidays and cultural celebrations.",
    etiquetteTips: ["Greet everyone with a handshake or kiss on the cheek", "Always say 'Buenos días/tardes/noches'", "Avoid sensitive topics about drug history", "Tip 10% at restaurants", "Dress neatly — Colombians take pride in appearance"],
  },
  'south africa': {
    traditions: ["Ubuntu philosophy — 'I am because we are'", "Braai (barbecue) culture — a national pastime", "Traditional Zulu, Xhosa, and Sotho ceremonies", "Madiba shirts in honor of Nelson Mandela", "Heritage Day ('National Braai Day') celebrations"],
    socialNorms: ["'Howzit' is a common informal greeting", "Handshake with various traditional grips depending on culture", "Respect for elders across all cultures", "Tipping 10-15% is customary", "Rugby and cricket are national sports alongside football"],
    religionOverview: "Christianity is predominant (~80%), with significant African traditional religion practices. Islam, Hinduism, and Judaism are also represented.",
    etiquetteTips: ["Learn about the diverse cultures — there are 11 official languages", "Be aware of personal safety, especially in cities at night", "Respect the complex history and avoid racial insensitivity", "Tip restaurant staff 10-15%", "Try 'biltong' — dried cured meat, a national snack"],
  },
  singapore: {
    traditions: ["Chinese New Year celebrations with lion dances and red packets", "Peranakan (Straits Chinese) cultural heritage", "Hawker center food culture (UNESCO-recognized)", "Racial Harmony Day celebrations", "Moon cake festival with lanterns"],
    socialNorms: ["Queuing ('kiasu' culture — fear of losing out)", "Cleanliness is enforced — fines for littering", "Chewing gum is banned (except therapeutic)", "Singlish (English-based creole) is widely spoken", "Respect for multiculturalism — Chinese, Malay, Indian, and other cultures"],
    religionOverview: "Highly diverse: Buddhism (~33%), Christianity (~19%), Islam (~14%), Taoism (~10%), Hinduism (~5%), with significant non-religious population (~19%).",
    etiquetteTips: ["Be punctual — Singaporeans value time", "Remove shoes when entering homes", "Respect the strict laws — no littering, no jaywalking", "Use chopsticks or fork and spoon (no knife needed)", "Do not tip — it's not customary and sometimes discouraged"],
  },
  philippines: {
    traditions: ["Fiesta culture — every town has an annual patron saint festival", "Bayanihan — community spirit of helping neighbors move houses", "Karaoke/videoke is a national passion", "Simbang Gabi — nine dawn Masses before Christmas", "Lechon (roasted pig) at every celebration"],
    socialNorms: ["'Po' and 'Opo' added to sentences when addressing elders", "Mano — pressing an elder's hand to your forehead as a sign of respect", "Filipino time — events often start 15-30 minutes late", "Hospitality is paramount — visitors are always fed", "Close family ties — extended families often live together"],
    religionOverview: "Predominantly Roman Catholic (~80%), making it the largest Catholic country in Asia. Islam (~5%) is prevalent in Mindanao. Iglesia ni Cristo is a notable local denomination.",
    etiquetteTips: ["Use 'po' and 'opo' when speaking to elders", "Accept food when offered — refusing may seem rude", "Remove shoes when entering homes", "Bring pasalubong (small gifts) when visiting", "Avoid criticizing religion or the Catholic Church"],
  },
  'new zealand': {
    traditions: ["Haka — Māori ceremonial war dance (performed at events and rugby)", "Hongi — pressing noses as a traditional Māori greeting", "Hangi — cooking food underground using heated rocks", "Waitangi Day celebrations (February 6)", "All Blacks rugby as a national identity"],
    socialNorms: ["Kiwis are laid-back and friendly", "Jandals (flip-flops) are worn everywhere, even some restaurants", "Tall poppy syndrome — modesty is valued, don't boast", "Outdoors and nature are central to lifestyle", "Tipping is not expected but appreciated"],
    religionOverview: "Historically Christian (~37%), but one of the most secular countries in the world. Growing non-religious population (~49%). Māori spiritual beliefs are respected.",
    etiquetteTips: ["Remove shoes before entering homes", "Learn basic Māori greetings (Kia ora)", "Respect Māori customs at marae (meeting grounds)", "Don't compare NZ to Australia", "Eco-consciousness is important — respect the environment"],
  },
  ireland: {
    traditions: ["Traditional Irish music sessions (seisiún) in pubs", "Gaelic Athletic Association sports (hurling, Gaelic football)", "Storytelling (seanchaí) tradition", "St. Patrick's Day celebrations worldwide", "Irish dancing (Riverdance made it globally famous)"],
    socialNorms: ["'Craic' (fun/entertainment) is central to Irish social life", "Pub culture is a social institution, not just about drinking", "Irish humor is self-deprecating and witty", "Rounds system — buying drinks for the group in turns", "Punctuality is loose for social events"],
    religionOverview: "Historically deeply Catholic (~78%), but rapid secularization in recent decades. Church attendance has declined significantly. Growing Protestant and non-religious populations.",
    etiquetteTips: ["Buy a round of drinks when it's your turn", "Never order an Irish Car Bomb — it's offensive", "Engage in conversation at pubs — Irish are very sociable", "Don't call Ireland part of the UK or Britain", "Learning a few Irish (Gaelic) words is appreciated"],
  },
  netherlands: {
    traditions: ["King's Day (April 27) — the entire country turns orange", "Sinterklaas tradition (December 5)", "Cycling culture — bikes outnumber people", "Tulip and flower festivals", "Stroopwafel and bitterballen as national snacks"],
    socialNorms: ["Dutch directness — honesty is valued over politeness", "Going Dutch — splitting bills is normal and expected", "Cycling is the primary mode of transport", "Punctuality is very important", "Three-kiss greeting on cheeks (right-left-right) for close friends"],
    religionOverview: "One of Europe's most secular nations. No religious majority: Roman Catholic (~24%), Protestant (~15%), Muslim (~5%), non-religious (~51%).",
    etiquetteTips: ["Always be on time — the Dutch value punctuality", "Lock your bike — theft is common", "Don't stand in bike lanes — cyclists have right of way", "Tipping 5-10% is appreciated but not required", "Be direct — Dutch people prefer honesty"],
  },
  switzerland: {
    traditions: ["Alphorn playing in mountain valleys", "Fondue and raclette as social dining traditions", "Fasnacht (carnival) — especially wild in Basel", "Swiss National Day (August 1) with bonfires and fireworks", "Yodeling traditions in Alpine regions"],
    socialNorms: ["Punctuality is extremely important — Swiss trains run on the second", "Greet with three kisses on the cheek (right-left-right)", "Quiet hours (Ruhezeiten) — no loud noise on Sundays and after 10 PM", "Recycling is mandatory and taken very seriously", "Privacy is highly valued"],
    religionOverview: "Roman Catholic (~35%) and Protestant Reformed (~23%), with growing Muslim (~5%) and non-religious (~28%) populations. Religion varies by canton.",
    etiquetteTips: ["Be on time — even 5 minutes late is noticed", "Respect quiet hours — no washing, vacuuming, or noise on Sundays", "Recycle meticulously — separate glass, paper, organic waste", "Greet shopkeepers when entering and leaving stores", "Clink glasses and make eye contact when toasting"],
  },
  austria: {
    traditions: ["Vienna coffeehouse culture (UNESCO Intangible Heritage)", "Waltz tradition — Vienna is the city of music", "Christmas markets (Christkindlmärkte)", "Krampus — the Christmas devil who accompanies St. Nicholas", "Schuhplattler folk dance in the Alps"],
    socialNorms: ["Formal titles matter — use Herr/Frau with surnames", "Greet with 'Grüß Gott' (God's greeting) not 'Hallo'", "Punctuality is essential", "Coffee and cake (Kaffee und Kuchen) is a cherished afternoon ritual", "Handshakes are firm and accompanied by eye contact"],
    religionOverview: "Predominantly Roman Catholic (~57%), with growing non-religious (~22%), Protestant (~4%), and Muslim (~8%) populations.",
    etiquetteTips: ["Use titles like Herr Doktor or Frau Professor", "Arrive on time or a few minutes early", "Say 'Grüß Gott' when entering shops and restaurants", "Dress well for the theater and concerts", "Do not start eating until the host says 'Mahlzeit' or 'Guten Appetit'"],
  },
  sweden: {
    traditions: ["Midsummer celebrations with maypole dancing and herring", "Fika — sacred coffee-and-pastry break", "Lucia celebrations (December 13) with candle processions", "Crayfish parties (kräftskiva) in August", "Easter witches — children dress as witches for candy"],
    socialNorms: ["Lagom — the concept of 'just right' or moderation", "Swedes value personal space and quietness", "Gender equality is deeply ingrained", "Shoes off when entering homes", "Allemansrätten — everyone's right to roam in nature"],
    religionOverview: "Officially Church of Sweden (Lutheran, ~57% nominal members), but one of the most secular countries. Only ~2% attend church regularly.",
    etiquetteTips: ["Remove shoes when entering someone's home", "Respect personal space — avoid physical contact with strangers", "Never skip fika — it's an essential part of Swedish culture", "Thank the hosts after a dinner with 'Tack för maten'", "Be on time — Swedes value punctuality"],
  },
  norway: {
    traditions: ["Constitution Day (May 17) — the biggest national celebration with parades", "Koselig/hygge — creating warmth and coziness indoors", "Friluftsliv — outdoor life philosophy, rain or shine", "Bunads — traditional folk costumes worn on May 17", "Midnight sun celebrations in summer"],
    socialNorms: ["Norwegians value equality and modesty (Janteloven)", "Outdoor activities are central to life — hiking, skiing, fishing", "Personal space is important — don't stand too close", "Tipping is not expected but rounding up is fine", "English is widely spoken"],
    religionOverview: "Church of Norway (Evangelical Lutheran) is the state church (~68% nominal), but Norway is highly secular. Regular church attendance is among the lowest in Europe.",
    etiquetteTips: ["Remove shoes when entering homes", "Respect nature — follow outdoor ethics (leave no trace)", "Don't boast or show off — modesty is valued", "Thank hosts with 'Takk for maten' after meals", "Be prepared for expensive prices — Norway is costly"],
  },
  denmark: {
    traditions: ["Hygge — the art of cozy, warm togetherness", "Fastelavn — Carnival where children dress up and hit a barrel", "Sankt Hans Aften — Midsummer Eve bonfire celebrations", "Julefrokost — Christmas lunch parties throughout December", "Smørrebrød — elaborate open-faced sandwich tradition"],
    socialNorms: ["Danes value informality — first names are common even in business", "Cycling is a way of life — Copenhagen has more bikes than cars", "Janteloven — modesty is valued, don't boast", "Work-life balance is sacred", "Hygge is not just a concept — it's a lifestyle"],
    religionOverview: "Evangelical Lutheran (~74% nominal members through Church of Denmark), but highly secular. Only ~3% attend church regularly. Growing non-religious population.",
    etiquetteTips: ["Remove shoes when entering Danish homes", "Bring wine, chocolate, or flowers when invited to dinner", "Be on time — Danes are punctual", "Don't skip the handshake greeting", "Join in hygge — light candles, cozy up, and be present"],
  },
  'czech republic': {
    traditions: ["Beer culture — Czech Republic has the highest beer consumption per capita", "Easter Monday — boys whip girls with willow sticks (pomlázka)", "Christmas carp — live carp is bought days before and kept in the bathtub", "Burning of the Witches (Pálení čarodějnic) on April 30", "Mushroom foraging as a national pastime"],
    socialNorms: ["Czechs are reserved initially but warm once comfortable", "Beer is cheaper than water in many pubs", "Toasting with eye contact is important", "Punctuality is expected", "Don't confuse Czechs with Slovaks"],
    religionOverview: "One of the most atheist countries in the world. Only ~10% identify as Catholic, ~2% other Christian. Over 70% identify as non-religious.",
    etiquetteTips: ["Clink glasses and maintain eye contact when toasting (Na zdraví!)", "Remove shoes when entering homes", "Don't call it 'Czechoslovakia' — it's been the Czech Republic since 1993", "Tipping 10% is customary at restaurants", "Try the beer — Czech pilsner is world-famous"],
  },
  czechia: {
    traditions: ["Beer culture — Czech Republic has the highest beer consumption per capita", "Easter Monday — boys whip girls with willow sticks (pomlázka)", "Christmas carp — live carp is bought days before and kept in the bathtub", "Burning of the Witches (Pálení čarodějnic) on April 30", "Mushroom foraging as a national pastime"],
    socialNorms: ["Czechs are reserved initially but warm once comfortable", "Beer is cheaper than water in many pubs", "Toasting with eye contact is important", "Punctuality is expected", "Don't confuse Czechs with Slovaks"],
    religionOverview: "One of the most atheist countries in the world. Only ~10% identify as Catholic, ~2% other Christian. Over 70% identify as non-religious.",
    etiquetteTips: ["Clink glasses and maintain eye contact when toasting (Na zdraví!)", "Remove shoes when entering homes", "Don't call it 'Czechoslovakia' — it's been the Czech Republic since 1993", "Tipping 10% is customary at restaurants", "Try the beer — Czech pilsner is world-famous"],
  },
  poland: {
    traditions: ["Wigilia — elaborate Christmas Eve dinner with 12 dishes", "Śmigus-Dyngus (Wet Monday) — splashing water on Easter Monday", "Name day celebrations (imieniny) more important than birthdays", "Pierogi-making as a family tradition", "All Saints' Day candle vigils at cemeteries (November 1)"],
    socialNorms: ["Poles are warm and hospitable once they know you", "Handshake or kiss on the cheek for greetings", "Offering food to guests is standard hospitality", "Family and religion are important pillars", "Poles take pride in their history and resilience"],
    religionOverview: "One of Europe's most Catholic countries (~85% Catholic). The Catholic Church plays a significant role in Polish culture, politics, and daily life. Pope John Paul II was Polish.",
    etiquetteTips: ["Bring flowers or wine when visiting someone's home", "Use 'Pan' (Mr.) and 'Pani' (Mrs.) as formal address", "Don't refuse food or drink when offered", "Remove shoes when entering homes", "Be respectful of Poland's complex history, especially WWII"],
  },
  hungary: {
    traditions: ["Thermal bathing culture — Budapest has the most thermal springs of any capital", "Pálinka (fruit brandy) toasting traditions", "Busójárás — traditional carnival with scary masks in Mohács", "Goulash cooking as both daily food and competitive sport", "Wine regions like Tokaj producing world-famous sweet wine"],
    socialNorms: ["Hungarians are proud of their unique language and culture", "Toast with wine but NOT beer (historical tradition)", "Name day celebrations are important", "Hungarians stand for the national anthem", "Handshake is the standard greeting"],
    religionOverview: "Roman Catholic (~37%), Calvinist/Reformed (~12%), Lutheran (~2%), with a growing non-religious population (~27%).",
    etiquetteTips: ["Never clink beer glasses — Hungarians avoid it for historical reasons", "Use the surname first in Hungarian (but not when speaking English)", "Bring wine or chocolates when visiting homes", "Tipping 10% is expected at restaurants", "Try the thermal baths — it's a quintessential Hungarian experience"],
  },
  croatia: {
    traditions: ["Klapa singing — traditional Dalmatian a cappella harmony (UNESCO)", "Sinjska Alka — medieval jousting tournament held annually since 1715", "Licitarsko Srce — decorated gingerbread hearts as love tokens", "Wine harvest festivals along the coast", "Korčula Moreška — traditional sword dance"],
    socialNorms: ["Croatians are warm and sociable, especially along the coast", "Coffee culture is huge — sitting in cafes for hours is normal", "Family and local community are very important", "Graut with a handshake or cheek kisses", "Punctuality is expected for business, relaxed socially"],
    religionOverview: "Predominantly Roman Catholic (~86%). Catholicism is deeply intertwined with Croatian national identity and cultural traditions.",
    etiquetteTips: ["Greet with a firm handshake or two kisses on the cheek", "Try rakija (fruit brandy) when offered — it's a sign of hospitality", "Don't compare Croatia to Serbia or the former Yugoslavia", "Tipping 10% is appreciated at restaurants", "Dress appropriately when visiting churches"],
  },
  'united arab emirates': {
    traditions: ["Arabic coffee (gahwa) ceremony with dates", "Falconry — a deeply revered practice protected by UNESCO", "Camel racing and beauty pageants", "Pearl diving heritage — Dubai's origin story", "Henna art for celebrations and weddings"],
    socialNorms: ["Respect for Islamic customs and prayer times", "Modest dress is expected, especially outside resort areas", "Alcohol is only served in licensed venues like hotels", "Friday-Saturday is the weekend", "Greet with 'Assalamu Alaikum' and a handshake (same gender)"],
    religionOverview: "Islam is the official religion (~76% Muslim). The UAE practices a moderate, tolerant form of Islam. Churches, Hindu temples, and a synagogue exist. Expatriates practice freely.",
    etiquetteTips: ["Dress modestly in public — cover shoulders and knees", "Don't eat, drink, or smoke in public during Ramadan daylight hours", "Avoid public displays of affection", "Photography of government buildings and military is prohibited", "Accept Arabic coffee and dates when offered"],
  },
  israel: {
    traditions: ["Shabbat observance — from Friday sunset to Saturday sunset", "Passover Seder — ceremonial meal recounting the Exodus", "Sukkot — building outdoor huts for the harvest festival", "Bar/Bat Mitzvah coming-of-age ceremonies", "Purim costumes and festivities"],
    socialNorms: ["Israelis are direct and informal in communication", "Shabbat is widely observed — many businesses close Friday afternoon", "Military service is mandatory, creating strong social bonds", "Debate and discussion are valued cultural traits", "Tipping 10-15% is expected at restaurants"],
    religionOverview: "Judaism (~74%), Islam (~18%), Christianity (~2%), Druze (~2%). Israel is the world's only Jewish-majority state. Religious and secular tensions exist.",
    etiquetteTips: ["Be aware of Shabbat — plan activities accordingly", "Don't bring up politics unless prepared for passionate debate", "Dress modestly at religious sites — cover knees and shoulders", "Respect kashrut (kosher) dietary laws in religious areas", "Learn basic Hebrew greetings (Shalom, Toda)"],
  },
  jordan: {
    traditions: ["Mansaf — the national dish eaten communally with hands", "Bedouin hospitality — guests are treated like royalty", "Arabic coffee ceremony with cardamom", "Traditional Dabke line dance at celebrations", "Desert camping with Bedouin tribes in Wadi Rum"],
    socialNorms: ["Hospitality is a sacred duty — guests are honored", "Dress modestly, especially outside Amman", "Greet with a handshake and right hand over heart", "Refusing food or drink can be considered rude", "Friday is the holy day — many businesses close"],
    religionOverview: "Islam is the state religion (~97% Muslim, predominantly Sunni). Christianity (~2%) has a protected minority status. Jordan is known for religious tolerance.",
    etiquetteTips: ["Accept tea or coffee when offered — at least 3 cups is polite", "Use your right hand for eating and greetings", "Dress modestly — cover shoulders and knees", "Ask permission before photographing people", "Remove shoes when entering homes and mosques"],
  },
  'sri lanka': {
    traditions: ["Kandy Esala Perahera — spectacular procession with decorated elephants", "Sinhala and Tamil New Year (April) with traditional games", "Cricket as a national obsession", "Ayurvedic medicine traditions", "Temple offerings of lotus flowers and coconut oil lamps"],
    socialNorms: ["Remove shoes before entering temples and homes", "Use right hand for eating and interactions", "Nod your head from side to side to indicate agreement", "Dress modestly at religious sites", "Sri Lankans are warm and hospitable to visitors"],
    religionOverview: "Buddhism (~70%), Hinduism (~13%), Islam (~10%), Christianity (~7%). Buddhism is given constitutional primacy. Religious diversity is a hallmark of Sri Lankan culture.",
    etiquetteTips: ["Remove shoes and hats before entering Buddhist temples", "Don't pose with your back to Buddha statues for photos", "Dress modestly — cover shoulders and knees at temples", "Use your right hand for greetings and eating", "Avoid pointing the soles of your feet at people or statues"],
  },
  cambodia: {
    traditions: ["Apsara dance — classical Khmer dance dating back to Angkor era", "Water Festival (Bon Om Touk) celebrating the Tonle Sap reversal", "Khmer New Year celebrations with sand mound building", "Silk weaving on traditional looms", "Offering food to monks every morning (alms giving)"],
    socialNorms: ["The sampeah greeting (palms pressed together, bow)", "Monks are highly respected — women should not touch them", "Feet are the lowest body part — don't point them at people", "Head is sacred — don't touch others' heads", "Cambodians are gentle and avoid confrontation"],
    religionOverview: "Theravada Buddhism (~97%), deeply embedded in Cambodian identity and daily life. Hinduism influenced Angkor-era culture. Islam and Christianity are small minorities.",
    etiquetteTips: ["Greet with the sampeah (palms together, slight bow)", "Remove shoes before entering homes and temples", "Dress modestly at Angkor Wat and other temples", "Never touch a monk if you are a woman", "Don't point your feet at Buddha images or people"],
  },
  cuba: {
    traditions: ["Salsa and Son music — the heartbeat of Cuban culture", "Afro-Cuban Santería religious practices", "Vintage car culture — 1950s American cars as daily transport", "Cigar rolling tradition (especially in Pinar del Río)", "Rumba dance and music gatherings in streets and parks"],
    socialNorms: ["Cubans are extremely friendly and sociable", "Music is everywhere — spontaneous dancing is normal", "Sharing is a cultural norm due to limited resources", "Community-focused lifestyle — neighbors are like family", "Patience is essential — queuing is a way of life"],
    religionOverview: "Officially secular. Catholicism (~60%), Protestantism (~5%), and Santería (Afro-Cuban syncretic religion blending Yoruba and Catholic elements) are widely practiced, often simultaneously.",
    etiquetteTips: ["Bring gifts like soap, shampoo, or medicine — they're hard to get", "Ask before photographing military personnel or installations", "Learn some Spanish — English is not widely spoken", "Bring cash (EUR preferred) — credit cards often don't work", "Engage with locals — Cubans love to talk and share stories"],
  },
};

export const extraFoodData = {
  // Gap fills for original 25
  'south korea': [
    { name: "Bibimbap", description: "Mixed rice bowl topped with vegetables, meat, egg, and gochujang chili paste.", famousFor: "Korea's most iconic rice dish, meaning 'mixed rice'." },
    { name: "Korean BBQ (Gogigui)", description: "Grilled meat (beef, pork) cooked at your table with side dishes.", famousFor: "A social dining experience with ssamjang and lettuce wraps." },
    { name: "Kimchi", description: "Fermented spicy cabbage — Korea's most famous side dish.", famousFor: "A staple at every Korean meal, with over 200 varieties." },
    { name: "Tteokbokki", description: "Chewy rice cakes in sweet and spicy gochujang sauce.", famousFor: "Korea's favorite street food, found at every market." },
    { name: "Japchae", description: "Glass noodles stir-fried with vegetables, meat, and soy sauce.", famousFor: "A celebratory dish served at Korean holidays and parties." },
  ],
  'united kingdom': [
    { name: "Fish and Chips", description: "Battered cod or haddock with thick-cut chips, served with mushy peas and tartar sauce.", famousFor: "Britain's most iconic takeaway meal since the 1860s." },
    { name: "Full English Breakfast", description: "Hearty plate of bacon, eggs, sausages, beans, toast, tomatoes, and black pudding.", famousFor: "The quintessential British 'fry-up' morning meal." },
    { name: "Sunday Roast", description: "Roasted meat (beef, lamb, chicken) with Yorkshire pudding, roast potatoes, and gravy.", famousFor: "A cherished British family tradition every Sunday." },
    { name: "Cornish Pasty", description: "Crimped pastry filled with beef, potato, swede, and onion.", famousFor: "Originally a miner's lunch in Cornwall, now beloved nationwide." },
    { name: "Afternoon Tea", description: "Tiered sandwiches, scones with clotted cream, and pastries with tea.", famousFor: "An elegant British tradition dating back to the 1840s." },
  ],
  egypt: [
    { name: "Koshari", description: "Mixed rice, lentils, pasta, and chickpeas topped with spiced tomato sauce and crispy onions.", famousFor: "Egypt's beloved national street food dish." },
    { name: "Ful Medames", description: "Slow-cooked fava beans seasoned with olive oil, lemon, cumin, and garlic.", famousFor: "Egypt's staple breakfast eaten for thousands of years." },
    { name: "Molokhia", description: "Thick green soup made from jute leaves, often served with rice and chicken.", famousFor: "A traditional Egyptian comfort food with ancient roots." },
    { name: "Shawarma", description: "Marinated meat shaved from a rotating spit, wrapped in pita with tahini.", famousFor: "Egypt's most popular street food wrap." },
    { name: "Baklava", description: "Layered filo pastry filled with nuts and drenched in honey syrup.", famousFor: "A beloved Middle Eastern dessert perfected in Egypt." },
  ],
  turkey: [
    { name: "Kebab", description: "Grilled meat dishes in countless regional varieties — from Adana to İskender.", famousFor: "Turkey's most famous culinary export, with dozens of variations." },
    { name: "Baklava", description: "Paper-thin filo layers with pistachios or walnuts, soaked in honey syrup.", famousFor: "Gaziantep baklava is considered the world's finest." },
    { name: "Lahmacun", description: "Thin flatbread topped with minced meat, herbs, and spices — 'Turkish pizza'.", famousFor: "A beloved fast food rolled up with fresh vegetables and lemon." },
    { name: "Manti", description: "Tiny Turkish dumplings filled with spiced meat, served with yogurt and garlic butter.", famousFor: "The smaller the dumpling, the more skilled the cook." },
    { name: "Turkish Breakfast (Kahvaltı)", description: "Elaborate spread of cheeses, olives, honey, eggs, simit, and tea.", famousFor: "One of the world's most lavish breakfast traditions." },
  ],
  russia: [
    { name: "Borscht", description: "Hearty beetroot soup with cabbage, potatoes, and beef, served with sour cream.", famousFor: "Russia's most iconic soup, deep crimson in color." },
    { name: "Pelmeni", description: "Boiled dumplings filled with minced meat, served with butter or sour cream.", famousFor: "A beloved comfort food, especially in Siberian winters." },
    { name: "Blini", description: "Thin crepes served with caviar, smoked salmon, or jam and sour cream.", famousFor: "Traditionally eaten during Maslenitsa (Pancake Week)." },
    { name: "Beef Stroganoff", description: "Sautéed beef strips in a sour cream mushroom sauce, served over noodles.", famousFor: "A Russian classic that became popular worldwide." },
    { name: "Pirozhki", description: "Small baked or fried buns stuffed with meat, cabbage, or potatoes.", famousFor: "Russia's favorite street food and snack." },
  ],
  indonesia: [
    { name: "Nasi Goreng", description: "Indonesian fried rice with sweet soy sauce, egg, and shrimp paste.", famousFor: "Indonesia's national dish — found everywhere from street stalls to fine dining." },
    { name: "Satay", description: "Grilled meat skewers served with rich peanut sauce.", famousFor: "One of Southeast Asia's most popular street foods." },
    { name: "Rendang", description: "Slow-cooked dry curry of beef in coconut milk and spices.", famousFor: "Voted the world's most delicious food by CNN." },
    { name: "Gado-Gado", description: "Blanched vegetables and tofu with rich peanut dressing.", famousFor: "Indonesia's famous vegetarian salad with deep flavor." },
    { name: "Bakso", description: "Springy meatball soup with noodles in a savory beef broth.", famousFor: "Indonesia's beloved comfort food, sold by street cart vendors." },
  ],

  // New 25 countries
  malaysia: [
    { name: "Nasi Lemak", description: "Coconut rice with sambal, anchovies, peanuts, boiled egg, and cucumber.", famousFor: "Malaysia's unofficial national dish, eaten at any time of day." },
    { name: "Char Kway Teow", description: "Stir-fried flat noodles with shrimp, cockles, Chinese sausage, and bean sprouts.", famousFor: "Penang's most famous hawker dish, cooked over high heat." },
    { name: "Roti Canai", description: "Flaky flatbread served with dhal or curry for dipping.", famousFor: "A beloved Indo-Malay breakfast found at every mamak stall." },
    { name: "Laksa", description: "Spicy coconut curry noodle soup with prawns and fresh herbs.", famousFor: "Available in many regional varieties — Penang laksa is the most famous." },
    { name: "Satay", description: "Grilled meat skewers with peanut sauce, served with rice cakes.", famousFor: "Malaysia's signature street food, best in Kajang." },
  ],
  'saudi arabia': [
    { name: "Kabsa", description: "Fragrant spiced rice with meat (lamb or chicken), topped with nuts and raisins.", famousFor: "Saudi Arabia's national dish, served at family gatherings." },
    { name: "Mandi", description: "Tender meat and rice cooked in a tandoor-style underground pit.", famousFor: "A Yemeni-origin dish beloved across Saudi Arabia." },
    { name: "Mutabbaq", description: "Stuffed pancake filled with spiced minced meat, egg, and herbs.", famousFor: "A popular street food and Ramadan iftar staple." },
    { name: "Jareesh", description: "Porridge-like dish made from crushed wheat and meat.", famousFor: "Traditional Najdi comfort food, slow-cooked for hours." },
    { name: "Arabic Coffee and Dates", description: "Cardamom-spiced coffee served with sweet dates.", famousFor: "The quintessential Saudi hospitality gesture, served at every gathering." },
  ],
  morocco: [
    { name: "Tagine", description: "Slow-cooked stew of meat, vegetables, and spices in a conical clay pot.", famousFor: "Morocco's most iconic dish, named after the pot it's cooked in." },
    { name: "Couscous", description: "Steamed semolina served with meat, vegetables, and broth.", famousFor: "The traditional Friday family meal across Morocco." },
    { name: "Pastilla", description: "Savory-sweet pie with pigeon or chicken, almonds, and cinnamon in filo pastry.", famousFor: "A delicate balance of sweet and savory that defines Moroccan cuisine." },
    { name: "Harira", description: "Hearty tomato-based soup with lentils, chickpeas, and lamb.", famousFor: "The traditional soup to break fast during Ramadan." },
    { name: "Moroccan Mint Tea", description: "Green tea steeped with fresh mint and sugar, poured from height.", famousFor: "Called 'Moroccan whiskey' — refusing is considered rude." },
  ],
  colombia: [
    { name: "Bandeja Paisa", description: "Enormous platter with beans, rice, chicharron, arepa, avocado, egg, and plantain.", famousFor: "Colombia's most famous and filling regional dish from Antioquia." },
    { name: "Arepas", description: "Grilled corn cakes stuffed with cheese, meat, or eggs.", famousFor: "A Colombian staple eaten daily for breakfast or snacks." },
    { name: "Empanadas", description: "Deep-fried corn pockets filled with meat, potato, and spices.", famousFor: "Colombia's go-to street food, best with aji hot sauce." },
    { name: "Ajiaco", description: "Hearty chicken and potato soup with corn, capers, and cream.", famousFor: "Bogotá's signature soup, perfect for the cool Andean climate." },
    { name: "Patacones", description: "Twice-fried green plantain discs served as a side or with toppings.", famousFor: "A crunchy staple accompanying many Colombian meals." },
  ],
  'south africa': [
    { name: "Braai (BBQ)", description: "South African barbecue featuring boerewors sausage, steaks, and sosaties.", famousFor: "More than just food — it's a social institution and national pastime." },
    { name: "Bobotie", description: "Spiced minced-meat bake with an egg custard topping, served with yellow rice.", famousFor: "South Africa's national dish with Cape Malay origins." },
    { name: "Biltong", description: "Air-dried cured meat seasoned with coriander and pepper.", famousFor: "South Africa's beloved high-protein snack — different from jerky." },
    { name: "Bunny Chow", description: "Hollowed-out bread loaf filled with spicy curry.", famousFor: "A uniquely South African fast food originating in Durban's Indian community." },
    { name: "Koeksisters", description: "Braided dough deep-fried and soaked in cold sugar syrup.", famousFor: "A sweet, sticky South African treat — crispy outside, syrupy inside." },
  ],
  singapore: [
    { name: "Hainanese Chicken Rice", description: "Poached chicken with fragrant rice cooked in chicken broth, with chili and ginger sauce.", famousFor: "Singapore's unofficial national dish, simple yet perfected." },
    { name: "Chilli Crab", description: "Stir-fried crab in sweet and spicy tomato-chili sauce, mopped up with mantou buns.", famousFor: "Singapore's most famous seafood dish — messy but unforgettable." },
    { name: "Laksa", description: "Rich coconut curry noodle soup with prawns, fish cake, and tau pok.", famousFor: "A hawker center classic blending Chinese and Malay flavors." },
    { name: "Char Kway Teow", description: "Smoky wok-fried flat noodles with lap cheong, cockles, and bean sprouts.", famousFor: "A hawker legend — the best stalls have hour-long queues." },
    { name: "Kaya Toast with Soft-Boiled Eggs", description: "Toasted bread with coconut jam (kaya) and butter, plus runny eggs with soy sauce.", famousFor: "Singapore's quintessential breakfast, found at every kopitiam." },
  ],
  philippines: [
    { name: "Adobo", description: "Chicken or pork braised in vinegar, soy sauce, garlic, and bay leaves.", famousFor: "The unofficial national dish — every Filipino family has their own recipe." },
    { name: "Lechon", description: "Whole roasted pig with crispy skin and tender, flavorful meat.", famousFor: "The centerpiece of every Filipino fiesta and celebration." },
    { name: "Sinigang", description: "Sour soup with tamarind broth, pork or shrimp, and vegetables.", famousFor: "A beloved comfort food with a distinctive tangy flavor." },
    { name: "Halo-Halo", description: "Shaved ice dessert with sweet beans, jellies, fruits, leche flan, ube ice cream, and milk.", famousFor: "The ultimate Filipino summer dessert — 'mix-mix' in Filipino." },
    { name: "Lumpia", description: "Fresh or fried spring rolls filled with vegetables and/or meat.", famousFor: "A Filipino fiesta staple with Chinese origins." },
  ],
  'new zealand': [
    { name: "Hangi", description: "Traditional Māori feast cooked underground with heated rocks.", famousFor: "An ancient cooking method producing incredibly tender, smoky meat." },
    { name: "Pavlova", description: "Meringue dessert topped with cream and fresh kiwifruit, strawberries, and passionfruit.", famousFor: "A fierce debate with Australia over who invented it (NZ claims it)." },
    { name: "Fish and Chips", description: "Fresh battered fish (often blue cod or snapper) with thick-cut chips.", famousFor: "A Kiwi beach tradition — best eaten wrapped in paper by the ocean." },
    { name: "Meat Pie", description: "Savory pastry filled with minced beef and gravy — a handheld lunch.", famousFor: "New Zealand consumes more meat pies per capita than anywhere else." },
    { name: "Hokey Pokey Ice Cream", description: "Vanilla ice cream with crunchy toffee honeycomb pieces.", famousFor: "New Zealand's most popular ice cream flavor — uniquely Kiwi." },
  ],
  ireland: [
    { name: "Irish Stew", description: "Hearty slow-cooked lamb or mutton with potatoes, carrots, and onions.", famousFor: "Ireland's most traditional comfort food for centuries." },
    { name: "Soda Bread", description: "Dense, crusty bread leavened with baking soda instead of yeast.", famousFor: "A staple of Irish baking — best served warm with butter." },
    { name: "Boxty", description: "Traditional Irish potato pancake made with grated and mashed potatoes.", famousFor: "A beloved Irish saying: 'Boxty on the griddle, boxty in the pan...'" },
    { name: "Colcannon", description: "Mashed potatoes mixed with cabbage or kale, butter, and milk.", famousFor: "Traditional Halloween dish — coins hidden inside for luck." },
    { name: "Full Irish Breakfast", description: "Rashers, sausages, black and white pudding, eggs, beans, toast, and tea.", famousFor: "The hearty Irish morning meal to fuel the entire day." },
  ],
  netherlands: [
    { name: "Stroopwafel", description: "Two thin waffles sandwiched with caramel syrup — best warm from a market stall.", famousFor: "The Netherlands' most beloved sweet treat, invented in Gouda." },
    { name: "Bitterballen", description: "Crispy deep-fried balls filled with beef ragout, served with mustard.", famousFor: "The essential Dutch bar snack — always ordered with beer." },
    { name: "Haring (Raw Herring)", description: "Fresh raw herring with onions and pickles, eaten by tilting your head back.", famousFor: "A Dutch tradition — 'Hollandse Nieuwe' in late May is a national event." },
    { name: "Erwtensoep (Pea Soup)", description: "Thick split pea soup with smoked sausage (rookworst) and rye bread.", famousFor: "So thick your spoon should stand up in it — perfect for Dutch winters." },
    { name: "Poffertjes", description: "Mini fluffy Dutch pancakes dusted with powdered sugar and butter.", famousFor: "A favorite at Dutch markets and fairs." },
  ],
  switzerland: [
    { name: "Fondue", description: "Melted cheese (Gruyère and Emmental) in a pot, eaten by dipping bread cubes.", famousFor: "Switzerland's most iconic social dining experience." },
    { name: "Raclette", description: "Melted cheese scraped onto potatoes, cornichons, and pickled onions.", famousFor: "A warming Alpine dish perfect for cold mountain evenings." },
    { name: "Rösti", description: "Crispy grated potato cake, pan-fried to golden perfection.", famousFor: "The 'Röstigraben' divides German-speaking and French-speaking Switzerland." },
    { name: "Zürich-style Veal (Zürcher Geschnetzeltes)", description: "Sliced veal in a creamy mushroom and white wine sauce, served with rösti.", famousFor: "Zurich's signature dish, rich and elegant." },
    { name: "Swiss Chocolate", description: "World-renowned milk and dark chocolate from brands like Lindt and Toblerone.", famousFor: "Switzerland consumes more chocolate per capita than any other country." },
  ],
  austria: [
    { name: "Wiener Schnitzel", description: "Breaded and fried veal cutlet, pounded thin and golden-crisp.", famousFor: "Austria's national dish — must be made with veal, not pork, to be authentic." },
    { name: "Sachertorte", description: "Rich chocolate cake with apricot jam, covered in dark chocolate glaze.", famousFor: "Invented in 1832 at Hotel Sacher in Vienna — a legendary recipe." },
    { name: "Apfelstrudel", description: "Paper-thin pastry rolled around spiced apples, raisins, and cinnamon.", famousFor: "A Viennese classic — the dough should be thin enough to read through." },
    { name: "Tafelspitz", description: "Boiled beef served with horseradish, apple sauce, and roasted potatoes.", famousFor: "Emperor Franz Joseph's favorite dish, a Viennese tradition." },
    { name: "Kaiserschmarrn", description: "Shredded fluffy pancake with rum-soaked raisins, dusted with powdered sugar.", famousFor: "Named after Emperor Franz Joseph I — a beloved Alpine dessert." },
  ],
  sweden: [
    { name: "Swedish Meatballs (Köttbullar)", description: "Small seasoned meatballs in cream sauce with lingonberry jam and mashed potatoes.", famousFor: "Sweden's most famous dish — yes, before IKEA made them global." },
    { name: "Smörgåsbord", description: "Elaborate buffet with herring, salmon, meatballs, cheeses, and breads.", famousFor: "A Swedish banquet tradition, especially at Christmas (Julbord)." },
    { name: "Kanelbullar (Cinnamon Buns)", description: "Soft cardamom-scented rolls with cinnamon and pearl sugar.", famousFor: "So beloved that Sweden has a national Cinnamon Bun Day (October 4)." },
    { name: "Gravlax", description: "Cured salmon with dill, sugar, and salt, served with hovmästarsås (mustard sauce).", famousFor: "A Scandinavian classic, the name means 'buried salmon'." },
    { name: "Surströmming", description: "Fermented Baltic Sea herring with an extremely pungent smell.", famousFor: "The world's smelliest food — must be opened outdoors!" },
  ],
  norway: [
    { name: "Brunost (Brown Cheese)", description: "Sweet, caramel-like whey cheese sliced thin with a cheese slicer.", famousFor: "Norway's national cheese — so beloved it once caused a tunnel fire/traffic jam." },
    { name: "Rakfisk", description: "Fermented trout served on flatbread with sour cream and onions.", famousFor: "A Norwegian delicacy with a 700-year history." },
    { name: "Fårikål", description: "Lamb and cabbage stew — Norway's designated national dish.", famousFor: "Voted Norway's national dish in 1972, eaten every autumn." },
    { name: "Smoked Salmon (Røkelaks)", description: "Cold-smoked Atlantic salmon, thinly sliced.", famousFor: "Norwegian salmon is exported worldwide and considered the finest quality." },
    { name: "Lefse", description: "Soft potato flatbread spread with butter, sugar, and cinnamon.", famousFor: "A traditional Norwegian treat, especially popular during holidays." },
  ],
  denmark: [
    { name: "Smørrebrød", description: "Open-faced rye bread topped with herring, shrimp, roast beef, or egg with elaborate garnishes.", famousFor: "Denmark's iconic lunch — an art form of layered toppings." },
    { name: "Frikadeller", description: "Pan-fried pork and veal meatballs with nutmeg and onion.", famousFor: "Denmark's beloved comfort food, served with potatoes and gravy." },
    { name: "Flæskesteg", description: "Roast pork with crispy crackling, served with red cabbage and potatoes.", famousFor: "The traditional Danish Christmas dinner centerpiece." },
    { name: "Danish Pastry (Wienerbrød)", description: "Flaky, buttery pastry with custard, fruit, or chocolate filling.", famousFor: "Ironically called 'Viennese bread' in Danish — perfected in Denmark." },
    { name: "Rød Grød med Fløde", description: "Red berry pudding with cream — also used to test if you can speak Danish!", famousFor: "A pronunciation challenge for non-Danes and a beloved summer dessert." },
  ],
  'czech republic': [
    { name: "Svíčková", description: "Marinated beef sirloin in creamy vegetable sauce with bread dumplings and cranberries.", famousFor: "The Czech national dish — comfort food at its finest." },
    { name: "Trdelník", description: "Chimney cake — spiraled dough grilled over charcoal, coated in sugar and walnuts.", famousFor: "Prague's most popular street food, though originally from Slovakia." },
    { name: "Vepřo Knedlo Zelo", description: "Roast pork with bread dumplings and sauerkraut.", famousFor: "A Czech pub classic — best paired with a pint of Czech pilsner." },
    { name: "Czech Pilsner Beer", description: "Golden lager originating from Plzeň, the birthplace of pilsner beer.", famousFor: "Pilsner Urquell invented the style in 1842 — Czechs drink more beer per capita than anyone." },
    { name: "Kolache", description: "Sweet pastry with fruit filling (plum, poppy seed, or cheese).", famousFor: "A Czech baking tradition brought to communities worldwide." },
  ],
  czechia: [
    { name: "Svíčková", description: "Marinated beef sirloin in creamy vegetable sauce with bread dumplings and cranberries.", famousFor: "The Czech national dish — comfort food at its finest." },
    { name: "Trdelník", description: "Chimney cake — spiraled dough grilled over charcoal, coated in sugar and walnuts.", famousFor: "Prague's most popular street food, though originally from Slovakia." },
    { name: "Vepřo Knedlo Zelo", description: "Roast pork with bread dumplings and sauerkraut.", famousFor: "A Czech pub classic — best paired with a pint of Czech pilsner." },
    { name: "Czech Pilsner Beer", description: "Golden lager originating from Plzeň, the birthplace of pilsner beer.", famousFor: "Pilsner Urquell invented the style in 1842 — Czechs drink more beer per capita than anyone." },
    { name: "Kolache", description: "Sweet pastry with fruit filling (plum, poppy seed, or cheese).", famousFor: "A Czech baking tradition brought to communities worldwide." },
  ],
  poland: [
    { name: "Pierogi", description: "Boiled dumplings with fillings like potato-cheese, sauerkraut, or meat.", famousFor: "Poland's most iconic dish — every region has its own variation." },
    { name: "Bigos (Hunter's Stew)", description: "Hearty stew of sauerkraut, fresh cabbage, and various meats, slow-cooked for hours.", famousFor: "Poland's national stew — traditionally made over several days for maximum flavor." },
    { name: "Żurek", description: "Sour rye soup with white sausage and hard-boiled egg, sometimes served in a bread bowl.", famousFor: "A uniquely Polish soup — tangy and hearty, especially popular at Easter." },
    { name: "Oscypek", description: "Smoked sheep's cheese from the Tatra Mountains, grilled and served with cranberry jam.", famousFor: "A protected regional specialty — can only be made by traditional shepherds in the Tatras." },
    { name: "Pączki", description: "Rich, filled doughnuts traditionally eaten on Fat Thursday before Lent.", famousFor: "On Fat Thursday, Poland consumes over 100 million pączki in a single day." },
  ],
  hungary: [
    { name: "Goulash (Gulyás)", description: "Rich paprika-spiced beef stew with potatoes, carrots, and dumplings.", famousFor: "Hungary's national dish — the original 'goulash' is a soup-stew, not a thick sauce." },
    { name: "Lángos", description: "Deep-fried flatbread topped with sour cream and grated cheese.", famousFor: "Hungary's favorite street food — found at every market and thermal bath." },
    { name: "Chicken Paprikash", description: "Chicken braised in paprika cream sauce, served with nokedli (egg noodles).", famousFor: "The dish that put Hungarian paprika on the world map." },
    { name: "Dobos Torte", description: "Five-layer sponge cake with chocolate buttercream and caramel top.", famousFor: "Created by József Dobos in 1884, it was one of the first modern cakes." },
    { name: "Kürtőskalács (Chimney Cake)", description: "Spiral-wound dough baked on a spit, coated in sugar, cinnamon, or nuts.", famousFor: "A Transylvanian-Hungarian treat — the original chimney cake." },
  ],
  croatia: [
    { name: "Peka", description: "Meat or seafood slow-roasted with vegetables under a bell-shaped lid covered in embers.", famousFor: "Croatia's most traditional cooking method — succulent and smoky." },
    { name: "Ćevapi", description: "Grilled minced meat sausages served in somun bread with onions and kajmak.", famousFor: "The Balkans' most popular street food, found across Croatia." },
    { name: "Black Risotto (Crni Rižot)", description: "Cuttlefish ink risotto with squid, a dramatic black color from the ink.", famousFor: "A Dalmatian coast specialty — stains your teeth but worth every bite." },
    { name: "Štrukli", description: "Rolled dough filled with cottage cheese, baked or boiled in cream.", famousFor: "A beloved Zagorje region comfort food — served as main dish or dessert." },
    { name: "Croatian Truffle Dishes", description: "Fresh Istrian truffles shaved over pasta, eggs, or risotto.", famousFor: "Istria is one of the world's greatest truffle regions — rivaling Italy." },
  ],
  'united arab emirates': [
    { name: "Al Machboos", description: "Spiced rice with meat (chicken or lamb), dried limes, and onions.", famousFor: "The UAE's national dish, similar to kabsa but with Emirati spices." },
    { name: "Shawarma", description: "Marinated meat from a rotating spit, wrapped in Arabic bread with garlic sauce.", famousFor: "Dubai's most popular street food — available 24/7." },
    { name: "Luqaimat", description: "Sweet fried dough balls drizzled with date syrup and sesame seeds.", famousFor: "A beloved Emirati dessert, especially during Ramadan." },
    { name: "Harees", description: "Slow-cooked wheat and meat porridge, smooth and comforting.", famousFor: "A traditional Ramadan iftar dish served across the Gulf." },
    { name: "Camel Burger", description: "Burger made with camel meat — a leaner alternative to beef.", famousFor: "A uniquely Emirati dining experience found in Dubai." },
  ],
  israel: [
    { name: "Hummus", description: "Creamy chickpea dip with tahini, lemon, and olive oil, scooped with fresh pita.", famousFor: "A national obsession — Israelis consume it at almost every meal." },
    { name: "Falafel", description: "Deep-fried chickpea balls in pita with salad, tahini, and pickles.", famousFor: "Israel's most iconic street food — debates rage over the best spot." },
    { name: "Shakshuka", description: "Eggs poached in spiced tomato sauce with peppers and onions.", famousFor: "Israel's beloved breakfast dish, eaten straight from the pan with bread." },
    { name: "Sabich", description: "Pita stuffed with fried eggplant, hard-boiled egg, hummus, and amba sauce.", famousFor: "An Iraqi-Jewish dish adopted as a top Israeli street food." },
    { name: "Borekas", description: "Flaky phyllo pastries filled with cheese, potato, or spinach.", famousFor: "A Sephardic Jewish tradition found at every Israeli bakery." },
  ],
  jordan: [
    { name: "Mansaf", description: "Lamb cooked in fermented dried yogurt (jameed), served over rice with pine nuts.", famousFor: "Jordan's national dish — eaten communally with hands from a shared platter." },
    { name: "Falafel", description: "Crispy fried chickpea patties in flatbread with pickles and tahini.", famousFor: "Jordan's most popular street food — freshly made at every corner." },
    { name: "Maqluba", description: "'Upside-down' rice pot with chicken, eggplant, and cauliflower, flipped onto a platter.", famousFor: "The dramatic upside-down presentation is the highlight of every meal." },
    { name: "Knafeh", description: "Crispy shredded filo layered with sweet cheese, soaked in rose-water syrup.", famousFor: "A Nabulsi dessert beloved in Jordan — best eaten warm and gooey." },
    { name: "Zarb", description: "Bedouin BBQ — meat and vegetables cooked underground in hot sand.", famousFor: "The authentic Wadi Rum desert dining experience." },
  ],
  'sri lanka': [
    { name: "Rice and Curry", description: "Rice served with an array of curries — dhal, fish, chicken, vegetable, and sambol.", famousFor: "Sri Lanka's staple meal — a colorful plate of 5-10 dishes at once." },
    { name: "Kottu Roti", description: "Chopped roti stir-fried with vegetables, egg, and spices on a hot griddle.", famousFor: "Sri Lanka's most popular street food — the rhythmic chopping sound is iconic." },
    { name: "Hoppers (Appa)", description: "Bowl-shaped rice flour and coconut milk crepe, often with an egg in the center.", famousFor: "A uniquely Sri Lankan breakfast — crispy edges, soft center." },
    { name: "Pol Sambol", description: "Fresh coconut relish with chili, onion, and lime.", famousFor: "The essential Sri Lankan condiment — served with every meal." },
    { name: "Ceylon Tea", description: "World-famous black tea grown in the hill country at elevations above 1,200m.", famousFor: "Sri Lanka is the world's 4th largest tea producer — tea plantations are a tourist attraction." },
  ],
  cambodia: [
    { name: "Amok", description: "Steamed fish curry in banana leaf with coconut milk, lemongrass, and kroeung paste.", famousFor: "Cambodia's national dish — delicate, creamy, and aromatic." },
    { name: "Lok Lak", description: "Stir-fried beef cubes with pepper-lime dipping sauce, served on lettuce.", famousFor: "A Franco-Khmer fusion dish, popular for lunch." },
    { name: "Bai Sach Chrouk", description: "Grilled pork over rice with pickled vegetables — Cambodia's classic breakfast.", famousFor: "Simple, satisfying, and found at every morning market stall." },
    { name: "Nom Banh Chok (Khmer Noodles)", description: "Rice noodles in green fish-based curry with fresh herbs and vegetables.", famousFor: "Called 'Khmer noodles' — the quintessential Cambodian breakfast." },
    { name: "Fried Tarantulas", description: "Deep-fried spiders seasoned with garlic and salt — a unique Cambodian snack.", famousFor: "Originally a survival food during the Khmer Rouge era, now a tourist attraction." },
  ],
  cuba: [
    { name: "Ropa Vieja", description: "Shredded beef in tomato sauce with peppers and onions — Cuba's national dish.", famousFor: "The name means 'old clothes' because the shredded meat resembles tattered fabric." },
    { name: "Cuban Sandwich", description: "Pressed sandwich with roast pork, ham, Swiss cheese, pickles, and mustard.", famousFor: "Born in Cuban immigrant communities in Florida, now globally famous." },
    { name: "Moros y Cristianos", description: "Black beans and white rice cooked together — 'Moors and Christians'.", famousFor: "A Cuban staple served at virtually every meal." },
    { name: "Tostones", description: "Twice-fried green plantain discs — crispy outside, soft inside.", famousFor: "Cuba's favorite side dish, served with everything." },
    { name: "Cuban Coffee (Cafecito)", description: "Strong, sweet espresso whipped with demerara sugar.", famousFor: "Tiny but powerful — a shot of pure Cuban energy and culture." },
  ],
};

export const extraMapCategoryData = {
  // New 25 countries
  malaysia: {
    bestFoodAreas: ["Jalan Alor, Kuala Lumpur", "Gurney Drive Hawkers, Penang", "Jonker Street, Malacca", "Bukit Bintang Food Court, KL", "Kota Kinabalu Filipino Market, Sabah"],
    nightlifeZones: ["Changkat Bukit Bintang, Kuala Lumpur", "TREC KL, Kuala Lumpur", "Upper Penang Road, Penang", "Bangsar, Kuala Lumpur", "Jalan Mesui, KL"],
    instagrammableSpots: ["Petronas Twin Towers KLCC, KL", "Batu Caves Rainbow Stairs, KL", "Chefchaouen of Malaysia Jalan Alor, KL", "The Top Rainbow Skywalk, Penang", "Langkawi Sky Bridge, Langkawi"],
    areasToAvoid: ["Chow Kit area at night, KL", "Brickfields at late night", "Remote areas of Sabah near Philippine border"],
    bestBeaches: ["Langkawi Beach, Kedah", "Perhentian Islands, Terengganu", "Redang Island, Terengganu", "Tioman Island, Pahang", "Tanjung Rhu Beach, Langkawi"],
  },
  'saudi arabia': {
    bestFoodAreas: ["Al Balad Historic District, Jeddah", "Tahlia Street, Riyadh", "Al Khobar Corniche, Eastern Province", "Bujairi Terrace, Diriyah", "Al Madinah food souqs, Medina"],
    nightlifeZones: ["Boulevard Riyadh City", "Jeddah Waterfront", "KAFD District, Riyadh", "Al Khobar Corniche", "The Zone, Riyadh"],
    instagrammableSpots: ["Edge of the World, Riyadh", "Al-Ula Elephant Rock, Medina Province", "KAFD Sphere, Riyadh", "Hegra Tombs, Al-Ula", "King Fahd Fountain, Jeddah"],
    areasToAvoid: ["Yemen border regions", "Remote desert areas without guides", "Near military installations"],
  },
  morocco: {
    bestFoodAreas: ["Jemaa el-Fnaa food stalls, Marrakech", "Rue des Consuls, Rabat", "Fez Medina food stalls, Fez", "Habous Quarter, Casablanca", "Essaouira Port fish grills, Essaouira"],
    nightlifeZones: ["Guéliz, Marrakech", "Ain Diab Corniche, Casablanca", "Kasbah Street, Tangier", "Hivernage, Marrakech", "Marina, Agadir"],
    instagrammableSpots: ["Chefchaouen Blue Streets, Chefchaouen", "Jardin Majorelle, Marrakech", "Hassan II Mosque, Casablanca", "Aït Benhaddou, Ouarzazate", "Erg Chebbi Dunes, Merzouga"],
    areasToAvoid: ["Rif Mountains drug-producing regions", "Isolated areas of Western Sahara", "Unlicensed taxis at night"],
    bestBeaches: ["Legzira Beach, Sidi Ifni", "Essaouira Beach, Essaouira", "Agadir Beach, Agadir", "Dakhla Beach, Dakhla", "Taghazout Beach, Agadir"],
  },
  colombia: {
    bestFoodAreas: ["La Candelaria, Bogotá", "Getsemaní, Cartagena", "El Poblado, Medellín", "San Antonio, Cali", "Granada, Cali"],
    nightlifeZones: ["Zona T, Bogotá", "Parque Lleras, Medellín", "Getsemaní, Cartagena", "San Antonio district, Cali", "Zona Rosa, Bogotá"],
    instagrammableSpots: ["Cartagena Old Town Walls, Cartagena", "Guatapé Rock (La Piedra del Peñol), Antioquia", "Cocora Valley Wax Palms, Salento", "Comuna 13 Street Art, Medellín", "Caño Cristales, Meta"],
    areasToAvoid: ["Catatumbo region at night", "Remote border areas with Venezuela", "Certain zones in Cali at night"],
  },
  'south africa': {
    bestFoodAreas: ["V&A Waterfront, Cape Town", "Maboneng Precinct, Johannesburg", "Florida Road, Durban", "Franschhoek Main Road, Western Cape", "Stellenbosch Wine Route, Western Cape"],
    nightlifeZones: ["Long Street, Cape Town", "Maboneng, Johannesburg", "Florida Road, Durban", "Camps Bay, Cape Town", "Melville, Johannesburg"],
    instagrammableSpots: ["Table Mountain Aerial Cableway, Cape Town", "Bo-Kaap Colorful Houses, Cape Town", "Blyde River Canyon, Mpumalanga", "Chapman's Peak Drive, Cape Town", "Cradle of Humankind, Gauteng"],
    areasToAvoid: ["Hillbrow and Berea, Johannesburg at night", "CBD areas after dark in most cities", "Isolated township areas without a guide"],
    bestBeaches: ["Camps Bay Beach, Cape Town", "Muizenberg Beach, Cape Town", "Umhlanga Rocks Beach, Durban", "Clifton Beaches, Cape Town", "Boulders Beach Penguin Colony, Simon's Town"],
  },
  singapore: {
    bestFoodAreas: ["Maxwell Food Centre, Chinatown", "Lau Pa Sat, CBD", "Chomp Chomp Hawker Centre, Serangoon", "Tiong Bahru Market, Tiong Bahru", "Old Airport Road Food Centre, Geylang"],
    nightlifeZones: ["Clarke Quay, Singapore River", "Ann Siang Hill, Chinatown", "Holland Village, Holland", "Boat Quay, Singapore River", "Orchard Road towers, CBD"],
    instagrammableSpots: ["Gardens by the Bay Supertree Grove, Marina Bay", "Marina Bay Sands Infinity Pool, Marina Bay", "Haji Lane, Kampong Glam", "Jewel Changi Airport Waterfall, Changi", "Buddha Tooth Relic Temple, Chinatown"],
    areasToAvoid: ["Geylang Red Light District at late night", "Little India on weekday nights (very crowded)"],
  },
  philippines: {
    bestFoodAreas: ["Poblacion, Makati Manila", "Mercato Centrale Night Market, Taguig", "Carbon Market, Cebu City", "Iloilo La Paz Market, Iloilo", "Binondo Chinatown, Manila"],
    nightlifeZones: ["Poblacion, Makati Manila", "Bonifacio Global City, Taguig", "Station I, Boracay", "Mango Avenue, Cebu City", "Malate, Manila"],
    instagrammableSpots: ["El Nido Big Lagoon, Palawan", "Chocolate Hills, Bohol", "Banaue Rice Terraces, Ifugao", "Mayon Volcano, Albay", "Kawasan Falls, Cebu"],
    areasToAvoid: ["Tondo, Manila at night", "Parts of Mindanao (Marawi, Sulu)", "Quiapo at night, Manila"],
    bestBeaches: ["White Beach, Boracay", "El Nido Beach, Palawan", "Nacpan Beach, El Nido", "Alona Beach, Panglao", "Siargao Cloud 9, Surigao"],
  },
  'new zealand': {
    bestFoodAreas: ["Ponsonby Road, Auckland", "Cuba Street, Wellington", "Eat Street, Rotorua", "Lyttelton Main Street, Christchurch", "Queenstown Mall, Queenstown"],
    nightlifeZones: ["Viaduct Harbour, Auckland", "Courtenay Place, Wellington", "Queenstown CBD, Queenstown", "Victoria Street, Christchurch", "Ponsonby Road, Auckland"],
    instagrammableSpots: ["Milford Sound, Fiordland", "Hobbiton Movie Set, Matamata", "Lake Tekapo Church, Canterbury", "Roy's Peak, Wanaka", "Tongariro Crossing Emerald Lakes, Tongariro"],
    areasToAvoid: ["South Auckland late at night", "Isolated hiking trails alone (inform someone)"],
    bestBeaches: ["Cathedral Cove, Coromandel", "Hot Water Beach, Coromandel", "Piha Beach, Auckland", "Abel Tasman Coast, Nelson", "Mount Maunganui Beach, Bay of Plenty"],
  },
  ireland: {
    bestFoodAreas: ["Temple Bar area, Dublin", "English Market, Cork", "Latin Quarter, Galway", "Dingle Town, Kerry", "Kinsale, Cork"],
    nightlifeZones: ["Temple Bar, Dublin", "Quay Street, Galway", "Oliver Plunkett Street, Cork", "The Docks, Limerick", "Cathedral Quarter, Belfast"],
    instagrammableSpots: ["Cliffs of Moher, County Clare", "Ring of Kerry viewpoints, County Kerry", "Dark Hedges, County Antrim", "Skellig Michael, County Kerry", "Kylemore Abbey, Connemara"],
    areasToAvoid: ["O'Connell Street very late at night, Dublin", "Some inner city areas late at night"],
  },
  netherlands: {
    bestFoodAreas: ["Albert Cuyp Market, Amsterdam", "Markthal, Rotterdam", "De Pijp neighborhood, Amsterdam", "Grote Markt, Haarlem", "Noordermarkt, Amsterdam"],
    nightlifeZones: ["Leidseplein, Amsterdam", "Rembrandtplein, Amsterdam", "Witte de Withstraat, Rotterdam", "Stratumseind, Eindhoven", "Grote Markt, Groningen"],
    instagrammableSpots: ["Keukenhof Tulip Gardens, Lisse", "Kinderdijk Windmills, Kinderdijk", "Rijksmuseum, Amsterdam", "Cube Houses, Rotterdam", "Amsterdam Canal Houses, Amsterdam"],
    areasToAvoid: ["Red Light District late at night alone", "Bijlmer area, Amsterdam Southeast at night"],
  },
  switzerland: {
    bestFoodAreas: ["Bahnhofstrasse, Zürich", "Old Town, Bern", "Carouge, Geneva", "Altstadt, Lucerne", "Markthalle, Basel"],
    nightlifeZones: ["Langstrasse, Zürich", "Bains des Pâquis area, Geneva", "Steinenvorstadt, Basel", "Aarbergergasse, Bern", "Flon Quarter, Lausanne"],
    instagrammableSpots: ["Matterhorn from Stellisee, Zermatt", "Chapel Bridge, Lucerne", "Jungfraujoch Top of Europe, Bernese Oberland", "Rhine Falls, Schaffhausen", "Lake Brienz, Interlaken"],
    areasToAvoid: ["Switzerland is generally very safe — no major areas to avoid"],
  },
  austria: {
    bestFoodAreas: ["Naschmarkt, Vienna", "Getreidegasse, Salzburg", "Grieskai, Graz", "Maria-Theresien-Straße, Innsbruck", "Bäckerstraße, Vienna"],
    nightlifeZones: ["Bermuda Triangle (Bermudadreieck), Vienna", "Gürtel Quarter, Vienna", "Rudolfskai, Salzburg", "Universitätsviertel, Graz", "Bogen, Innsbruck"],
    instagrammableSpots: ["Hallstatt Lake View, Hallstatt", "Schönbrunn Palace Gardens, Vienna", "Salzburg Fortress from Mirabell Garden, Salzburg", "Grossglockner High Alpine Road, Carinthia", "Golden Roof, Innsbruck"],
    areasToAvoid: ["Praterstern area at night, Vienna", "Certain areas near Westbahnhof at night, Vienna"],
  },
  sweden: {
    bestFoodAreas: ["Södermalm, Stockholm", "Haga District, Gothenburg", "Malmö Saluhall, Malmö", "Östermalmshallen, Stockholm", "Feskekörka Fish Market, Gothenburg"],
    nightlifeZones: ["Stureplan, Stockholm", "Avenyn, Gothenburg", "Södermalm/SoFo, Stockholm", "Lilla Torg, Malmö", "Gamla Stan, Stockholm"],
    instagrammableSpots: ["Gamla Stan Old Town, Stockholm", "Abisko Aurora Sky Station, Abisko", "Stockholm Archipelago, Stockholm", "Turning Torso, Malmö", "ICEHOTEL, Jukkasjärvi"],
    areasToAvoid: ["Rinkeby suburb at night, Stockholm", "Rosengård at night, Malmö"],
  },
  norway: {
    bestFoodAreas: ["Mathallen Food Hall, Oslo", "Fisketorget Fish Market, Bergen", "Solsiden, Trondheim", "Strandkaien, Stavanger", "Aker Brygge, Oslo"],
    nightlifeZones: ["Aker Brygge, Oslo", "Bryggen area, Bergen", "Solsiden, Trondheim", "Grünerløkka, Oslo", "Vågen area, Stavanger"],
    instagrammableSpots: ["Trolltunga, Odda", "Preikestolen (Pulpit Rock), Stavanger", "Geirangerfjord, Geiranger", "Lofoten Islands, Nordland", "Northern Lights in Tromsø, Tromsø"],
    areasToAvoid: ["Grønland area late at night, Oslo", "Remote mountain trails without preparation"],
  },
  denmark: {
    bestFoodAreas: ["Torvehallerne, Copenhagen", "Kødbyen (Meatpacking District), Copenhagen", "Strøget area, Copenhagen", "Aarhus Street Food, Aarhus", "Nyhavn, Copenhagen"],
    nightlifeZones: ["Vesterbro/Kødbyen, Copenhagen", "Nyhavn, Copenhagen", "Gothersgade area, Copenhagen", "Jægergårdsgade, Aarhus", "Nørrebro, Copenhagen"],
    instagrammableSpots: ["Nyhavn Colorful Houses, Copenhagen", "Tivoli Gardens, Copenhagen", "The Little Mermaid, Copenhagen", "Mons Klint White Cliffs, Møn", "Kronborg Castle, Helsingør"],
    areasToAvoid: ["Christiania late at night (Pusher Street), Copenhagen", "Nørrebro at very late hours"],
  },
  'czech republic': {
    bestFoodAreas: ["Manifesto Market, Prague", "Lokál pubs, Prague", "Stodolní area, Ostrava", "Zelný trh Market, Brno", "Dlouhá Street, Prague"],
    nightlifeZones: ["Dlouhá Street, Prague Old Town", "Žižkov district, Prague", "Cross Club, Prague", "Stodolní Street, Ostrava", "Veveří, Brno"],
    instagrammableSpots: ["Charles Bridge at sunrise, Prague", "Prague Castle, Prague", "Český Krumlov, South Bohemia", "Astronomical Clock, Prague", "Dancing House, Prague"],
    areasToAvoid: ["Wenceslas Square at very late night, Prague", "Holešovice industrial areas at night, Prague"],
  },
  czechia: {
    bestFoodAreas: ["Manifesto Market, Prague", "Lokál pubs, Prague", "Stodolní area, Ostrava", "Zelný trh Market, Brno", "Dlouhá Street, Prague"],
    nightlifeZones: ["Dlouhá Street, Prague Old Town", "Žižkov district, Prague", "Cross Club, Prague", "Stodolní Street, Ostrava", "Veveří, Brno"],
    instagrammableSpots: ["Charles Bridge at sunrise, Prague", "Prague Castle, Prague", "Český Krumlov, South Bohemia", "Astronomical Clock, Prague", "Dancing House, Prague"],
    areasToAvoid: ["Wenceslas Square at very late night, Prague", "Holešovice industrial areas at night, Prague"],
  },
  poland: {
    bestFoodAreas: ["Kazimierz District, Kraków", "Hala Koszyki, Warsaw", "Plac Nowy, Kraków", "Łazarz Market, Poznań", "Stary Browar area, Poznań"],
    nightlifeZones: ["Kazimierz, Kraków", "Nowy Świat, Warsaw", "Mazowiecka Street, Warsaw", "Łódź OFF Piotrkowska, Łódź", "Stare Miasto, Wrocław"],
    instagrammableSpots: ["Wawel Castle, Kraków", "Warsaw Old Town, Warsaw", "Wieliczka Salt Mine, Wieliczka", "Wrocław Cathedral Island, Wrocław", "Malbork Castle, Malbork"],
    areasToAvoid: ["Praga Północ at night, Warsaw", "Industrial zones of cities after dark"],
  },
  hungary: {
    bestFoodAreas: ["Central Market Hall, Budapest", "Gozsdu Courtyard, Budapest", "Koleves Kert, Budapest", "Liszt Ferenc tér, Budapest", "Karaván Street Food, Budapest"],
    nightlifeZones: ["Ruin Bars in Jewish Quarter, Budapest", "Gozsdu Courtyard, Budapest", "Király utca, Budapest", "Deák Ferenc tér area, Budapest", "Szimpla Kert area, Budapest"],
    instagrammableSpots: ["Parliament from Fisherman's Bastion, Budapest", "Széchenyi Thermal Baths, Budapest", "Szimpla Kert Ruin Bar, Budapest", "Buda Castle, Budapest", "Shoes on the Danube Bank, Budapest"],
    areasToAvoid: ["District VIII (Józsefváros) at night, Budapest", "Keleti station area late at night, Budapest"],
  },
  croatia: {
    bestFoodAreas: ["Dubrovnik Old Town, Dubrovnik", "Dolac Market, Zagreb", "Riva Promenade, Split", "Rovinj Old Town, Rovinj", "Zadar Old Town, Zadar"],
    nightlifeZones: ["Bačvice Beach clubs, Split", "Hvar Town, Hvar Island", "Tkalčićeva Street, Zagreb", "Dubrovnik Old Town bars, Dubrovnik", "Zrće Beach, Pag Island"],
    instagrammableSpots: ["Dubrovnik Old Town Walls, Dubrovnik", "Plitvice Lakes, Lika-Senj", "Hvar Lavender Fields, Hvar", "Zadar Sea Organ, Zadar", "Rovinj Old Town, Rovinj"],
    areasToAvoid: ["Some areas near Slavonski Brod at night", "Former minefields in rural Slavonia — stick to marked paths"],
    bestBeaches: ["Zlatni Rat Beach, Brač", "Stiniva Beach, Vis", "Bačvice Beach, Split", "Dubrovnik Banje Beach, Dubrovnik", "Sakarun Beach, Dugi Otok"],
  },
  'united arab emirates': {
    bestFoodAreas: ["Al Dhiyafah Road, Dubai", "Yas Island Restaurants, Abu Dhabi", "JBR The Walk, Dubai", "Saadiyat Island, Abu Dhabi", "Al Seef Heritage District, Dubai"],
    nightlifeZones: ["JBR and Dubai Marina, Dubai", "Downtown Dubai, Dubai", "Yas Island, Abu Dhabi", "DIFC, Dubai", "Barsha Heights, Dubai"],
    instagrammableSpots: ["Burj Khalifa At The Top, Dubai", "Sheikh Zayed Grand Mosque, Abu Dhabi", "Dubai Frame, Dubai", "Louvre Abu Dhabi, Abu Dhabi", "Palm Jumeirah Boardwalk, Dubai"],
    areasToAvoid: ["UAE is generally very safe — no major areas to avoid", "Sharjah Industrial Area at night"],
    bestBeaches: ["JBR Beach, Dubai", "Saadiyat Island Beach, Abu Dhabi", "Kite Beach, Dubai", "La Mer Beach, Dubai", "Al Mamzar Beach Park, Dubai"],
  },
  israel: {
    bestFoodAreas: ["Carmel Market (Shuk HaCarmel), Tel Aviv", "Machane Yehuda Market, Jerusalem", "Levinsky Market, Tel Aviv", "Nahalat Binyamin, Tel Aviv", "German Colony, Haifa"],
    nightlifeZones: ["Rothschild Boulevard, Tel Aviv", "Florentin, Tel Aviv", "Port Area, Tel Aviv", "Ben Yehuda Street, Jerusalem", "Masada Street, Haifa"],
    instagrammableSpots: ["Western Wall, Jerusalem", "Bahá'í Gardens, Haifa", "Tel Aviv Bauhaus buildings, Tel Aviv", "Masada Sunrise, Dead Sea", "Dead Sea Floating, Ein Bokek"],
    areasToAvoid: ["Gaza border area", "Parts of the West Bank without proper guidance", "Check travel advisories for current situation"],
  },
  jordan: {
    bestFoodAreas: ["Rainbow Street, Amman", "Downtown Al Balad, Amman", "Hashem Restaurant area, Amman", "Aqaba Fish Market, Aqaba", "Madaba, Madaba"],
    nightlifeZones: ["Rainbow Street, Amman", "Abdoun, Amman", "Sweifieh, Amman", "Jabal Amman, Amman", "Aqaba Marina, Aqaba"],
    instagrammableSpots: ["Petra Treasury (Al-Khazneh), Wadi Musa", "Wadi Rum Desert Camp, Aqaba", "Dead Sea, Sweimeh", "Amman Citadel, Amman", "Dana Nature Reserve, Tafila"],
    areasToAvoid: ["Syrian border regions", "Certain areas of downtown Amman very late at night"],
    bestBeaches: ["Aqaba South Beach, Aqaba", "Tala Bay, Aqaba", "Berenice Beach Club, Aqaba"],
  },
  'sri lanka': {
    bestFoodAreas: ["Pettah Market, Colombo", "Galle Face Green street food, Colombo", "Dutch Hospital Shopping Precinct, Colombo", "Galle Fort, Galle", "Kandy Market, Kandy"],
    nightlifeZones: ["Colombo Fort area, Colombo", "Park Street area, Colombo", "Unawatuna Beach bars, Galle", "Mirissa Beach, Matara", "Mount Lavinia, Colombo"],
    instagrammableSpots: ["Sigiriya Rock Fortress, Matale", "Nine Arch Bridge, Ella", "Galle Fort Lighthouse, Galle", "Temple of the Tooth, Kandy", "Nuwara Eliya Tea Plantations, Nuwara Eliya"],
    areasToAvoid: ["Northern Province former conflict areas (use caution)", "Pettah at night, Colombo"],
    bestBeaches: ["Unawatuna Beach, Galle", "Mirissa Beach, Matara", "Arugam Bay, Eastern Province", "Bentota Beach, Bentota", "Tangalle Beach, Hambantota"],
  },
  cambodia: {
    bestFoodAreas: ["Pub Street, Siem Reap", "Russian Market, Phnom Penh", "Street 308, Phnom Penh", "Old Market area, Siem Reap", "Kampot Riverfront, Kampot"],
    nightlifeZones: ["Pub Street, Siem Reap", "Bassac Lane, Phnom Penh", "Street 278 (Golden Street), Phnom Penh", "Otres Beach, Sihanoukville", "Kampot Riverside bars, Kampot"],
    instagrammableSpots: ["Angkor Wat Sunrise, Siem Reap", "Ta Prohm Tree Roots, Siem Reap", "Royal Palace, Phnom Penh", "Kampot Pepper Farms, Kampot", "Koh Rong Sanloem Beach, Sihanoukville"],
    areasToAvoid: ["Parts of Sihanoukville at night (casino areas)", "Remote border areas with Thailand"],
    bestBeaches: ["Koh Rong Sanloem, Sihanoukville", "Otres Beach, Sihanoukville", "Koh Rong Long Beach, Sihanoukville", "Kep Beach, Kep"],
  },
  cuba: {
    bestFoodAreas: ["La Bodeguita del Medio area, Old Havana", "San Cristóbal area, Old Havana", "Plaza Vieja, Old Havana", "Trinidad town center, Trinidad", "Viñales town, Pinar del Río"],
    nightlifeZones: ["Malecón, Havana", "Calle Obispo, Old Havana", "Vedado, Havana", "Casa de la Música, Trinidad", "Casa de la Trova, Santiago de Cuba"],
    instagrammableSpots: ["Old Havana vintage cars, Havana", "Viñales Valley, Pinar del Río", "Trinidad cobblestone streets, Trinidad", "Malecón sunset, Havana", "Plaza Mayor, Trinidad"],
    areasToAvoid: ["Centro Habana at late night", "Isolated areas without street lighting"],
    bestBeaches: ["Varadero Beach, Matanzas", "Playa Paraíso, Cayo Largo", "Playa Ancón, Trinidad", "Guardalavaca Beach, Holguín", "Cayo Coco, Ciego de Ávila"],
  },
};
